### ISSUE TITLE
Exception while opening any detailview from listview 

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#1002]
XAF : 23.1.3
Xpand : 23.1.301

15.06.23 12:07:48.595	================================================================================
The error occurred:

	Type:       ArgumentException
	Message:    Object of type 'System.EventHandler`1[System.EventArgs]' cannot be converted to type 'System.EventHandler`1[DevExpress.ExpressApp.Win.Editors.LookupEditProviderEventArgs]'.
	Data:       0 entries
	Stack trace:

   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(StackAllocedArguments& stackArgs, ReadOnlySpan`1 parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Xpand.Extensions.Reactive.Transform.Transform.<>c__DisplayClass111_0`1.<FromEventPattern>b__0(EventHandler`1 handler)
   at System.Reactive.Linq.ObservableImpl.ClassicEventProducer`2.AddHandler(TDelegate handler) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEvent.cs:line 360
   at System.Reactive.Linq.ObservableImpl.EventProducer`2.Session.AddHandler(TDelegate onNext) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEvent.cs:line 325
	InnerException is null

================================================================================

**Comment by apobekiaris** [comment]
the fix is on lab soon to be released, thnks

**Comment by apobekiaris** [comment]
eXpand.lab release [23.1.301.1](https://github.com/eXpandFramework/eXpand.lab/releases/23.1.301.1) includes commit that relate to this task:

* [Update rx packages #1002](https://github.com/eXpandFramework/eXpand.lab/commit/4e95447f1919d1985a2ae51d2e1c319ade7e4d59)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
is this fix ok?

**Comment by vimarx** [comment]
yes , close #1002

**Comment by apobekiaris** [comment]
eXpand.lab release [23.1.502.0](https://github.com/eXpandFramework/eXpand.lab/releases/23.1.502.0) includes commit that relate to this task:

* [Update rx packages #1002](https://github.com/eXpandFramework/eXpand.lab/commit/a28811d7a7ef2763f07315a055f3e290109ecab3)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.
