### ISSUE TITLE
Null reference  exception closing form in 23.1.303

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#1009]
Closing form  (net 6.0 windows)

04.07.23 14:35:35.845	FirstChanceException event raised in JIT.Win: Object reference not set to an instance of an object.    at Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorService.<>c__DisplayClass30_1.<GetObjectForSave>b__5()
   at System.Reactive.Linq.ObservableImpl.Finally`1._.Dispose(Boolean disposing) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Finally.cs:line 67
   at System.Reactive.Disposables.CompositeDisposable.Remove(IDisposable item) in /_/Rx.NET/Source/src/System.Reactive/Disposables/CompositeDisposable.cs:line 214
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 964
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.SafeObserver`1.WrappingSafeObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Internal/SafeObserver.cs:line 30
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 950
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at System.ComponentModel.Component.Dispose(Boolean disposing)
   at DevExpress.ExpressApp.Xpo.XPObjectSpace.DisposeSession(Session session)
   at DevExpress.ExpressApp.Xpo.XPObjectSpace.Dispose()
   at DevExpress.ExpressApp.CompositeView.DisposeObjectSpace()
   at DevExpress.ExpressApp.CompositeView.DisposeCore()
   at DevExpress.Persistent.Base.SafeExecutor.Execute(Method method, Object targetObject, String targetObjectIdentifier)
04.07.23 14:35:35.847	FirstChanceException event raised in JIT.Win: Object reference not set to an instance of an object.    at Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorService.<>c__DisplayClass30_1.<GetObjectForSave>b__5()
   at System.Reactive.Linq.ObservableImpl.Finally`1._.Dispose(Boolean disposing) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Finally.cs:line 67
   at System.Reactive.Disposables.CompositeDisposable.Remove(IDisposable item) in /_/Rx.NET/Source/src/System.Reactive/Disposables/CompositeDisposable.cs:line 214
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 964
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.SafeObserver`1.WrappingSafeObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Internal/SafeObserver.cs:line 30
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 950
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at System.ComponentModel.Component.Dispose(Boolean disposing)
   at DevExpress.ExpressApp.Xpo.XPObjectSpace.DisposeSession(Session session)
   at DevExpress.ExpressApp.Xpo.XPObjectSpace.Dispose()
   at DevExpress.ExpressApp.CompositeView.DisposeObjectSpace()
   at DevExpress.ExpressApp.CompositeView.DisposeCore()
   at DevExpress.Persistent.Base.SafeExecutor.Execute(Method method, Object targetObject, String targetObjectIdentifier)
   at DevExpress.ExpressApp.View.Dispose()
   at DevExpress.Persistent.Base.SafeExecutor.Execute(Method method, Object targetObject, String targetObjectIdentifier)
04.07.23 14:35:35.850	================================================================================
The error occurred:

	Type:       NullReferenceException
	Message:    Object reference not set to an instance of an object.
	Data:       0 entries
	Stack trace:

   at Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorService.<>c__DisplayClass30_1.<GetObjectForSave>b__5()
   at System.Reactive.Linq.ObservableImpl.Finally`1._.Dispose(Boolean disposing) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Finally.cs:line 67
   at System.Reactive.Disposables.CompositeDisposable.Remove(IDisposable item) in /_/Rx.NET/Source/src/System.Reactive/Disposables/CompositeDisposable.cs:line 214
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 964
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.Sink`1.ForwardOnCompleted() in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 54
   at System.Reactive.SafeObserver`1.WrappingSafeObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Internal/SafeObserver.cs:line 30
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 950
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at System.ComponentModel.Component.Dispose(Boolean disposing)
   at DevExpress.ExpressApp.Xpo.XPObjectSpace.DisposeSession(Session session)
   at DevExpress.ExpressApp.Xpo.XPObjectSpace.Dispose()
   at DevExpress.ExpressApp.CompositeView.DisposeObjectSpace()
   at DevExpress.ExpressApp.CompositeView.DisposeCore()
   at DevExpress.Persistent.Base.SafeExecutor.Execute(Method method, Object targetObject, String targetObjectIdentifier)
   at DevExpress.ExpressApp.View.Dispose()
   at DevExpress.Persistent.Base.SafeExecutor.Execute(Method method, Object targetObject, String targetObjectIdentifier)
   at DevExpress.ExpressApp.Frame.Dispose()
   at System.ComponentModel.Component.Dispose(Boolean disposing)
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.Windows.Forms.Form.Dispose(Boolean disposing)
   at DevExpress.XtraEditors.XtraForm.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.DForm.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
	InnerException is null

**Comment by apobekiaris** [comment]
This stack is not helping can u try to sample me?

**Comment by vimarx** [comment]
Will try to reproduce it in a smaller environment...

**Comment by apobekiaris** [comment]
which view is this? the storage DetailView?

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
