### ISSUE TITLE
[23.1] Can not open ModelDifference detailview

### ISSUE THREAD

**Issue by Kagandaj** [eXpandFramework/eXpand#1018]
𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
1. Create new xaf win application (dx_23.1)
2. Add eXpandModelDifferenceWin
3. Run application navigate to application settings
4. select one entry and open detailview
5. error 

Sequence contains no elements

   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at Xpand.Extensions.XAF.ApplicationModulesManagerExtensions.ApplicationModulesManagerExtensions.Application(ApplicationModulesManager manager)
   at Xpand.Extensions.XAF.ApplicationModulesManagerExtensions.ApplicationModulesManagerExtensions.CreateModel(ApplicationModulesManager manager, IEnumerable`1 aspects, ModelStoreBase modelDifferenceStore)
   at Xpand.Persistent.Base.ModelDifference.ModelBuilder.BuildModel(XafApplication application, String configFileName, XpandApplicationModulesManager applicationModulesManager)
   at Xpand.Persistent.Base.ModelDifference.ModelBuilder.Build(Boolean rebuild)
   at Xpand.Persistent.Base.ModelDifference.ModelLoader.GetMasterModelCore(Boolean rebuild)
   at Xpand.Persistent.Base.ModelDifference.ModelLoader.GetMasterModel(XafApplication xafApplication, Action`1 action)
   at Xpand.Persistent.Base.ModelDifference.ModelLoader.<>c__DisplayClass12_0.<GetMasterModel>b__0()
   at Xpand.Utils.Helpers.Retry.<>c__DisplayClass0_0.<Do>b__0()
   at Xpand.Utils.Helpers.Retry.Do[T](Func`1 action, TimeSpan retryInterval, Int32 retryCount)

**Comment by apobekiaris** [comment]
eXpand.lab release [23.1.601.1](https://github.com/eXpandFramework/eXpand.lab/releases/23.1.601.1) includes commit that relate to this task:

* [ModelDifference: Cannot open detailview when DI #1018](https://github.com/eXpandFramework/eXpand.lab/commit/fa62b4baf32067b8c70473634f2c551fdab27146)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
attaching my test project for reference
[DXApplication1.zip](https://github.com/eXpandFramework/eXpand/files/13266148/DXApplication1.zip)

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
