### ISSUE TITLE
Model Editor failed to load. - 'FontStyle' property specified was not found.

### ISSUE THREAD

**Issue by pavlovboris** [eXpandFramework/eXpand#1031]
Hello, 

After updating to 23.1.601.3,  Devexpress model editor won't start on any project with the following exception : System.Reflection.CustomAttributeFormatException: 'FontStyle' property specified was not found. ---> 

The XpandModelEditor seems to work as expected. 

Thank you for your great work and support!

Model Editor Log : 

24.11.2023 г. 16:16:38 : Enter SetExceptionForModelEditorAsync
24.11.2023 г. 16:16:45 : System.Reflection.CustomAttributeFormatException: 'FontStyle' property specified was not found. ---> System.Reflection.CustomAttributeFormatException: 'FontStyle' property specified was not found. ---> StreamJsonRpc.RemoteInvocationException: 'FontStyle' property specified was not found.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DevExpress.ExpressApp.Design.ClientHost.<OpenModelEditorAsync>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DevExpress.ExpressApp.Design.ClientHost.<>c__DisplayClass134_0.<<OpenModelEditor>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DevExpress.ExpressApp.Design.ClientHost.<>c__DisplayClass120_0.<<RunAsync>b__0>d.MoveNext()
RPC server exception:
System.Reflection.CustomAttributeFormatException: 'FontStyle' property specified was not found.
 ---> System.Reflection.CustomAttributeFormatException: 'FontStyle' property specified was not found.
      at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   --- End of inner exception stack trace ---
      at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
      at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
      at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
      at System.RuntimeType.GetCustomAttributes(Boolean inherit)
      at DevExpress.Xpo.Metadata.ReflectionClassInfo.GetCustomAttributes(Type classType)
      at DevExpress.Xpo.Metadata.ReflectionClassInfo..ctor(Type classType, XPDictionary dictionary)
      at DevExpress.Xpo.Metadata.ReflectionDictionary.CreateClassInfo(Type classType)
      at DevExpress.Xpo.Metadata.ReflectionDictionary.ResolveClassInfoByType(Type classType)
      at DevExpress.ExpressApp.DC.Xpo.XafReflectionDictionary.ResolveClassInfoByType(Type classType)
      at DevExpress.Xpo.Metadata.ReflectionDictionary.QueryClassInfo(Type classType)
      at DevExpress.Xpo.Metadata.XPDictionary.GetClassInfo(Type classType)
      at DevExpress.Xpo.Metadata.XPMemberInfo.get_CollectionElementType()
      at DevExpress.Xpo.Metadata.XPMemberInfo.GetAssociatedMember()
      at DevExpress.ExpressApp.DC.Xpo.XpoTypeInfoSource.InitMemberInfo(XafMemberInfo member, XPMemberInfo xpMember)
      at DevExpress.ExpressApp.DC.Xpo.XpoTypeInfoSource.InitMemberInfo(ITypeInfo owner, XafMemberInfo member, Object memberSource)
      at DevExpress.ExpressApp.DC.Xpo.XpoTypeInfoSource.InitMemberInfo(Object memberSource, XafMemberInfo member)
      at Xpand.Persistent.Base.Xpo.XpandXpoTypeInfoSource.DevExpress.ExpressApp.DC.ITypeInfoSource.InitMemberInfo(Object member, XafMemberInfo memberInfo) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\Xpo\XpandXpoTypeInfoSource.cs:line 40
      at DevExpress.ExpressApp.DC.TypeInfo.InitializeMember(Object member, String memberName)
      at DevExpress.ExpressApp.DC.Xpo.XpoTypeInfoSource.EnumXPClassMembers(TypeInfo info, EnumMembersHandler handler)
      at DevExpress.ExpressApp.DC.Xpo.XpoTypeInfoSource.EnumMembers(TypeInfo info, EnumMembersHandler handler)
      at Xpand.Persistent.Base.Xpo.XpandXpoTypeInfoSource.DevExpress.ExpressApp.DC.ITypeInfoSource.EnumMembers(TypeInfo info, EnumMembersHandler handler) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\Xpo\XpandXpoTypeInfoSource.cs:line 15
      at DevExpress.ExpressApp.DC.TypeInfo.GetOwnMembers()
      at DevExpress.ExpressApp.DC.TypeInfo.Refresh(Boolean refreshMembers)
      at DevExpress.ExpressApp.DC.Xpo.XpoTypeInfoSource.RegisterEntity(Type type)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.EnsureReferencesForEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntity(Type entityType)
      at DevExpress.ExpressApp.DC.TypesInfo.RegisterEntities(IEnumerable`1 types)
      at DevExpress.ExpressApp.ApplicationModulesManager.LoadDomainComponents(ITypesInfo typesInfo)
      at DevExpress.ExpressApp.ApplicationModulesManager.LoadTypesInfo(ITypesInfo typesInfo)
      at DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
      at DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(XafApplication application, String configFileName, String assembliesPath, Action initializeTypeInfoSources)
      at DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, String targetDiffFileName, IDisposable& obj, ILogger logger)
      at DevExpress.ExpressApp.Design.ModelEditor.ModelEditorFormController.CreateModelEditorController()
      at DevExpress.ExpressApp.Design.ModelEditor.ModelEditorFormController.Init()
      at DevExpress.ExpressApp.Design.ModelEditorServer.ServerHost.CreateNewModelEditor(String fileName, ModelEditorInfo meInfo, String projectUniqueName, Dictionary`2 settings, String frameworkVersion)
      at DevExpress.ExpressApp.Design.ModelEditorServer.ServerHost.<>c__DisplayClass66_0.<OpenModelEditor>b__1()
      at DevExpress.ExpressApp.Design.ModelEditorServer.UiRunner.<>c__DisplayClass3_0.<RunOnUIThreadCore>b__0(Object _)
   --- End of stack trace from previous location ---
      at DevExpress.ExpressApp.Design.ModelEditorServer.ServerHost.OpenModelEditor(String fileName, String projectUniqueName, Dictionary`2 settings, String frameworkVersion)
      at DevExpress.ExpressApp.Design.ModelEditorServer.ServerProtocol.OpenModelEditor(String xafmlFileName, String projectUniqueName, Dictionary`2 settings, String frameworkVersion)
      at InvokeStub_IServerReceiveProtocol.OpenModelEditor(Object, Object, IntPtr*)
      at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of stack trace from previous location ---
      at DevExpress.ExpressApp.Design.ModelEditorServer.LoggedServerProtocol`1.Invoke(MethodInfo targetMethod, Object[] args)
      at generatedProxy_1.OpenModelEditor(String, String, Dictionary`2, String)
      at InvokeStub_generatedProxy_1.OpenModelEditor(Object, Object, IntPtr*)
      at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

   Exception_EndOfInnerExceptionStack

**Comment by apobekiaris** [comment]
I would search all files in all dirs for this property `FontStyle` maybe it can give us a clue what's going on, if not I require a sample reproducing the case.

**Comment by apobekiaris** [comment]
a tip from the XAF team, it maybe a version conflict e.g. if u use different a version TypeA!=TypeA

**Comment by pavlovboris** [comment]
Thank you, for the tip.  Found out the following : 
exception is thrown when FontStyle is used inappearance rule in code with [Appearance]

BR

**Comment by apobekiaris** [comment]
if u can repro it and does not involve eXpandFramework, you need to ask the DX support

**Comment by pavlovboris** [comment]
Thanks for the hints! 
Found out the following:
 if I need to remove CriteriaOperator.RegisterCustomFunction( ICustomFunctionOperator)
 and I need to remove all attributes that have [Appearance ... FontStyle](Excel importer as well(ExcelColumnMap)) than the model editor loads correctly. 
As far as your suggestion, I will try to repro and will contact DX if find more, but the exception occurs only when  23.1.601.3/23.1.601.2, it does not appear with 23.1.601.1 that why I thought that its something with exPand.

**Comment by apobekiaris** [comment]
>As far as your suggestion, I will try to repro and will contact DX if find more, but the exception occurs only when 23.1.601.3/23.1.601.2 is installed, it does not appear with 23.1.601.1 that why I thought that its something with exPand.

it still can be a version conflict, but in any case as I can not repro it nor my tests or my apps fail, I can only help u If I have a repro sample

**Comment by pavlovboris** [comment]
Dont want to lose our time anymore on this, I can live without the appearance attribute  FontStyle in Code and without excelimporter module. Maybe I will try to repro later only with excelimporter module, Can close for now. 

Thank you and BR
