### ISSUE TITLE
Model Editor Error 

### ISSUE THREAD

**Issue by DannyRawlings** [eXpandFramework/eXpand#1051]
Hi ya,

I have been unable to open the model editor since rebuilding my Windows OS

I have found this error in the Model Editor log file under the path "AppData\Local\Xpand\Xpand.XAF.ModelEditor.Win\4.232.2.0"

**Xpand.XAF.ModelEditor.Win Error: 0 : 22.03.24 15:31:37.175	================================================================================
The error occurred:

	Type:       InvalidProjectFileException
	Message:    The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.**

Is there anything you can recommend to resolve this?

Cheers

Dan

**Comment by apobekiaris** [comment]
given that u have 6,7,8 sdk installed and at least a system restart

the only thing I find it strange is the path mine is on 

AppData\Roaming\Xpand.XAF.ModelEditor.Win\WinDesktop\net8.0\4.232.2.0\

**Comment by DannyRawlings** [comment]
I will try and reinstall it as my Roaming folder path looks different to yours

![image](https://github.com/eXpandFramework/eXpand/assets/7148712/618ff403-22f7-4ac3-a565-d76b771b1201)

**Comment by DannyRawlings** [comment]
Still no luck after a reinstall - The version being installed via Visual Studio is older than the release on GitHub. I have also tried to install via the VSIX file but that fails 

![image](https://github.com/eXpandFramework/eXpand/assets/7148712/3ba959ab-ea96-4c5d-9606-f49b14145a77)

![image](https://github.com/eXpandFramework/eXpand/assets/7148712/e5db8545-f3aa-4977-9609-2cc7b3ded491)

**Comment by DannyRawlings** [comment]
Update - I have now tried a different user on my machine and the error is the same. I have also reinstall both .net 7 & 8 sdks

**Comment by DannyRawlings** [comment]
So - When I first run the editor I see it pop up, the 'Parsing Projects' appears followed by nothing on my screen.

This is the full error I see in the log 

Type:       InvalidProjectFileException
	Message:    The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Users\i007106\source\repos\DXApplication2\DXApplication2.Module\DXApplication2.Module.csproj
	Data:       0 entries
	Stack trace:

   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, String toolsVersion)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName)
   at Xpand.XAF.ModelEditor.Module.Win.MSBuildExtensions.<>c__DisplayClass1_0.<Projects>b__1(ProjectInSolution projectInSolution) in C:\Work\Reactive.XAF\tools\Xpand.XAF.ModelEditor\IDE\ModelEditor.Win\Xpand.XAF.ModelEditor.Module.Win\MSBuildExtensions.cs:line 23
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value)
	InnerException is null

**Comment by DannyRawlings** [comment]
ok, I have finally figured out how to get it to work.  I download the Model zip files and extracted it to the 'Roaming\Xpand.XAF.ModelEditor.Win\WinDesktop\net7.0\4.232.4.0' after that it seems to be happy. The issue was that it was not creating the WinDesktop folder

**Comment by DannyRawlings** [comment]
That was just a sample project I created using the Wizard - I wanted a project that had nothing in it to make sure that my project wasn't causing the issue

**Comment by apobekiaris** [comment]
if u still have it post it here please

**Comment by DannyRawlings** [comment]
No probs - see attached
[DXApplication2.zip](https://github.com/eXpandFramework/eXpand/files/14742800/DXApplication2.zip)

**Comment by expand** [comment]
i have pushed a new version for both IDE and tested your solution while first clean the Roaming ME folder and worked fine.

Note, that you should have a folder with the solution targetframework

for me is 

C:\Users\Tolis\AppData\Roaming\Xpand.XAF.ModelEditor.Win\WinDesktop\net7.0\4.232.4.0\

**Comment by expand** [comment]
the files are downloaded in the C:\Users\Tolis\AppData\Roaming\Xpand.XAF.ModelEditor.Win

previosuly i mentioned that AppData\Local\Xpand\Xpand.XAF.ModelEditor.Win\4.232.2.0 looks different, my bad that is also correct is the location of the log. The ME is in C:\Users\Tolis\AppData\Roaming\Xpand.XAF.ModelEditor.Win

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
