### ISSUE TITLE
Model Editor Error - String Value is too long

### ISSUE THREAD

**Issue by DannyRawlings** [eXpandFramework/eXpand#1060]
Hello

I am not sure what has changed - But I am getting the following error when loading the ME. 

It seems to relate to the file path of my project as I have tested it and it works fine with shorter file paths. But from my perspective, this has always been the same - I've not changed anything from myside.

Issue is tested with both .Net 7 and .Net 8. I have tried the usual re install etc... 

Any help is appreciated, below is as much info as I could find. 

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
DevExpress.Xpo.DB.Helpers.InMemorySetException: String value is too long.
   at DevExpress.Xpo.DB.Helpers.InMemoryRow.CheckValues(Boolean setDefaults, Boolean checkAutoIncrement)
   at DevExpress.Xpo.DB.Helpers.InMemoryRow..ctor(InMemoryTable table, ICollection`1 initData)
   at DevExpress.Xpo.DB.Helpers.DataSetStoreHelpersFull.DoInsertRecord(InMemoryTable table, QueryParameterCollection parameters, CriteriaOperatorCollection operands, ParameterValue identityParameter, TaggedParametersHolder identitiesByTag)
   at DevExpress.Xpo.DB.InMemoryDataStore.<>c__DisplayClass32_0.<ProcessModifyData>b__0()
` 

**ExpressAppFramework Log extract**

`Xpand.XAF.ModelEditor.Win Error: 0 : 04.06.24 10:04:51.755	================================================================================
The error occurred:

	Type:       SqlExecutionErrorException
	Message:    Executing Sql 'insert into XafModel values ('CLAAS_Dealer_Tools.Blazor.Server\Model_en-GB', 1, 'C:\Users\i007106\OneDrive - CLAAS\Dokumente\Development\Web\Blazor\CLAAS Dealer Tools\CLAAS_Dealer_Tools.Blazor.Server\Model_en-GB.xafml', False, 0)' with parameters '' exception 'DevExpress.Xpo.DB.Helpers.InMemorySetException: String value is too long.
   at DevExpress.Xpo.DB.Helpers.InMemoryRow.CheckValues(Boolean setDefaults, Boolean checkAutoIncrement)
   at DevExpress.Xpo.DB.Helpers.InMemoryRow..ctor(InMemoryTable table, ICollection`1 initData)
   at DevExpress.Xpo.DB.Helpers.DataSetStoreHelpersFull.DoInsertRecord(InMemoryTable table, QueryParameterCollection parameters, CriteriaOperatorCollection operands, ParameterValue identityParameter, TaggedParametersHolder identitiesByTag)
   at DevExpress.Xpo.DB.InMemoryDataStore.<>c__DisplayClass32_0.<ProcessModifyData>b__0()'
	Data:       0 entries
	Stack trace:

   at Xpand.Extensions.XAF.XafApplicationExtensions.XafApplicationExtensions.HandleException(XafApplication application, Exception exception)
   at System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value)
	----------------
	InnerException:

			Type:       InMemorySetException
			Message:    String value is too long.
			Data:       0 entries
			Stack trace:

   at DevExpress.Xpo.DB.Helpers.InMemoryRow.CheckValues(Boolean setDefaults, Boolean checkAutoIncrement)
   at DevExpress.Xpo.DB.Helpers.InMemoryRow..ctor(InMemoryTable table, ICollection`1 initData)
   at DevExpress.Xpo.DB.Helpers.DataSetStoreHelpersFull.DoInsertRecord(InMemoryTable table, QueryParameterCollection parameters, CriteriaOperatorCollection operands, ParameterValue identityParameter, TaggedParametersHolder identitiesByTag)
   at DevExpress.Xpo.DB.InMemoryDataStore.<>c__DisplayClass32_0.<ProcessModifyData>b__0()
			InnerException is null`

![image](https://github.com/eXpandFramework/eXpand/assets/7148712/18eb47bf-aaa5-49cb-8980-870ff94cb7c0)
![image](https://github.com/eXpandFramework/eXpand/assets/7148712/50a59491-6133-4ce9-8c30-ce7c2e40ac04)

**Comment by apobekiaris** [comment]
HI 

you sure you are on the latest version? of the plugin? which is your version?

**Comment by DannyRawlings** [comment]
I have also tested the project by moving it to the root of the drive - still same error

This is the version I am using after it was reinstalled via Visual Studio

![image](https://github.com/eXpandFramework/eXpand/assets/7148712/fffa69b3-8491-4b19-a869-8c395d9e1d10)

**Comment by apobekiaris** [comment]
apparently the problem is with C:\Users\i007106\OneDrive - CLAAS\Dokumente\Development\Web\Blazor\CLAAS Dealer Tools\CLAAS_Dealer_Tools.Blazor.Server\Model_en-GB.xafml

move the project to a shorter path to workaround it until I publish a fix

**Comment by DannyRawlings** [comment]
No rush from my side, but I already moved it to a shorter path and still had the same issue.

**Comment by apobekiaris** [comment]
C:\Users\i007106\OneDrive - CLAAS\Dokumente\Development\Web\Blazor\CLAAS Dealer Tools\CLAAS_Dealer_Tools.Blazor.Server\Model_en-GB.xafml

should be 100 characters or less as per XPO default column size, VS plugin is now online please try it and let me know

**Comment by DannyRawlings** [comment]
It works again now. Thank you again

**Comment by DannyRawlings** [comment]
Resolved
