### ISSUE TITLE
IO: export only nonempty members

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#153]
Is there a way to export only members that have values? Export files for large number of records are becoming unmanageable and redundant in cases when only few random columns have values but total number of columns is large.

**Comment by apobekiaris** [comment]
Can you elab a bit over the case, having a detailed example will speed up a possible enhancement id needed

**Comment by emeyke** [comment]
Here is 1 record of exported file example:
https://www.dropbox.com/s/puxz5biarxytsmf/1.xml?dl=0

Here is same record with fields that have values
https://www.dropbox.com/s/idg04v3ss8d113b/2.xml?dl=0

There seems to be no reason to have those empty properties in the file when they do not affect abything except the size.

Unless I got something wrong.

**Comment by apobekiaris** [comment]
thnks now i have a very clear picture, I will update you once implemented.

**Comment by emeyke** [comment]
Great. Thanks Tolis.

**Comment by emeyke** [comment]
Getting "Instances of abstract classes cannot be created." with minified on. Without it works.
Just in case the export file that is created without minifying:
https://www.dropbox.com/s/bhxhuylamgz232o/nominify.xml?dl=0


	Type:       InvalidOperationException
	Message:    Instances of abstract classes cannot be created.
	Data:       0 entries
	Stack trace:

   at ctor(Object )
   at Xpand.ExpressApp.IO.Core.ExportEngineExtensions.HasDefaultValue[T](T memberInfo, Object memberValue)
   at Xpand.ExpressApp.IO.Core.ExportEngine.SetMemberValue(ITypeInfo typeInfo, Object theObject, IClassInfoGraphNode classInfoGraphNode, XElement propertyElement)
   at Xpand.ExpressApp.IO.Core.ExportEngine.ExportCore(Object selectedObject, IEnumerable`1 serializedClassInfoGraphNodes, XElement root, ElementSchema elementSchema)
   at Xpand.ExpressApp.IO.Core.ExportEngine.Export(IEnumerable`1 baseCollection, ISerializationConfigurationGroup serializationConfigurationGroup)
   at Xpand.ExpressApp.IO.Controllers.IOViewControllerBase.Export(ISerializationConfigurationGroup selectedObject)
   at Xpand.ExpressApp.IO.Controllers.IOViewControllerBase.AcceptActionOnExecuteCompleted(Object sender, ActionBaseEventArgs actionBaseEventArgs)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.OnExecuted(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	InnerException is null

**Comment by apobekiaris** [comment]
from the stack i understand that you tried to export a non persistent abstract member and the code failed. I fixed it in next milestone can you try this assembly or need an installer?

**Comment by apobekiaris** [comment]
[Xpand.ExpressApp.IO.zip](https://github.com/eXpandFramework/eXpand/files/2358861/Xpand.ExpressApp.IO.zip)

**Comment by emeyke** [comment]
Thanks Tolis.
Will it be in 18.1.5.6? or only in 18.1.6.2?

**Comment by expand** [comment]
18.1.6.2

**Comment by emeyke** [comment]
With the current 15.1.5.5 version I am getting this when importing. Worked with 15.1.5.4.
![image](https://user-images.githubusercontent.com/234025/45219440-9a27f480-b2b3-11e8-9cf6-1857d931677f.png)

**Comment by apobekiaris** [comment]
the screenshot does not help, provide the stack

**Comment by emeyke** [comment]
07.09.18 15:32:16.340		Type: DevExpress.ExpressApp.Actions.SimpleAction
								ID: Save
								Category: Save
								Controller.Name: DevExpress.ExpressApp.Win.SystemModule.WinModificationsController
								Context.Name: File Chooser
								Context.IsRoot: True
								Context.SelectedObjects.Count: 1
								Context.CurrentObject: Xpand.Persistent.BaseImpl.ImportExport.FileChooser

07.09.18 15:32:16.359	Action 'Save' done
ECDB.IO.Win.exe Error: 0 : 07.09.18 15:32:56.263	================================================================================
The error occurred:

	Type:       NullReferenceException
	Message:    Object reference not set to an instance of an object.
	Data:       0 entries
	Stack trace:

   at Xpand.Persistent.Base.General.ObjectSpaceExtensions.Create[T](IObjectSpace objectSpace)
   at Xpand.ExpressApp.IO.Core.ImportEngine.HandleError(XElement element, FailReason failReason, ElementSchema elementSchema)
   at Xpand.ExpressApp.IO.Core.ImportEngine.ImportObjects(XDocument document, Func`2 objectSpaceQuery)
   at Xpand.ExpressApp.IO.Core.ImportEngine.ImportObjects(Stream stream, Func`2 objectSpaceQuery)
   at DevExpress.ExpressApp.Actions.SimpleActionExecuteEventHandler.Invoke(Object sender, SimpleActionExecuteEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	InnerException is null

**Comment by emeyke** [comment]
test file that imported fine with 18.1.5.4
https://www.dropbox.com/s/b77wc1j5ees4tlc/test.xml?dl=0

**Comment by apobekiaris** [comment]
the stack implies that the `CreateObjectSpace()` is called and returned null
https://github.com/eXpandFramework/eXpand/blob/d21ddb753915eeeca6b5f3a1e99e22ce5a8bb3c9/Xpand/Xpand.ExpressApp.Modules/IO/Controllers/IOViewControllerBase.cs#L96-L100

I am afraid I cannot see why this happens and does not sound related to any recent change.

**Comment by apobekiaris** [comment]
so you need to provide some info on why your ObjectSpaceProvider returns null

**Comment by emeyke** [comment]
Replicated the problem with IOTester.
Steps:
Add domain object
Create serialization configuration with Minified=False;
Export objects
Import back.

Results:

Object reference not set to an instance of an object.

   at Xpand.Persistent.Base.General.ObjectSpaceExtensions.Create[T](IObjectSpace objectSpace)
   at Xpand.ExpressApp.IO.Core.ImportEngine.HandleError(XElement element, FailReason failReason, ElementSchema elementSchema)
   at Xpand.ExpressApp.IO.Core.ImportEngine.ImportObjects(XDocument document, Func`2 objectSpaceQuery)
   at Xpand.ExpressApp.IO.Core.ImportEngine.ImportObjects(Stream stream, Func`2 objectSpaceQuery)
   at DevExpress.ExpressApp.Actions.SimpleActionExecuteEventHandler.Invoke(Object sender, SimpleActionExecuteEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**Comment by apobekiaris** [comment]
what about 18.1.6.1 is it the same?

**Comment by emeyke** [comment]
yes

**Comment by apobekiaris** [comment]
I fix it in this patched assembly.

[Xpand.ExpressApp.IO.zip](https://github.com/eXpandFramework/eXpand/files/2367059/Xpand.ExpressApp.IO.zip)

**Comment by emeyke** [comment]
Thanks! Will wait till released

**Comment by apobekiaris** [comment]
Unfortunately the patches are no versioned correctly so I cannot easy tell if you using the patched assembly or not. I have to fix that problem first.

**Comment by apobekiaris** [comment]
here a [patched](https://www.dropbox.com/s/x8i8q86nfokbs43/eXpandFramework-18.1.6.17.exe?dl=0) installer. If you still having the same error check that your log for the loaded assemblies. They must version 18.1.6.17

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
