### ISSUE TITLE
How to refresh Xpand Dashbboard

### ISSUE THREAD

**Issue by david0villa** [eXpandFramework/eXpand#162]
Hi all,

Can someone advise me how to refresh dashboard ? I tried to click on Refresh button and all data becomes blank on dashboard

**Comment by apobekiaris** [comment]
try a screenshot please so we can follow u easier and most probably the log would be helpful in this case.

**Comment by david0villa** [comment]
Hi,
 
I am using this xml below, 1st open is loading  all data which we expected. However, click on refresh button on the top makes dashboard data blank. I am leaving xpand setting as default as very new to it. Hope this clears

<?xml version="1.0" encoding="utf-8"?>
<Dashboard CurrencyCulture="en-US">
  <Title Text="Dashboard" />
  <DataSources>
    <ObjectDataSource ComponentName="eCourierPickup">
      <Name>eCourierPickup</Name>
      <DataSource Type="TestObject.eCourierPickup, Module, Version=1.0.6823.15619, Culture=neutral, PublicKeyToken=null" />
      <Filter>[DeletedDate] Is Null And [CreatedDate] &gt; #2018-06-03#</Filter>
    </ObjectDataSource>
  </DataSources>
  <Items>
    <Pivot ComponentName="pivotDashboardItem1" Name="Pivot 1" DataSource="eCourierPickup">
      <DataItems>
        <Measure DataMember="Id" DefaultId="DataItem1" />
        <Dimension DataMember="Caption" DefaultId="DataItem0" />
      </DataItems>
      <Columns>
        <Column DefaultId="DataItem0" />
      </Columns>
      <Values>
        <Value DefaultId="DataItem1" />
      </Values>
    </Pivot>
  </Items>
  <LayoutTree>
    <LayoutGroup>
      <LayoutItem DashboardItem="pivotDashboardItem1" />
    </LayoutGroup>
  </LayoutTree>
</Dashboard>

**Comment by david0villa** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<Dashboard CurrencyCulture="en-US" >
  <Title Text="Dashboard" />
  <DataSources>
    <ObjectDataSource ComponentName="eCourierPickup">
      <Name>eCourierPickup</Name>
      <DataSource Type="TestObject.eCourierPickup, Module, Version=1.0.6823.15619, Culture=neutral, PublicKeyToken=null" />
      <Filter>[DeletedDate] Is Null And [CreatedDate] &gt; #2018-06-03#</Filter>
    </ObjectDataSource>
  </DataSources>
  <Items>
    <Pivot ComponentName="pivotDashboardItem1" Name="Pivot 1" DataSource="eCourierPickup">
      <DataItems>
        <Measure DataMember="Id" DefaultId="DataItem1" />
        <Dimension DataMember="Caption" DefaultId="DataItem0" />
      </DataItems>
      <Columns>
        <Column DefaultId="DataItem0" />
      </Columns>
      <Values>
        <Value DefaultId="DataItem1" />
      </Values>
    </Pivot>
  </Items>
  <LayoutTree>
    <LayoutGroup>
      <LayoutItem DashboardItem="pivotDashboardItem1" />
    </LayoutGroup>
  </LayoutTree>
</Dashboard>`

**Comment by apobekiaris** [comment]
try this 


![image](https://user-images.githubusercontent.com/159464/45292945-6d681d00-b4ff-11e8-932e-b5f0cddaf551.png)

**Comment by david0villa** [comment]
`
<?xml version="1.0" encoding="utf-8"?>
<Dashboard CurrencyCulture="en-US" DesignerAutomaticUpdates="false">
  <Title Text="Dashboard" />
  <DataSources>
    <ObjectDataSource ComponentName="eCourierPickup">
      <Name>eCourierPickup</Name>
      <DataSource Type="TestObject.eCourierPickup, Module, Version=1.0.6823.15619, Culture=neutral, PublicKeyToken=null" />
      <Filter>[DeletedDate] Is Null And [CreatedDate] &gt; #2018-06-03#</Filter>
    </ObjectDataSource>
  </DataSources>
  <Items>
    <Pivot ComponentName="pivotDashboardItem1" Name="Pivot 1" DataSource="eCourierPickup">
      <DataItems>
        <Measure DataMember="Id" DefaultId="DataItem1" />
        <Dimension DataMember="Caption" DefaultId="DataItem0" />
      </DataItems>
      <Columns>
        <Column DefaultId="DataItem0" />
      </Columns>
      <Values>
        <Value DefaultId="DataItem1" />
      </Values>
    </Pivot>
  </Items>
  <LayoutTree>
    <LayoutGroup>
      <LayoutItem DashboardItem="pivotDashboardItem1" />
    </LayoutGroup>
  </LayoutTree>
[</Dashboard>]

`

**Comment by david0villa** [comment]
![xml](https://user-images.githubusercontent.com/43064318/45293496-b211a980-b53b-11e8-8d26-ae0ea6df6c8d.png)

Sorry I could not post xml
I am using this xml below, 1st open is loading all data which we expected. However, click on refresh button on the top makes dashboard data blank. I am leaving xpand setting as default as very new to it. Hope this clears. I hope with any data changed, dashboard would be changed accordingly when click on refresh

**Comment by apobekiaris** [comment]
it should be enough give me some time please as I am loaded at the moment and see my previous post on how to post your xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<Application >

</Application>
```

**Comment by david0villa** [comment]
Thank you very much for your prompt help. XML as below

```xml
<?xml version="1.0" encoding="utf-8"?>
<Dashboard CurrencyCulture="en-US">
  <Title Text="Dashboard" />
  <DataSources>
    <ObjectDataSource ComponentName="eCourierPickup">
      <Name>eCourierPickup</Name>
      <DataSource Type="TestObject.eCourierPickup, Module, Version=1.0.6823.15619, Culture=neutral, PublicKeyToken=null" />
      <Filter>[DeletedDate] Is Null And [CreatedDate] &gt; #2018-06-03#</Filter>
    </ObjectDataSource>
  </DataSources>
  <Items>
    <Pivot ComponentName="pivotDashboardItem1" Name="Pivot 1" DataSource="eCourierPickup">
      <DataItems>
        <Measure DataMember="Id" DefaultId="DataItem1" />
        <Dimension DataMember="Caption" DefaultId="DataItem0" />
      </DataItems>
      <Columns>
        <Column DefaultId="DataItem0" />
      </Columns>
      <Values>
        <Value DefaultId="DataItem1" />
      </Values>
    </Pivot>
  </Items>
  <LayoutTree>
    <LayoutGroup>
      <LayoutItem DashboardItem="pivotDashboardItem1" />
    </LayoutGroup>
  </LayoutTree>
</Dashboard>

```

**Comment by apobekiaris** [comment]
your xml has nothing strange but I do not understand how to repro it. Which refresh you hit DataboardDefintion_DetailView?

can you provide your sample solution ?

**Comment by david0villa** [comment]
`Internal error. Please contact the application vendor or your system administrator and provide the following information.

DevExpress.Data.Filtering.CriteriaCompilerException: Error 'Can't find property 'DeletedDate'' at '[DeletedDate]' compiling criteria '[DeletedDate] Is Null And AddDays([CreatedDate], 5) > Now()' ---> DevExpress.Data.Filtering.Exceptions.InvalidPropertyPathException: Can't find property 'DeletedDate'
   at DevExpress.Data.Filtering.Helpers.CriteriaCompilerContextDescriptorDefaultBase.MakePropertyAccessCoreChecked(Expression baseExpression, String property)
   at DevExpress.Data.Filtering.Helpers.CriteriaCompilerContextDescriptorDefaultBase.MakePropertyAccess(Expression baseExpression, String propertyPath)
   at DevExpress.Data.Filtering.Helpers.CriteriaCompilerCore.Process(CriteriaOperator criteria)
   --- End of inner exception stack trace ---
   at DevExpress.Data.Filtering.Helpers.CriteriaCompilerCore.Compile(CriteriaCompilerDescriptor descriptor, CriteriaCompilerAuxSettings settings, CriteriaOperator op)
   at DevExpress.DataProcessing.DataReaderExEnumerableWrapper.CreateFilterPredicate(CriteriaOperator filterCriteria)
   at DevExpress.DataProcessing.DataReaderExEnumerableWrapper..ctor(String[] dataMembers, IEnumerable source, PropertyDescriptorCollection properties, CustomFunctionCollection customFunctions, CriteriaOperator filterCriteria, Int32 numberOfRows)
   at DevExpress.DashboardCommon.DashboardObjectDataSource.ExecuteReader(Action`1 action, CriteriaOperator filterCriteria, Int32 numberOfRows, String[] schema)
   at DevExpress.DashboardCommon.DashboardObjectDataSource.GetStorageInternal(CancellationToken token)
   at DevExpress.DashboardCommon.DashboardObjectDataSource.DevExpress.DashboardCommon.Native.IDashboardDataSourceInternal.GetStorage(String dataMember)
   at DevExpress.DashboardCommon.DataProcessing.DataSourceModel.Create(IDashboardDataSource ds, String dataMember)
   at DevExpress.DashboardCommon.DataProcessing.DataSourceModel.Create(IDashboardDataSource ds, String dataMember, IDataFlowStorage storage)
   at DevExpress.DashboardCommon.Native.DataSourceModelsProvider.GetDataSourceModel(String dataSourceName, String dataMember, IDataFlowStorage storage)
   at DevExpress.DashboardCommon.Native.DashboardColoringValuesProvider.GetColoringValuesCore(IDataSourceMetadata dataSourceMetadata, String dataMember, IEnumerable`1 definitions, IEnumerable`1 filterDimensions, CriteriaOperator filter, IList`1 dashboardItems, IEnumerable`1 items, IActualParametersProvider parameters)
   at DevExpress.DashboardCommon.Native.DashboardColoringValuesProvider.DevExpress.DashboardCommon.Native.IColoringValuesProvider.GetColoringValues(ColorRepositoryKey repositoryKey)
   at DevExpress.DashboardCommon.Native.ColorSchemeGenerator.BuildTable(ColorRepositoryKey repositoryKey, MeasureDefinition[][] measures)
   at DevExpress.DashboardCommon.Native.ColorSchemeGenerator.GenerateColoring()
   at DevExpress.DashboardCommon.Native.ColorSchemeGenerator.GenerateColoringCache(IColoringValuesProvider provider, ColorRepository repository, Int32 paletteColorsCount)
   at DevExpress.DashboardCommon.Server.DashboardSession.EnsureDashboardColoringCache()
   at DevExpress.DashboardCommon.Service.DashboardServiceOperation`1.Execute(DashboardServiceResult result)

If I am putting the filter under data source then the error message above showing up, although the last version of xpand works well. The issue only happens when I upgraded to xpand 18.1.5. I am struggling with Refresh button and tried to fix that.  If no filter putting into data source then click on Refresh no error but data on dashboard becomes blank. The below screenshot is where we click on Refresh. 

![refresh_button](https://user-images.githubusercontent.com/43064318/45329090-12d3cd00-b5a2-11e8-99b6-4e4b09aa6299.png)
`

**Comment by apobekiaris** [comment]
Can you try this [path](https://www.dropbox.com/s/pdnsnblek8om99o/eXpandFramework-18.1.6.12.exe?dl=0). It includes #157 in which the related to your case easytest works fine.
https://github.com/eXpandFramework/eXpand/tree/18.1/Demos/Modules/SystemTester/SystemTester.Module/FunctionalTests/SequenceGenerator

**Comment by apobekiaris** [comment]
you do not need to modify anything from MSSQLConnectionProvider and its descendants

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
