### ISSUE TITLE
Security Permission

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#183]
Hello,

I have the following issue in our XAF app : 

From Winform client, i can create report and execute them. 
From Web client i can create report but not execute them. 

In attachement the error and the stacktrace . 
Any idea where it can come from ? 

First i reported this to devexpress it seems to come from security module in Web only. 

https://www.devexpress.com/Support/Center/Question/Details/T675480/reportv2-asp-preview

[Report Web Execute Issue.docx](https://github.com/eXpandFramework/eXpand/files/2414115/Report.Web.Execute.Issue.docx)

BR
ISA

**Comment by apobekiaris** [comment]
looks related to #177

**Comment by apobekiaris** [comment]
do you use `XpandRole` or implement the `IXpandRoleCustomPermissions`?

**Comment by isatahiri** [comment]
Hello,

No we do not use this module. 
But due to dependencies i cannot remove it apparently. 
![image](https://user-images.githubusercontent.com/41955268/46006676-6113c080-c0b8-11e8-8eb5-c0f01f67fb72.png)

**Comment by isatahiri** [comment]
I do not see any link with #177 
What makes you think this ? 

BR
ISA

**Comment by apobekiaris** [comment]
in #177 I suggested to disable the IO action using a ModelArtifact permission which use the security module.

>do you use XpandRole or implement the IXpandRoleCustomPermissions?

What I meant is that your Role must derive from XPandRole or implement IXpandRoleCustomPermissions for the Security permissions to work.

**Comment by isatahiri** [comment]
Hello,

I have not implemented yet what you suggested in #177.

My current role is : 
`[DefaultClassOptions, XafDisplayName("Security role"), ImageName("BO_Department"), DefaultProperty("Name")]
    public class KBA_UserRole : PermissionPolicyRoleBase, IPermissionPolicyRoleWithUsers
    { // Inherit from a different class to provide a custom primary key, concurrency and deletion behavior, etc. (https://documentation.devexpress.com/eXpressAppFramework/CustomDocument113146.aspx).
        public KBA_UserRole(Session session)
            : base(session)
        {
        }
        public override void AfterConstruction()
        {
            base.AfterConstruction();
            // Place your initialization code here (https://documentation.devexpress.com/eXpressAppFramework/CustomDocument112834.aspx).
        }

        public bool CanExport
        {
            get { return GetPropertyValue<bool>("CanExport"); }
            set { SetPropertyValue<bool>("CanExport", value); }
        }

        [XafDisplayName("Can synch session's attendees with Exchange")]
        public bool CanSyncSessionAttendeesWithExchange
        {
            get { return GetPropertyValue<bool>("CanSyncSessionAttendeesWithExchange"); }
            set { SetPropertyValue<bool>("CanSyncSessionAttendeesWithExchange", value); }
        }

        [Association("Users-UserRoles")]
        public XPCollection<KBA_User> Users
        {
            get
            {
                return GetCollection<KBA_User>("Users");
            }
        }
        IEnumerable<IPermissionPolicyUser> IPermissionPolicyRoleWithUsers.Users
        {
            get { return Users.OfType<IPermissionPolicyUser>(); }
        }
    }`

So should i replace IPermissionPolicyRoleWithUsers by IXpandRoleCustomPermissions or just add IXpandRoleCustomPermissions. 

How should i use IList<IOperationPermissionProvider> IXpandRoleCustomPermissions.Permissions  ? 
Can you redirect me to some sample please ? 

BR
ISA

**Comment by isatahiri** [comment]
You say > What I meant is that your Role must derive from XPandRole or implement IXpandRoleCustomPermissions for the Security permissions to work.

But this is in the module directly. So as i haven't done this yet, how possible i receive this error only in web client. In win client it is working without any error. 

BR
ISA

**Comment by apobekiaris** [comment]
give me some time please to research further.

note that #177 is implemented in 18.1.6.2 so if the user cannot read any SerializationConfiguration the IO action will be disabled so you wont need the custom permission

**Comment by apobekiaris** [comment]
Can you post your log?

**Comment by isatahiri** [comment]
iisexpress.exe Error: 0 : 24.09.18 17:27:35.335	no context	================================================================================
The error occurred:

	Type:       Exception
	Message:    Error when trying to populate the datasource. The following exception was thrown: 
Object reference not set to an instance of an object.
	Data:       0 entries
	Stack trace:

   at DevExpress.XtraPrinting.PrintingSystemBase.OnCreateDocumentException(ExceptionEventArgs args)
   at DevExpress.XtraReports.UI.XtraReport.TryCreateDocument(Single progressRange, Boolean buildPagesInBackground)
   at DevExpress.XtraReports.UI.XtraReport.CreateDocument(Boolean buildForInstantPreview)
   at DevExpress.XtraReports.Web.WebDocumentViewer.Native.Services.DocumentBuilder.<>c__DisplayClass3.<StartBuild>b__2()
	----------------
	InnerException:

			Type:       DataRetrievalException
			Message:    Error when trying to populate the datasource. The following exception was thrown: 
Object reference not set to an instance of an object.
			Data:       0 entries
			Stack trace:

   at DevExpress.XtraReports.Native.DataSourceFiller.Execute()
   at DevExpress.XtraReports.UI.XtraReportBase.FillDataSources(Boolean skipIfFilled)
   at DevExpress.XtraReports.UI.XtraReport.OnBeforePrint(PrintEventArgs e)
   at DevExpress.XtraReports.UI.XtraReport.TryCreateDocument(Single progressRange, Boolean buildPagesInBackground)
			----------------
			InnerException:

					Type:       NullReferenceException
					Message:    Object reference not set to an instance of an object.
					Data:       0 entries
					Stack trace:

   at Xpand.ExpressApp.Security.Core.SecuritySystemExtensions.WithCustomPermissions(IPermissionDictionary permissionDictionary)
   at Xpand.ExpressApp.Security.XpandSecurityModule.CustomizeRequestProcessors(CustomizeRequestProcessorsEventArgs e)
   at Xpand.ExpressApp.Security.XpandSecurityModule.OnCustomizeRequestProcessors(Object sender, CustomizeRequestProcessorsEventArgs e)
   at DevExpress.ExpressApp.Security.SecurityStrategy.OnCustomizeRequestProcessors(IDictionary`2 processors, IPermissionDictionary permissionsDictionary)
   at DevExpress.ExpressApp.Security.SecurityStrategy.SelectDataSecurityProvider_CustomizeRequestProcessors(Object sender, CustomizeRequestProcessorsEventArgs e)
   at DevExpress.ExpressApp.Security.SelectDataSecurityProvider.OnCustomizeRequestProcessors(IDictionary`2 processors, IPermissionDictionary permissionsDictionary)
   at DevExpress.ExpressApp.Security.SelectDataSecurityProvider.CreateProcessors(IObjectSpace objectSpace)
   at DevExpress.ExpressApp.Security.SelectDataSecurityProvider.CreateSelectDataSecurity(IObjectSpace objectSpace)
   at DevExpress.ExpressApp.Security.SecurityStrategy.CreateSelectDataSecurityCore(IObjectSpace objectSpace)
   at DevExpress.ExpressApp.Security.SecurityStrategy.CreateSelectDataSecurity(IObjectSpace objectSpace)
   at DevExpress.ExpressApp.Security.ClientServer.SecuredObjectSpaceProvider.GetSecuredObjectLayer(UnitOfWork unitOfWork)
   at DevExpress.ExpressApp.Security.ClientServer.SecuredObjectSpaceProvider.CreateUnitOfWork(IDataLayer dataLayer)
   at DevExpress.ExpressApp.Xpo.XPObjectSpaceProvider.<CreateObjectSpaceCore>b__3()
   at DevExpress.ExpressApp.Xpo.XPObjectSpace..ctor(ITypesInfo typesInfo, XpoTypeInfoSource xpoTypeInfoSource, CreateUnitOfWorkHandler createUnitOfWorkDelegate)
   at DevExpress.ExpressApp.Xpo.XPObjectSpaceProvider.CreateObjectSpaceCore()
   at DevExpress.ExpressApp.Xpo.XPObjectSpaceProvider.CreateObjectSpace()
   at DevExpress.ExpressApp.Xpo.XPObjectSpaceProvider.DevExpress.ExpressApp.IObjectSpaceProvider.CreateObjectSpace()
   at DevExpress.ExpressApp.XafApplication.CreateObjectSpaceCore(Type objectType)
   at DevExpress.ExpressApp.XafApplication.CreateObjectSpace(Type objectType)
   at DevExpress.ExpressApp.ReportsV2.ReportObjectSpaceProvider.GetObjectSpace(Type objectType)
   at DevExpress.ExpressApp.ReportsV2.ReportObjectSpaceProvider.DevExpress.Persistent.Base.ReportsV2.IReportObjectSpaceProvider.GetObjectSpace(Type type)
   at DevExpress.Persistent.Base.ReportsV2.DataSourceBase.CreateObjectSpace(Type dataType, IServiceProvider serviceProvider)
   at DevExpress.Persistent.Base.ReportsV2.DataSourceBase.DevExpress.Data.IListAdapterAsync.BeginFillList(IServiceProvider servProvider, CancellationToken token)
   at DevExpress.XtraReports.Native.ListAdapterFiller.FillAsynch(IListAdapterAsync asyncAdapter, IBackgroundService backgroundService, CancellationToken token)
   at DevExpress.XtraReports.Native.ListAdapterFiller.ExecuteCore()
   at DevExpress.XtraReports.Native.DataSourceFiller.Execute()
					InnerException is null

**Comment by apobekiaris** [comment]
Since the `SecuritySystem.CurrentUser` used from Security is stored in the `HttpSessionState`, it is not available when opening an XtraReport instance in the HTML5 ReportViewer, because the latter creates the document in the background thread.
 
If this behavior causes issues, it is possible to create the document in advance using the solution provided here: https://www.devexpress.com/Support/Center/Question/Details/T395067
 
I will refactor the related methods to avoid throwing in this case.

**Comment by isatahiri** [comment]
Hello,

Thanks for the info for investigation. It is clear now. I'll apply the solution provided by devexpress temporary. 

BR
ISA

**Comment by isatahiri** [comment]
Hello,

You said that you will refactor the related methods to avoid throwing in this case.
Will you give us a patch for this ? 

BR
ISA

**Comment by apobekiaris** [comment]
do u use nuget? the nightly feed has the change

https://xpandnugetserver.azurewebsites.net see also https://www.benday.com/2017/05/03/walkthrough-use-a-package-from-a-private-nuget-server-in-tfs2017/

p.s.: i am still working on the azure nightly installer feed but it won't take much long.

**Comment by apobekiaris** [comment]
here a link to the new nightly installer feed

https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=125&view=results

**Comment by isatahiri** [comment]
Hello,

I confirm that is working now. And sorry i do not use nuget. 

BR
ISA
