### ISSUE TITLE
Report with Parameters

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#193]
Upgraded to 18.1 from 16.2 and when I run a report in the web that has parameters, I get a null reference error in.

at Xpand.Persistent.Base.ModelAdapter.ModelSynchronizer`2.GetModelValueInfos(IModelNode modelNode) in D:\Github\Fuzion\Xpand-Source\Xpand\Xpand.Persistent\Xpand.Persistent.Base\ModelAdapter\Synchronizers.cs:line 153
   at Xpand.Persistent.Base.ModelAdapter.ModelSynchronizer`2.ApplyValues(ModelNode node, Object component, PropertyDescriptorCollection properties) in D:\Github\Fuzion\Xpand-Source\Xpand\Xpand.Persistent\Xpand.Persistent.Base\ModelAdapter\Synchronizers.cs:line 95
   at Xpand.Persistent.Base.ModelAdapter.ModelSynchronizer`2.ApplyModel(IModelNode node, Object component, Action`3 action) in D:\Github\Fuzion\Xpand-Source\Xpand\Xpand.Persistent\Xpand.Persistent.Base\ModelAdapter\Synchronizers.cs:line 79
   at Xpand.Persistent.Base.ModelAdapter.ObjectModelSynchronizer.ApplyModel(Action`3 action) in D:\Github\Fuzion\Xpand-Source\Xpand\Xpand.Persistent\Xpand.Persistent.Base\ModelAdapter\Synchronizers.cs:line 32
   at DevExpress.ExpressApp.Model.ModelSynchronizer.ApplyModel()

**Comment by apobekiaris** [comment]
I cannot suggest anything without more info, since you only know your configuration do you think you can sample us?

**Comment by apobekiaris** [comment]
Probably you relate to the #183

**Comment by capricciobob** [comment]
I created a sample project. It will create some dummy DomainObjects1s. There is an repx file in there. If you load that report, it has a parameter for Date >= ??

Run the report in the web and it will fire the error for you.

[ReportParametersException.zip](https://github.com/eXpandFramework/eXpand/files/2444506/ReportParametersException.zip)

**Comment by capricciobob** [comment]
By the way, I use Reports V1, not V2.

**Comment by capricciobob** [comment]
I changed my sample project and this error does not occur with ReportsV2.

**Comment by apobekiaris** [comment]
to make it work in ReportsV1 you can simply disable the `BAD` controller. So In your can I would use this.

```cs
    public class Global : System.Web.HttpApplication {
        public Global() {
            InitializeComponent();
        }
        protected void Application_Start(Object sender, EventArgs e) {
            XpandModuleBase.DisableControllers(typeof(ASPxDateEditModelAdapter));
```

**Comment by capricciobob** [comment]
That works for now and gets me past my issue, thanks!
