### ISSUE TITLE
WorkflowServer Implementation Question

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#200]
Trying to find an example of what needs to be done to add the Xpand Workflow to the Workflow Server Application project. The old forum didn't have anything either.

Thanks!

**Comment by apobekiaris** [comment]
I think you are looking for #128

**Comment by capricciobob** [comment]
Exactly what I needed, thanks!

**Comment by capricciobob** [comment]
The server is running great. I do not have the action for Show Running Instances so I cannot tell what is going on in the backend. Does that action work for Xpand Workflow types?

**Comment by apobekiaris** [comment]
can you provide diagnostic info about the DevExpress.ExpressApp.Workflow.Visualization.RunningInstanceController? Why it is disabled?

**Comment by capricciobob** [comment]
I had a controller blocking the actions. All is solved! Thanks again.

**Comment by capricciobob** [comment]
The Running WOrkflow INstances list view now shows. When I open a detail view for a XAF workflow it shows fine. When I try to open a detail view for the Xpand.ObjectChangedWorkflow, I get an error.

Object reference not set to an instance of an object.

   at DevExpress.ExpressApp.Workflow.Visualization.TrackingVisualizationController.OnDeactivated()
   at DevExpress.ExpressApp.Controller.activeList_ResultValueChanged(Object sender, BoolValueChangedEventArgs e)
   at DevExpress.ExpressApp.Utils.BoolList.OnResultValueChanged(Boolean oldResultValue, Boolean resultValue)
   at DevExpress.ExpressApp.Utils.BoolList.EndUpdate()
   at DevExpress.ExpressApp.Utils.BoolList.set_Item(String key, Boolean value)
   at DevExpress.ExpressApp.Frame.<>c__DisplayClass4.<Dispose>b__1()
   at DevExpress.Persistent.Base.SafeExecutor.Execute(Method method, Object targetObject, String targetObjectIdentifier)
   at DevExpress.ExpressApp.Frame.Dispose()
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.CreateWindow(ShowViewParameters parameters, ShowViewSource showViewSource, Boolean isMain)
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.CreateInspectorWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.CreateInspectorWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewInInspector(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.ShowViewInNewWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewFromCommonView(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.ShowViewStrategyBase.ShowViewCore(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewCore(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.ShowViewStrategyBase.ShowView(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Frame.ProcessActionCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Win.WinWindow.ProcessActionCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Frame.ShowViewAction_ProcessCreatedView(Object sender, ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.OnProcessCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**Comment by apobekiaris** [comment]
can you post a sample? this last stack does not contain Xpand assemblies

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
