### ISSUE TITLE
ModifyViewVariant Clone throughs error when saving

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#205]
Unable to cast object of type 'EarthCape.Module.Core.Unit' to type 'Xpand.ExpressApp.ViewVariants.ViewVariant'.

   at Xpand.ExpressApp.ViewVariants.ModifyVariantsController.SynchronizeModel(Frame frame, String viewId)
   at Xpand.ExpressApp.ViewVariants.ModifyVariantsController.CloneView(String id, String viewCaption)
   at Xpand.ExpressApp.ViewVariants.ModifyVariantsController.CreateVariantNode(String variantCaption, String viewCaption, IModelVariants modelVariants)
   at Xpand.ExpressApp.ViewVariants.ModifyVariantsController.CreateViewVariantCore(Frame frame)
   at Xpand.ExpressApp.ViewVariants.ModifyVariantsController.<>c__DisplayClass19_0.<ShowViewVariantView>b__0(Object o, DialogControllerAcceptingEventArgs args)
   at DevExpress.ExpressApp.SystemModule.DialogController.Accept(SimpleActionExecuteEventArgs args)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**Comment by apobekiaris** [comment]
the stack is not enough to understand whats going on, you can always disable the related controller

```cs
XpandModuleBase.DisableControllers(typeof(ModifyVariantsController));
```cs

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
