### ISSUE TITLE
Web: Nested listviews dont open detail views

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#223]
Can you tell anything by the stack?

The error occurred:

	Type:       NullReferenceException
	Message:    Object reference not set to an instance of an object.
	Data:       0 entries
	Stack trace:

   at Xpand.Persistent.Base.General.Web.CustomizeASPxPopupController.XafPopupWindowControl_CustomizePopupWindowSize(Object sender, CustomizePopupWindowSizeEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at DevExpress.ExpressApp.Web.Controls.XafPopupWindowControl.OnCustomizePopupWindowSize(CustomizePopupWindowSizeEventArgs args)
   at DevExpress.ExpressApp.Web.Controls.XafPopupWindowControl.popupSettingsHelper_CustomizePopupWindowSize(Object sender, CustomizePopupWindowSizeEventArgs e)
   at DevExpress.ExpressApp.Web.Controls.ASPxPopupControlSettingsHelperBase.OnCustomizePopupWindowSize(CustomizePopupWindowSizeEventArgs args)
   at DevExpress.ExpressApp.Web.Controls.ASPxPopupControlSettingsHelper.CalckPopupWindowParam(Unit&amp; width, Unit&amp; height, Boolean&amp; canManageSize, PopupTemplateType&amp; popupTemplateType)
   at DevExpress.ExpressApp.Web.Controls.ASPxPopupControlSettingsHelper.SetupPopupControl(ASPxPopupControl popupControl, Page page)
   at DevExpress.ExpressApp.Web.Controls.XafPopupWindowControl.CreatePopupControl(String url, Boolean isSizeable, ShowPopupMode showPopupMode, String closeScript, Frame sourceFrame, Frame targetFrame, ShowViewSource showViewSource, ClientServerInfo clientServerInfo)
   at DevExpress.ExpressApp.Web.Controls.XafPopupWindowControl.CreatePopupControlMarkup(String url, Boolean isSizeable, Boolean showInFindPopup, String closeScript, ClientServerInfo clientServerInfo, Frame sourceFrame, Frame targetFrame, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Web.PopupWindowManager.PreparePopupWindowControl(String url, Boolean isSizeable, Boolean showInFindPopup, String closeScript, Frame sourceFrame, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Web.PopupWindowManager.ShowPopup(WebWindow windowToShow, WebWindow currentRequestWindow, Boolean showInFindPopup, String closeScript, ShowViewSource showViewSource, Boolean useFindTemplate)
   at DevExpress.ExpressApp.Web.ShowViewStrategy.RegisterStartupWindowOpeningScript(ShowViewParameters parameters, Window window, WebWindow currentWindow, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Web.ShowViewStrategy.ShowDialog(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Web.ShowViewStrategy.ShowViewFromNestedView(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.ShowViewStrategyBase.ShowViewCore(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.ShowViewStrategyBase.ShowView(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Frame.ProcessActionCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Frame.ShowViewAction_ProcessCreatedView(Object sender, ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.OnProcessCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	InnerException is null

**Comment by apobekiaris** [comment]
let me know if this controller fixes this problem, add it to your web module

```cs
    public class MyClass:CustomizeASPxPopupController {
        protected override void OnFrameAssigned(){
//            base.OnFrameAssigned();
            var popupWindowControl = ((BaseXafPage)WebWindow.CurrentRequestPage).XafPopupWindowControl;
            popupWindowControl.CustomizePopupWindowSize += XafPopupWindowControl_CustomizePopupWindowSize;
            popupWindowControl.CustomizePopupControl += PopupWindowControlOnCustomizePopupControl;
            Frame.Disposing+=FrameOnDisposing;        }

        private void FrameOnDisposing(object sender, EventArgs eventArgs){
            ((Frame) sender).Disposing-=FrameOnDisposing;
        }

        private void PopupWindowControlOnCustomizePopupControl(object sender, CustomizePopupControlEventArgs e){
            var popupWindowControl = ((XafPopupWindowControl)sender);
            popupWindowControl.CustomizePopupControl -= PopupWindowControlOnCustomizePopupControl;
            new ObjectModelSynchronizer(e.PopupControl, ((IModelViewPopup) View.Model).PopupControl).ApplyModel();
        }

        private void XafPopupWindowControl_CustomizePopupWindowSize(object sender, CustomizePopupWindowSizeEventArgs e) {
            var popupWindowControl = ((XafPopupWindowControl) sender);
            popupWindowControl.CustomizePopupWindowSize -= XafPopupWindowControl_CustomizePopupWindowSize;
            if (View != null){
                var popupControl = ((IModelViewPopup)View.Model).PopupControl;
                var height = popupControl.GetValue<Unit>("Height");
                var width = popupControl.GetValue<Unit>("Width");
                if (!height.IsEmpty && !width.IsEmpty){
                    e.Size = new Size((int) height.Value, (int) width.Value);
                    e.Handled = true;
                }
                if (popupControl.ShowPopupMode.HasValue)
                    e.ShowPopupMode=popupControl.ShowPopupMode.Value;
                if (popupControl.PopupTemplateType.HasValue)
                    e.PopupTemplateType=popupControl.PopupTemplateType.Value;
                if (!e.Handled && popupControl.ShowPopupMode.HasValue || popupControl.ShowPopupMode.HasValue) {
                    e.Handled = true;
                }
            }
        }



    }
```

**Comment by emeyke** [comment]
This fixes it.
