### ISSUE TITLE
ExcelImporter and runtime members

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#226]
When creating new ExcelImport objects with latest nightly

		InnerException:

					Type:       TypeInitializationException
					Message:    The type initializer for &#39;Xpand.Persistent.Base.AllTypesLocalizedClassInfoTypeConverter&#39; threw an exception.
					Data:       0 entries
					Stack trace:

   at Create_AllTypesLocalizedClassInfoTypeConverter()
   at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
					----------------
					InnerException:

							Type:       ReflectionTypeLoadException
							Message:    Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
							Data:       0 entries
							LoaderExceptions:       517 entries
									&#39;0&#39;		&#39;Could not load file or assembly &#39;System.Collections.Immutable, Version=1.1.37.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#39; or one of its dependencies. The system cannot find the file specified.&#39;
							Stack trace:

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Xpand.Persistent.Base.AllTypesLocalizedClassInfoTypeConverter.&lt;&gt;c.&lt;.cctor&gt;b__1_0(Assembly assembly) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\TypeConverters.cs:line 15
   at System.Linq.Enumerable.&lt;SelectManyIterator&gt;d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Xpand.Persistent.Base.AllTypesLocalizedClassInfoTypeConverter..cctor() in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\TypeConverters.cs:line 15
							InnerException is null

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.18](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=220&view=results) includes commit [Ignore errors of AllTypesLocalizedClassInfoTypeConverter #226](https://github.com/eXpandFramework/lab/commit/34fcb98c9f63075e5d136d0e9667b2d5e3afda97) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.21](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=223&view=results) includes commit [Ignore errors of AllTypesLocalizedClassInfoTypeConverter #226](https://github.com/eXpandFramework/lab/commit/03562112fea76cb84e1612a9c8aae47a64cddce1) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS
