### ISSUE TITLE
ExcelImporter fails on web

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#227]
18.1.603.18
When hitting Import

================================================================================
The error occurred:

	Type:       NullReferenceException
	Message:    Object reference not set to an instance of an object.
	Data:       0 entries
	Stack trace:

   at Xpand.ExpressApp.Web.Editors.ProgressViewItem.Start() in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Web\Editors\ProgressViewItem.cs:line 43
   at Xpand.ExpressApp.ExcelImporter.Controllers.ExcelImportDetailViewController.ImportActionOnExecute(Object sender, SimpleActionExecuteEventArgs e) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ExcelImporter\Controllers\ExcelImportDetailViewController.cs:line 0
   at DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	InnerException is null

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.20](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=222&view=results) includes commit [Option to configure persistent types creation #204 #227](https://github.com/eXpandFramework/lab/commit/61de01fbf0fc737d2481fa6fea4f9afa1f3b0c7a) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Installer lab build [18.1.603.21](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=223&view=results) includes commit [ExcelImporter: Option to configure persistent types creation #204 #212 #227](https://github.com/eXpandFramework/lab/commit/361084afa579cb44cc7245d1d1d91dd4c7ecb2d0) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
