### ISSUE TITLE
DX Dashboards failing after Xpand dashboards added (by ExcelImporter)

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#228]
Exception occurs while assigning the 'XpandDetailView, ID:DashboardViewer_DetailView' view to XpandWebWindow: 
Unable to cast object of type 'DevExpress.Persistent.BaseImpl.DashboardData' to type 'Xpand.ExpressApp.Dashboard.BusinessObjects.IDashboardDefinition'.

**Comment by apobekiaris** [comment]
Can you elab a bit I do not see how to repro

**Comment by apobekiaris** [comment]
I guess you used both native and Xpand Dashboards modules? see #239

**Comment by emeyke** [comment]
I am getting, e.g. this when creating new dx dashboard:

Object reference not set to an instance of an object.

   at Xpand.ExpressApp.Dashboard.Services.XpandDashboardDataProvider.CreateServiceCore(IDashboardData dashboardData) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\Dashboard\Services\XpandDashboardDataProvider.cs:line 13
   at DevExpress.ExpressApp.Dashboards.DashboardDataProvider.AttachService(IServiceContainer serviceContainer, IDashboardData dashboardData)
   at DevExpress.ExpressApp.Dashboards.Win.DashboardDesignerManager.AttachService(IServiceContainer serviceContainer, IDashboardData dashboardData)
   at DevExpress.ExpressApp.Dashboards.Win.DashboardDesignerManager.InitDashboardDesigner(DashboardDesigner dashboardDesigner)
   at DevExpress.ExpressApp.Dashboards.Win.DashboardDesignerManager.ShowDesignerCore(IDashboardData dashboardData)
   at DevExpress.ExpressApp.Dashboards.Win.WinNewDashboardController.CreateNewDashboard(ObjectCreatingEventArgs e)
   at DevExpress.ExpressApp.Dashboards.Win.WinNewDashboardController.ProcessObjectCreating(ObjectCreatingEventArgs e)
   at DevExpress.ExpressApp.Dashboards.NewDashboardController.NewObjectController_ObjectCreating(Object sender, ObjectCreatingEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at DevExpress.ExpressApp.SystemModule.NewObjectViewController.OnObjectCreating(CollectionSourceBase currentCollectionSource, ObjectCreatingEventArgs queryNewObjectArgs)
   at DevExpress.ExpressApp.SystemModule.NewObjectViewController.CreateNewObject(Type newObjectType, IObjectSpace objectSpaceForNewObject, SingleChoiceActionExecuteEventArgs args)
   at DevExpress.ExpressApp.Win.SystemModule.WinNewObjectViewController.New(SingleChoiceActionExecuteEventArgs args)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**Comment by emeyke** [comment]
I don't. :)
but xpand dashboards are used by excel importer.

**Comment by emeyke** [comment]
Now when creating new excelimport on win:

Index was outside the bounds of the array.

   at Xpand.Persistent.Base.AllTypesLocalizedClassInfoTypeConverter.GetTypeName(Type type) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\TypeConverters.cs:line 64
   at System.ComponentModel.TypeConverter.ConvertToString(Object value)
   at DevExpress.ExpressApp.Win.Editors.TypePropertyEditor.SetupRepositoryItem(RepositoryItem item)
   at DevExpress.ExpressApp.Win.Editors.DXPropertyEditor.DevExpress.ExpressApp.Win.Editors.IInplaceEditSupport.CreateRepositoryItem()
   at DevExpress.ExpressApp.Win.Editors.RepositoryEditorsFactory.CreateRepositoryItem(Boolean needProtectedContent, IModelMemberViewItem memberViewItem, Type objectType)
   at DevExpress.ExpressApp.Win.Editors.RepositoryItemCreator.CreateItem(IGridColumnModelSynchronizer xafGridColumnInfo)
   at DevExpress.ExpressApp.Win.Editors.GridViewColumnFactory.TryCreateRepositoryItem(IGridColumnModelSynchronizer gridColumnInfo, IRepositoryItemCreator repositoryItemCreator)
   at DevExpress.ExpressApp.Win.Editors.GridViewColumnFactory.CreateColumnRepositoryItem(GridColumn column, IGridColumnModelSynchronizer gridColumnInfo, ColumnView columnView, IRepositoryItemCreator repositoryItemCreator, IGridViewOptions editorOptions)
   at DevExpress.ExpressApp.Win.Editors.GridViewColumnFactory.SetupColumn(GridColumn column, IGridColumnModelSynchronizer gridColumnInfo, ColumnView columnView, IRepositoryItemCreator repositoryItemCreator, IGridViewOptions editorOptions)
   at DevExpress.ExpressApp.Win.Editors.GridViewColumnFactory.AddColumn(IModelColumn columnInfo, ColumnView columnView, IRepositoryItemCreator repositoryItemCreator, IGridViewOptions editorOptions, IModelSynchronizersHolder modelSynchronizersHolder)
   at DevExpress.ExpressApp.Win.Editors.GridViewColumnFactory.PopulateColumns(ModelLayoutElementCollection layoutElementCollection, ColumnView columnView, IRepositoryItemCreator repositoryItemCreator, IGridViewOptions editorOptions, IModelSynchronizersHolder modelSynchronizersHolder)
   at DevExpress.ExpressApp.Win.Editors.WinColumnsListEditor.PopulateColumns()
   at DevExpress.ExpressApp.Win.Editors.GridListEditor.ApplyModel()
   at DevExpress.ExpressApp.Win.Editors.WinColumnsListEditor.CreateControlsCore()
   at DevExpress.ExpressApp.Editors.ListEditor.CreateControls()
   at DevExpress.ExpressApp.Editors.ViewItem.CreateControl()
   at DevExpress.ExpressApp.CompositeView.CreateViewItemControls()
   at DevExpress.ExpressApp.CompositeView.CreateControlsCore()
   at DevExpress.ExpressApp.View.CreateControls()
   at DevExpress.ExpressApp.Win.Templates.ViewSiteManager.EnsureViewControl()
   at DevExpress.ExpressApp.Win.Templates.ViewSiteManager.FillViewSite()
   at DevExpress.ExpressApp.Win.Templates.ViewSiteManager.viewSiteControl_HandleCreated(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at DevExpress.XtraEditors.XtraScrollableControl.OnHandleCreated(EventArgs e)
   at DevExpress.XtraEditors.PanelControl.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraScrollableControl.WndProc(Message& m)
   at DevExpress.Utils.Controls.PanelBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
