### ISSUE TITLE
Runtime member creation failed

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#243]
Could not replicate this in tester solution but please have a look at log if there is any hint where to look.
Creating new Persisitent member through expand model editor runtime.
When app is restarted, it fails to run giving error message below.

Exception thrown: 'System.AggregateException' in Xpand.Persistent.Base.dll
06.11.18 19:47:21.079	--------------------------------------------------------------------------------
							Logon failed

06.11.18 19:47:21.080	Runtime members creation failed
06.11.18 19:47:21.082		CurrentObject: Xpand.ExpressApp.Security.AuthenticationProviders.XpandLogonParameters
Exception thrown: 'System.AggregateException' in DevExpress.ExpressApp.v18.2.dll
The thread 0x4e84 has exited with code 0 (0x0).
EarthCape.Win.exe Error: 0 : 06.11.18 19:47:21.132	================================================================================
The error occurred:

	Type:       AggregateException
	Message:    Runtime members creation failed
	Data:       0 entries
	Stack trace:

   at Xpand.Persistent.Base.RuntimeMembers.RuntimeMemberBuilder.CreateRuntimeMembers(IModelApplication model) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\RuntimeMembers\RuntimeMemberBuilder.cs:line 65
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at DevExpress.ExpressApp.XafApplication.LoadUserDifferences()
   at DevExpress.ExpressApp.XafApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
   at DevExpress.ExpressApp.Win.WinApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
	----------------
	InnerException:

			Type:       Exception
			Message:    Failed to create test3 on EarthCape.Module.Core.PersonCore
			Data:       0 entries
			Stack trace:

			----------------
			InnerException:

					Type:       NullReferenceException
					Message:    Object reference not set to an instance of an object.
					Data:       0 entries
					Stack trace:

   at Xpand.Persistent.Base.RuntimeMembers.RuntimeMemberBuilder.CreateXpandCustomMemberInfo(IModelMemberEx modelMemberEx, XPObjectSpace objectSpace) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\RuntimeMembers\RuntimeMemberBuilder.cs:line 111
   at Xpand.Persistent.Base.RuntimeMembers.RuntimeMemberBuilder.CreateRuntimeMembers(IModelApplication model) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\RuntimeMembers\RuntimeMemberBuilder.cs:line 49
					InnerException is null

**Comment by emeyke** [comment]
Ok this was remedied by sticking to XpandObjectSpaceProvider. Will get back to it later.
