### ISSUE TITLE
Adding Expand to existing project

### ISSUE THREAD

**Issue by utwasim981** [eXpandFramework/eXpand#245]
I have an existing XAF 17.2.7 project and I want to add Xpand 17.2.7.2 to it, when I add Xpand as reference I got the following error.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Xpand.VSIX.Extensions.ProjectExtensions.References(Project project, String assemblyName) in C:\Release172\Xpand.Plugins\Xpand.VSIX\Extensions\ProjectExtensions.cs:line 52
   at Xpand.VSIX.Extensions.ProjectExtensions.GetPlatform(Project project) in C:\Release172\Xpand.Plugins\Xpand.VSIX\Extensions\ProjectExtensions.cs:line 56
   at Xpand.VSIX.Wizard.SolutionWizard.<>c.<GetXpandModules>b__9_0(Project project) in C:\Release172\Xpand.Plugins\Xpand.VSIX\Wizard\SolutionWizard.cs:line 46
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Xpand.VSIX.Wizard.SolutionWizard.GetXpandModules() in C:\Release172\Xpand.Plugins\Xpand.VSIX\Wizard\SolutionWizard.cs:line 45
   at Xpand.VSIX.Wizard.SolutionWizard.Show() in C:\Release172\Xpand.Plugins\Xpand.VSIX\Wizard\SolutionWizard.cs:line 103

**Comment by apobekiaris** [comment]
you are talking about a VSIX package exception disaplyed in the VS command output window right?

The VSIX package does not depend on DX suite so it is safe to always have the latest version. Can you try the latest and let me know if the error remains please?

**Comment by utwasim981** [comment]
I Tried Xpand.VSIX-18.2.201.0 and it't the same. the issue also if I add the module manually it's not building the project

**Comment by apobekiaris** [comment]
Installer lab build [18.2.201.10](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=253&view=results) includes commit [VSIX swallow exception for invalid projects #245](https://github.com/eXpandFramework/lab/commit/5e424603bb23dc3f6f432c7ea1f440cea4de656a) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by utwasim981** [comment]
for this project I manage to add it manually through the module designer, for any new project is working fine. thanks for your support
