### ISSUE TITLE
ExcelImporter: file open issue

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#255]
Getting this when just creating nre import record and opening this file on win:
https://www.dropbox.com/s/ntjh54w8uqz5r8j/Book2.xlsx?dl=0 (example, but seems to be the same with any other file)

Buffer cannot be null.
Parameter name: buffer

   at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   at System.IO.MemoryStream..ctor(Byte[] buffer)
   at Xpand.ExpressApp.ExcelImporter.BusinessObjects.ExcelImport.GetXlsContent(String fileName, Byte[] bytes) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ExcelImporter\BusinessObjects\ExcelImport.cs:line 151
   at Xpand.ExpressApp.ExcelImporter.Win.Controllers.ExcelImportDetailViewController.ParseStream() in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ExcelImporter.Win\Controllers\ExcelImportDetailViewController.cs:line 74
   at Xpand.ExpressApp.ExcelImporter.Win.Controllers.ExcelImportDetailViewController.FileOnPropertyChanged(Object sender, PropertyChangedEventArgs e) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ExcelImporter.Win\Controllers\ExcelImportDetailViewController.cs:line 68
   at Xpand.Persistent.Base.XpandFileData.OnPropertyChanged(String propertyName)
   at Xpand.Persistent.Base.XpandFileData.set_FullName(String value)
   at DevExpress.Persistent.Base.FileDataHelper.LoadFromStream(IFileData fileData, String fileName, Stream stream, String fullName)
   at DevExpress.ExpressApp.FileAttachments.Win.FileDataEdit.FileSelected(String fileName)
   at DevExpress.ExpressApp.FileAttachments.Win.FileDataEdit.ShowFileOpenDialog()
   at DevExpress.ExpressApp.FileAttachments.Win.FileDataEdit.OnClickButton(EditorButtonObjectInfoArgs buttonInfo)
   at DevExpress.XtraEditors.ButtonEdit.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at DevExpress.XtraEditors.TextEdit.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by emeyke** [comment]
on the same tester project
https://www.dropbox.com/s/mh3hwyzf5f3w4uf/XpandTester%20%282%29.zip?dl=0

**Comment by apobekiaris** [comment]
I can import it fine.

Your stack trace reminds me a bad version a while ago, makes sure you are on the latest.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
