### ISSUE TITLE
Exception occurs while the 'Xpand.ExpressApp.Security.XpandSecurityModule' customizes TypesInfo: Sequence contains no matching element

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#257]
Hello Tolis,

Since today i have the following error. 
I haven't changed anything related to the security. 
I just created an new class. Do you have any idea because i have no idea where to look. 

I happens only on the win client on the start. 

![image](https://user-images.githubusercontent.com/41955268/48945117-7a56b300-ef29-11e8-9dfc-dce57f896892.png)

Type:       InvalidOperationException
	Message:    Exception occurs while the 'Xpand.ExpressApp.Security.XpandSecurityModule' customizes TypesInfo: Sequence contains no matching element
	Data:       0 entries
	Stack trace:

   at DevExpress.ExpressApp.ApplicationModulesManager.DoCustomizeTypesInfo(ITypesInfo typesInfo)
   at DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   at DevExpress.ExpressApp.XafApplication.Setup(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   at DevExpress.ExpressApp.XafApplication.Setup()
   at KBA_ADDON.Win.Program.Main() in C:\KBA-NotaSys\Devs\PROD\KBA_ADDON\KBA_ADDON.Win\Program.cs:line 75
	----------------
	InnerException:

			Type:       InvalidOperationException
			Message:    Sequence contains no matching element
			Data:       0 entries
			Stack trace:

   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Xpand.Persistent.Base.General.XpandModuleBase.AssignSecurityEntities()
   at Xpand.Persistent.Base.General.XpandModuleBase.CustomizeTypesInfo(ITypesInfo typesInfo)
   at Xpand.ExpressApp.Security.XpandSecurityModule.CustomizeTypesInfo(ITypesInfo typesInfo)
   at DevExpress.ExpressApp.ApplicationModulesManager.DoCustomizeTypesInfo(ITypesInfo typesInfo)
			InnerException is null

**Comment by isatahiri** [comment]
I use the version : 18.2.301.8

**Comment by isatahiri** [comment]
Sorry ! Case solved. Is seems that my model is correpted somehow. 
The UserType and RoleType were empty in the WinApplication. 

BR
ISA
