### ISSUE TITLE
question

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#266]
Hi tolis,
I just trying to login in Devexpress 18.2.3 version with my old database. and i got this exception;

Duplicate mapping to column 'OptimisticLockField' in class 'Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentAttributeInfos.PersistentVisibleInDetailViewAttribute'.

   at DevExpress.Xpo.Metadata.XPClassInfo.CheckMembers()
   at DevExpress.Xpo.Metadata.ReflectionClassInfo..ctor(Type classType, XPDictionary dictionary)
   at DevExpress.Xpo.Metadata.ReflectionDictionary.CreateClassInfo(Type classType)
   at DevExpress.Xpo.Metadata.ReflectionDictionary.ResolveClassInfoByType(Type classType)
   at DevExpress.ExpressApp.DC.Xpo.XafReflectionDictionary.ResolveClassInfoByType(Type classType)
   at DevExpress.Xpo.Metadata.ReflectionDictionary.QueryClassInfo(String assemblyName, String className)
   at DevExpress.Xpo.XPObjectType.get_TypeClassInfo()
   at DevExpress.Xpo.XPObjectType.get_IsValidType()
   at DevExpress.Xpo.Helpers.XPObjectTypesManager.FillLoadedTypes(ICollection objectTypesList)
   at DevExpress.Xpo.Helpers.XPObjectTypesManager.GetAllTypes()
   at DevExpress.Xpo.Session.GetObjectsInternal(ObjectsQuery[] queries)
   at DevExpress.Xpo.Logger.LogManager.Log[T](String category, LogHandler`1 handler, MessageHandler`1 createMessageHandler)
   at DevExpress.Xpo.Session.GetObjects(ObjectsQuery query)
   at DevExpress.Xpo.XPBaseCollection.Load()
   at DevExpress.Xpo.XPBaseCollection.get_Objects()
   at DevExpress.Xpo.XPBaseCollection.System.Collections.IEnumerable.GetEnumerator()
   at DevExpress.ExpressApp.Updating.DatabaseUpdater.LoadVersionInfoList(IObjectSpace objectSpace, CompatibilityError& compatibilityError)
   at DevExpress.ExpressApp.Updating.DatabaseUpdater.CheckCompatibilityCore(Boolean getFirstVersionError)

**Comment by apobekiaris** [comment]
whats your Xpand version?

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
