### ISSUE TITLE
Modeldifference: problem opening web model xml

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#276]
Getting this when switching to XML tab of the web model with latest nightly.

Unable to cast object of type 'EarthCape.Web.EarthCapeAspNetApplication' to type 'DevExpress.ExpressApp.Win.WinApplication'.

   at Xpand.Persistent.Base.General.Win.ToolbarExtensions.Execute(Control control, Action`1 action) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\Win\ToolbarExtensions.cs:line 27
   at Xpand.ExpressApp.Win.PropertyEditors.RichEdit.RichEditContainerRibbon.DestroyToolBar() in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\PropertyEditors\RichEdit\RichEditContainerRibbon.cs:line 49
   at Xpand.ExpressApp.Win.PropertyEditors.RichEdit.RichEditToolbarController.DestroyAllToolBars() in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\PropertyEditors\RichEdit\RichEditToolbarController.cs:line 50
   at Xpand.ExpressApp.Win.PropertyEditors.RichEdit.RichEditToolbarController.RichEditControl_GotFocus(Object sender, EventArgs e) in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\PropertyEditors\RichEdit\RichEditToolbarController.cs:line 39
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnGotFocus(EventArgs e)
   at DevExpress.XtraRichEdit.RichEditControl.OnGotFocus(EventArgs e)
   at System.Windows.Forms.Control.WmSetFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraRichEdit.RichEditControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by apobekiaris** [comment]
Can you sample me? I tested in ModelDifferenceTester solution with no errors
