### ISSUE TITLE
Importer: exception when adding file

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#284]
Exception occurs when adding file to new ExcelImport record:

Repro steps:
in Win client
create new ExcelImport record
add Name
add File
Exception below occurs.

For databases that already had ExcelImport records before upgrading to latest expand, exception occurs on program start.

No match for method with name OnPropertyChanged and flags Instance | NonPublic | Public | Static on type Xpand.Persistent.Base.XpandFileData.

   at Fasterflect.Emitter.LookupUtils.GetMethod(CallInfo callInfo)
   at Fasterflect.Emitter.MethodInvocationEmitter.CreateDelegate()
   at Fasterflect.Emitter.BaseEmitter.GetDelegate()
   at Fasterflect.MethodExtensions.DelegateForCallMethod(Type type, Type[] genericTypes, String name, Flags bindingFlags, Type[] parameterTypes)
   at Fasterflect.MethodExtensions.DelegateForCallMethod(Type type, String name, Type[] parameterTypes)
   at Fasterflect.MethodExtensions.CallMethod(Object obj, String name, Object[] parameters)
   at DevExpress.ExpressApp.FileAttachments.Win.FileDataEdit.FileSelected(String fileName)
   at DevExpress.ExpressApp.FileAttachments.Win.FileDataEdit.ShowFileOpenDialog()
   at DevExpress.ExpressApp.FileAttachments.Win.FileDataEdit.OnClickButton(EditorButtonObjectInfoArgs buttonInfo)
   at DevExpress.XtraEditors.ButtonEdit.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at DevExpress.XtraEditors.TextEdit.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by apobekiaris** [comment]
Installer lab build [18.2.401.01](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=502&view=results) includes commit [XpandFileData throws cause fody internal method naming changed #285 #284](https://github.com/eXpandFramework/lab/commit/190629ef4cf07ff9e7c2704cac493db4444d9388) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
