### ISSUE TITLE
Nuget packages

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#291]
Hi,

How can i install that references from nuget? 

"DevExpress.XAF.Modules.ModelViewIneritance.dll"
DevExpress.XAF.Extensions.Enum.dll
DevExpress.XAF.Extensions.Model.dll
DevExpress.XAF.Extensions.String.dll

**Comment by apobekiaris** [comment]
these are standalone nuget packages eXpandFrameowrk already uses them, else you can install in a XAF Only project as you install any other nuget package. 

p.s.: install the modules and not the extensions and not that I am still refactoring so assemblies may change in next minor

**Comment by skybluex3** [comment]
Which one package includes that assemblies? I checked eXpandAgnostic but it doesnt included

**Comment by apobekiaris** [comment]
https://www.nuget.org/packages?q=DevExpress.XAF.Modules.ModelViewIneritance

**Comment by skybluex3** [comment]
Thanks

**Comment by skybluex3** [comment]
is that package removed on 18.2.400.2 ?

**Comment by apobekiaris** [comment]
yeah there was a spelling on on the name #283 try [ModelViewInheritance](https://www.nuget.org/packages?q=DevExpress.XAF.Modules.ModelViewInheritance)

**Comment by skybluex3** [comment]
@apobekiaris  should i do something for update ? because i get this error on startup
Object reference not set to an instance of an object.

   at DevExpress.XAF.Modules.ModelViewInheritance.ModelViewInheritanceUpdater.UpdateViewModel(ValueTuple`3 info, IModelApplication application, ModelNode master) in D:\a\1\s\src\Modules\Agnostic\ModelViewInheritance\ModelViewInheritanceUpdater.cs:line 83
   at DevExpress.XAF.Modules.ModelViewInheritance.ModelViewInheritanceUpdater.<>c__DisplayClass6_0.<UpdateModel>b__1(IModelApplication application) in D:\a\1\s\src\Modules\Agnostic\ModelViewInheritance\ModelViewInheritanceUpdater.cs:line 66
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at DevExpress.XAF.Modules.ModelViewInheritance.ModelViewInheritanceUpdater.UpdateModel(ModelNode master, ValueTuple`3 info, IModelApplication[] modulesDifferences) in D:\a\1\s\src\Modules\Agnostic\ModelViewInheritance\ModelViewInheritanceUpdater.cs:line 64
   at DevExpress.XAF.Modules.ModelViewInheritance.ModelViewInheritanceUpdater.UpdateNodeCore(ModelNode node) in D:\a\1\s\src\Modules\Agnostic\ModelViewInheritance\ModelViewInheritanceUpdater.cs:line 31
   at DevExpress.ExpressApp.Model.ModelNodesGeneratorBase.RunUpdaters(ModelNode node, Boolean enableModelCache)
   at DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGenerator(ModelNodesGeneratorBase generator)
   at DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGenerator()
   at DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes(Boolean alwaysCreate)
   at DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodesCore()
   at DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodes()
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetNode(String id, Boolean inThisLayer)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetNode(String id, Boolean inThisLayer)
   at DevExpress.ExpressApp.Model.Core.ModelNodeList`1.get_Item(String id)
   at DevExpress.ExpressApp.ReportsV2.Win.ReportsWindowsFormsModuleV2.Application_SetupComplete(Object sender, EventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at DevExpress.ExpressApp.XafApplication.OnSetupComplete()
   at DevExpress.ExpressApp.Win.WinApplication.OnSetupComplete()
   at DevExpress.ExpressApp.XafApplication.Setup(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   at DevExpress.ExpressApp.XafApplication.Setup()
   at ManageMind.Win.Program.Main(String[] arg) in C:\Projects\Development\ManageMind\ManageMind.Win\Program.cs:line 135

**Comment by apobekiaris** [comment]
it looks like the latest patch has problems see how to disable in #292

**Comment by apobekiaris** [comment]
Installer lab build [18.2.401.05](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [DevExpress.XAF.Modules nugets update #291 #292](https://github.com/eXpandFramework/lab/commit/de6603ec9ae36447222f48df65720b4e02779f59) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
