### ISSUE TITLE
ModelInheritance: cant open model editor design time

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#292]
Throws this with latest build

Object reference not set to an instance of an object.

   at DevExpress.XAF.Modules.ModelViewInheritance.ModelViewInheritanceUpdater.UpdateViewModel(ValueTuple`3 info, IModelApplication application, ModelNode master) in D:\a\1\s\src\Modules\Agnostic\ModelViewInheritance\ModelViewInheritanceUpdater.cs:line 83
   at DevExpress.XAF.Modules.ModelViewInheritance.ModelViewInheritanceUpdater.<>c__DisplayClass6_0.<UpdateModel>b__1(IModelApplication application) in D:\a\1\s\src\Modules\Agnostic\ModelViewInheritance\ModelViewInheritanceUpdater.cs:line 66
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at DevExpress.XAF.Modules.ModelViewInheritance.ModelViewInheritanceUpdater.UpdateModel(ModelNode master, ValueTuple`3 info, IModelApplication[] modulesDifferences) in D:\a\1\s\src\Modules\Agnostic\ModelViewInheritance\ModelViewInheritanceUpdater.cs:line 64
   at DevExpress.XAF.Modules.ModelViewInheritance.ModelViewInheritanceUpdater.UpdateNodeCore(ModelNode node) in D:\a\1\s\src\Modules\Agnostic\ModelViewInheritance\ModelViewInheritanceUpdater.cs:line 31
   at DevExpress.XAF.Modules.ModelViewInheritance.ModelViewInheritanceUpdater.UpdateNode(ModelNode node) in D:\a\1\s\src\Modules\Agnostic\ModelViewInheritance\ModelViewInheritanceUpdater.cs:line 156
   at DevExpress.ExpressApp.Model.ModelNodesGeneratorBase.RunUpdaters(ModelNode node, Boolean enableModelCache)
   at DevExpress.ExpressApp.Model.ModelNodesGeneratorBase.GenerateNodes(ModelNode node)
   at DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGenerator(ModelNodesGeneratorBase generator)
   at DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGenerator()
   at DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes(Boolean alwaysCreate)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetNode(String id, Boolean inThisLayer)
   at DevExpress.ExpressApp.Model.Core.ModelValuePersistentPathCalculator.Calculate(ModelNode originalNode, String propertyName, Boolean runDefaultCalculator, Boolean inThisLayer)
   at DevExpress.ExpressApp.Model.Core.ModelValuePersistentPathCalculator.Calculate(ModelNode originalNode, String propertyName)
   at DevExpress.ExpressApp.Model.Core.ModelNodeInfo.DefaultValueItem.CalcValue(ModelNode node, String propertyName)
   at DevExpress.ExpressApp.Model.Core.ModelNodeInfo.GetDefaultValue(ModelNode node, String propertyName)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetDefaultValueCore(String name)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[ValueType](IModelValue`1 modelValue, String name, Int32 aspectIndex)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[T](String name, Boolean inThisLayer, Int32 aspectIndex)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[T](String name)
   at ModelClass.get_DefaultListView()
   at DevExpress.ExpressApp.SystemModule.NavigationItemNodeGenerator.GenerateNodesCore(ModelNode node)
   at DevExpress.ExpressApp.Model.ModelNodesGeneratorBase.GenerateNodes(ModelNode node)
   at DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGenerator(ModelNodesGeneratorBase generator)
   at DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGenerator()
   at DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes(Boolean alwaysCreate)
   at DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodesCore()
   at DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodes()
   at DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes(Boolean alwaysCreate)
   at DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodesCore()
   at DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodes()
   at DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes(Boolean alwaysCreate)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetNode(String id, Boolean inThisLayer)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetNode(String id, Boolean inThisLayer)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetNode(String id, Boolean inThisLayer)
   at DevExpress.ExpressApp.Model.Core.ModelNodeInfo.GetChildNodes(ModelNode modelNode)
   at DevExpress.ExpressApp.Model.ModelEditorHelper.GetChildNodes(ModelNode modelNode)
   at DevExpress.ExpressApp.Win.Core.ModelEditor.ModelInterfaceAdapter.GetChildrenCore(Object nodeObject)
   at DevExpress.ExpressApp.Win.Core.ModelEditor.ModelInterfaceAdapter.HasChildren(Object nodeObject)
   at DevExpress.ExpressApp.Win.Core.ModelEditor.ExtendModelInterfaceAdapter.HasChildren(Object nodeObject)

**Comment by emeyke** [comment]
![image](https://user-images.githubusercontent.com/234025/50894666-7664ee80-140c-11e9-95ba-025570a03a2d.png)

**Comment by apobekiaris** [comment]
Installer lab build [18.2.401.05](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=&view=results) includes commit [DevExpress.XAF.Modules nugets update #291 #292](https://github.com/eXpandFramework/lab/commit/de6603ec9ae36447222f48df65720b4e02779f59) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
