### ISSUE TITLE
object reference

### ISSUE THREAD

**Issue by skybluex3** [eXpandFramework/eXpand#297]
Hi Tolis,
I've found nullref exception on 
 Xpand.Xpo.CreateCustomMember() func 
if attributes is null then application throws. I dont have any idea that collection how did set null, but i need to pass that object reference. How can i pass?

**Comment by skybluex3** [comment]
the callstack is ;
DevExpress.Xpo.v18.2.dll!DevExpress.Xpo.Metadata.XPCustomMemberInfo.XPCustomMemberInfo(DevExpress.Xpo.Metadata.XPClassInfo owner, string propertyName, System.Type propertyType, DevExpress.Xpo.Metadata.XPClassInfo referenceType, bool nonPersistent, bool nonPublic)	Unknown
>	Xpand.Xpo.dll!Xpand.Xpo.IXPSimpleObjectExtensions.CreateCustomMember(DevExpress.Xpo.Metadata.XPClassInfo classInfo, string propertyName, System.Type propertyType, bool nonPersistent, System.Attribute[] attributes) Line 19	C#
 	Xpand.Persistent.Base.dll!Xpand.Persistent.Base.RuntimeMembers.RuntimeMemberBuilder.CreateMemberInfo(Xpand.Persistent.Base.RuntimeMembers.Model.IModelMemberEx modelMemberEx, DevExpress.Xpo.Metadata.XPClassInfo xpClassInfo) Line 188	C#
 	Xpand.Persistent.Base.dll!Xpand.Persistent.Base.RuntimeMembers.RuntimeMemberBuilder.CreateXpandCustomMemberInfo(Xpand.Persistent.Base.RuntimeMembers.Model.IModelMemberEx modelMemberEx, DevExpress.ExpressApp.Xpo.XPObjectSpace objectSpace) Line 98	C#
 	Xpand.Persistent.Base.dll!Xpand.Persistent.Base.RuntimeMembers.RuntimeMemberBuilder.CreateRuntimeMembers(DevExpress.ExpressApp.Model.IModelApplication model) Line 49	C#
 	DevExpress.ExpressApp.v18.2.dll!DevExpress.ExpressApp.XafApplication.LoadUserDifferences()	Unknown
 	DevExpress.ExpressApp.v18.2.dll!DevExpress.ExpressApp.XafApplication.Logon(DevExpress.ExpressApp.Actions.PopupWindowShowActionExecuteEventArgs logonWindowArgs)	Unknown
 	DevExpress.ExpressApp.Win.v18.2.dll!DevExpress.ExpressApp.Win.WinApplication.Logon(DevExpress.ExpressApp.Actions.PopupWindowShowActionExecuteEventArgs logonWindowArgs)	Unknown
 	DevExpress.ExpressApp.v18.2.dll!DevExpress.ExpressApp.XafApplication.showLogonAction_OnExecute(object sender, DevExpress.ExpressApp.Actions.PopupWindowShowActionExecuteEventArgs args)	Unknown
 	DevExpress.ExpressApp.v18.2.dll!DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(System.Delegate handler, DevExpress.ExpressApp.Actions.ActionBaseEventArgs eventArgs)	Unknown
 	DevExpress.ExpressApp.v18.2.dll!DevExpress.ExpressApp.Actions.PopupWindowShowAction.DoExecute(DevExpress.ExpressApp.Window window)	Unknown
 	DevExpress.ExpressApp.v18.2.dll!DevExpress.ExpressApp.Actions.PopupWindowShowAction.DialogController_Accepting(object sender, DevExpress.ExpressApp.SystemModule.DialogControllerAcceptingEventArgs e)	Unknown
 	DevExpress.ExpressApp.v18.2.dll!DevExpress.ExpressApp.SystemModule.DialogController.Accept(DevExpress.ExpressApp.Actions.SimpleActionExecuteEventArgs args)	Unknown
 	DevExpress.ExpressApp.v18.2.dll!DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(System.Delegate handler, DevExpress.ExpressApp.Actions.ActionBaseEventArgs eventArgs)	Unknown
 	DevExpress.ExpressApp.Win.v18.2.dll!DevExpress.ExpressApp.Win.Templates.ActionContainers.ButtonsContainersSimpleActionItem.ProcessClick()	Unknown

**Comment by apobekiaris** [comment]
until i research and since attributes is null how about making  it not nul;l by adding an unrelated attribute to the member?

**Comment by skybluex3** [comment]
i add every member to Caption Attribute, but idk really how it was null,
I Found this Xpand.Persistent.Base.RuntimeMembers.RuntimeMemberBuilder.SuppressException = true;
but the cs changed like that;
Object reference not set to an instance of an object.

   at DevExpress.ExpressApp.Model.DomainLogics.ModelClassLogic.FindComplexMember(IModelClass modelClass, String memberName)
   at DevExpress.ExpressApp.Model.DomainLogics.ModelClassLogic.FindMember(IModelClass modelClass, String memberName)
   at DevExpress.ExpressApp.SystemModule.ModelMemberViewItemValidator.IsValid(IModelMemberViewItem modelMemberViewItem, IModelApplication application)
   at DevExpress.ExpressApp.Model.Core.ModelNodeInfo.IsValid(ModelNode node, IModelApplication application)
   at DevExpress.ExpressApp.Model.Core.ModelNode.IsValid(IModelApplication application)
   at DevExpress.ExpressApp.Model.Core.ModelNode.ValidateUniqueLastLayerNode()
   at DevExpress.ExpressApp.Model.Core.ModelNode.ValidateUniqueLastLayerNode()
   at DevExpress.ExpressApp.Model.Core.ModelNode.ValidateUniqueLastLayerNode()
   at DevExpress.ExpressApp.Model.Core.ModelNode.ValidateMasterNodesCore(Boolean validateNotLoaded)
   at DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodesCore()
   at DevExpress.ExpressApp.Model.Core.ModelNode.CreateMasterNodes()
   at DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes()
   at DevExpress.ExpressApp.Model.Core.ModelNode.EnsureMaster(ModelMultipleMasterStoreItem masterNodeItem)
   at DevExpress.ExpressApp.Model.Core.ModelNode.get_Master()
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetMasterRecursive()
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetModelValue(String name)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[T](String name, Boolean inThisLayer, Int32 aspectIndex)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[T](String name)
   at DevExpress.ExpressApp.Editors.ViewInfo.FromView(ObjectView view)
   at DevExpress.ExpressApp.ConditionalAppearance.RefreshItemsAppearanceControllerBase`1.RefreshViewItemsAppearance()
   at DevExpress.ExpressApp.ConditionalAppearance.AppearanceController.Refresh()
   at DevExpress.ExpressApp.ConditionalAppearance.RefreshAppearanceController.RefreshAppearance()
   at DevExpress.ExpressApp.ConditionalAppearance.RefreshAppearanceController.RefreshAppearance(Object obj)
   at DevExpress.ExpressApp.ConditionalAppearance.RefreshAppearanceController.ObjectSpace_ObjectChanged(Object sender, ObjectChangedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at DevExpress.ExpressApp.BaseObjectSpace.OnObjectChanged(ObjectChangedEventArgs args)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at DevExpress.ExpressApp.Security.AuthenticationStandardLogonParameters.RaisePropertyChanged(String propertyName)
   at DevExpress.ExpressApp.Security.AuthenticationStandard.ClearSecuredLogonParameters()
   at DevExpress.ExpressApp.XafApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
   at DevExpress.ExpressApp.Win.WinApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)

**Comment by apobekiaris** [comment]
From what I see Xpand.Xpo.CreateCustomMember has attributes as params and they never used from any calls. So I am not sure whats is happening there.

I am sorry I cannot tell much without a repro, please post a sample

**Comment by skybluex3** [comment]
Oh , i found . It's my fault, one class declared twice.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
