### ISSUE TITLE
ExcelImport ThreadSafeDataLayer issue

### ISSUE THREAD

**Issue by brond3** [eXpandFramework/eXpand#337]
I currently get a ThreadSafeDataLayer error after the import and I click on the save button when using the ExcelImport module.  I have reviewed the test application to see what was done to it (it works with no issue) to see how it was done but could not see anything that was done to make it ThreadSafe.  If anyone could point me in the correct direction it would be greatly appreciated. 

Below is the full error that shows up. 

Reentrancy or cross thread operation detected. Use ThreadSafeDataLayer or find the cause of the cross thread access to the SimpleDataLayer instance from your code. To suppress this exception, set DevExpress.Xpo.SimpleDataLayer.SuppressReentrancyAndThreadSafetyCheck = true

   at DevExpress.Xpo.SimpleDataLayer.ReentrancyAndThreadSafetyChecked[T](Func`1 action)
   at DevExpress.Xpo.SimpleDataLayer.ModifyData(ModificationStatement[] dmlStatements)
   at DevExpress.Xpo.SimpleObjectLayer.CommitChanges(Session session, ICollection fullListForDelete, ICollection completeListForSave)
   at DevExpress.Xpo.Session.FlushChangesInsideTransaction()
   at DevExpress.Xpo.Session.FlushChanges()
   at DevExpress.Xpo.SessionObjectLayer.CommitChanges(Session session, ICollection fullListForDelete, ICollection completeListForSave)
   at DevExpress.Xpo.Session.FlushChangesInsideTransaction()
   at DevExpress.Xpo.Session.FlushChanges()
   at DevExpress.Xpo.Session.<CommitTransaction>b__312_0()
   at DevExpress.Xpo.Logger.LogManager.Log(String category, LogHandlerVoid handler, MessageHandler`1 createMessageHandler, ExceptionHandler exceptionHandler)
   at DevExpress.Xpo.Session.CommitTransaction()
   at DevExpress.Xpo.UnitOfWork.CommitChanges()
   at DevExpress.ExpressApp.Xpo.XPObjectSpace.DoCommit()
   at DevExpress.ExpressApp.BaseObjectSpace.CommitChanges()
   at DevExpress.ExpressApp.Win.SystemModule.WinModificationsController.Save(SimpleActionExecuteEventArgs args)
   at DevExpress.ExpressApp.SystemModule.ModificationsController.saveAction_OnExecute(Object sender, SimpleActionExecuteEventArgs e)
   at DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**Comment by apobekiaris** [comment]
The module works only with the `ThreadSafeDatalayer` due to its asynchronous behavior. See how it is initialized for the win in the `ExcelImporterTester` solution

https://github.com/eXpandFramework/eXpand/blob/10c2e80ca0df5db1e1cfa8d101c2b28ef004f82a/Demos/Modules/ExcelImporter/ExcelImporterTester.Win/WinApplication.cs#L24-L27

**Comment by brond3** [comment]
Thank you.  You are a savior.  It now works perfectly.  My application had the same code but instead of true), true))  it had true),false))

**Comment by brond3** [comment]
Issues addressed.
