### ISSUE TITLE
Sequence contains no matching element on Xpand Express App 18.1.4

### ISSUE THREAD

**Issue by katlego1989** [eXpandFramework/eXpand#342]
I am getting  this error when using  the Xpand Excel Importer on expand framework 18.1.4.

It  uploads the and  maps the .xlsx file , then when click import it throws the  error below:

**Sequence contains no matching element**

   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Xpand.ExpressApp.ExcelImporter.Controllers.ImportExtension.GetImportToObject(ITypeInfo importToTypeInfo, ValueTuple`2[] columnNames, DataRow dataRow, ExcelImport excelImport)
   at Xpand.ExpressApp.ExcelImporter.Controllers.ImportExtension.Import(ExcelImport excelImport, Byte[] bytes)
   at Xpand.ExpressApp.ExcelImporter.Controllers.ExcelImportDetailViewController.ImportActionOnExecute(Object sender, SimpleActionExecuteEventArgs e)
   at DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**Comment by apobekiaris** [comment]
Please provide exact repro steps or preferable a sample. 

>expand framework 18.1.4

note that at the moment source code patches are applied only to latest versions and looks like you using one of the first module versions. I would strongly recommend to upgrade if possible.

**Comment by katlego1989** [comment]
Good Day, 
 
Below are are  the  import steps : 

1.  I attached the   .xlsx file
2. specified the  excel sheet name
3. Specified the xaf object type i am importing to.
4. Check the Use Header Rows check box
5. Did the  mappings ( note: i created default data for relationship looks ups with  empty values to avoid null exceptions)
6. Click Save  to save configurations .
7. Then finally clicked on the Import button. ( Note : this is when the error pops up) 

**Is  the issue resolved in Xpand App Excel Importer  18.2.6   ?** 
and  if  this  also helps  with debugging, kindly note  that my objects have  at least a 3  level inheritance chain i.e  " Customer --> Person --> Policy Holder"
 

![image](https://user-images.githubusercontent.com/48460938/54189629-dcc4c680-44ba-11e9-8053-aeee9b245d07.png)

**Comment by apobekiaris** [comment]
thnks for the info however at the moment I do not have the resources to support such an old version. 

>Is the issue resolved in Xpand App Excel Importer 18.2.6 ?

The module is used from several people and there are no bug reports open. Feel free to explore **all** [related issues](https://github.com/eXpandFramework/eXpand/issues?utf8=%E2%9C%93&q=label%3AExcelImporter+).

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
