### ISSUE TITLE
Show Workflow Instances list scheduled workflow instance error

### ISSUE THREAD

**Issue by nwpratt** [eXpandFramework/eXpand#365]
**Describe the bug**
When I click on the "Show Workflow Instances" list I get the following error when I try to open a Scheduled workflow instance.

Object reference not set to an instance of an object.
   at DevExpress.ExpressApp.Workflow.Visualization.TrackingVisualizationController.OnDeactivated()
   at DevExpress.ExpressApp.Controller.activeList_ResultValueChanged(Object sender, BoolValueChangedEventArgs e)
   at DevExpress.ExpressApp.Utils.BoolList.OnResultValueChanged(Boolean oldResultValue, Boolean resultValue)
   at DevExpress.ExpressApp.Utils.BoolList.EndUpdate()
   at DevExpress.ExpressApp.Utils.BoolList.SetItemValue(String key, Boolean value)
   at DevExpress.ExpressApp.Frame.<>c__DisplayClass52_0.<Dispose>b__1()
   at DevExpress.Persistent.Base.SafeExecutor.Execute(Method method, Object targetObject, String targetObjectIdentifier)
   at DevExpress.ExpressApp.Frame.Dispose()
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.CreateWindow(ShowViewParameters parameters, ShowViewSource showViewSource, Boolean isMain)
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.CreateInspectorWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.CreateInspectorWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewInInspector(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.ShowViewInNewWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewFromCommonView(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.ShowViewStrategyBase.ShowViewCore(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewCore(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.ShowViewStrategyBase.ShowView(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Frame.ProcessActionCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Win.WinWindow.ProcessActionCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Frame.ShowViewAction_ProcessCreatedView(Object sender, ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.OnProcessCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**To Reproduce**
1. Go to 'Show Workflow Instances'
2. Click on a scheduled workflow instance in the list.
3. See error

**Expected behavior**
Show the scheduled workflow instance details like the DevExpress workflow details.

**Comment by apobekiaris** [comment]
thanks for reporting, where exactly did you got this? empty solution? your solution?

**Comment by nwpratt** [comment]
My solution

**Comment by nwpratt** [comment]
I think the problem is with the DevExpress.ExpressApp.Workflow.Visualization.RunningWorkflowInstanceInfoControllerBase class trying to parse the WorkflowUniqueId = “ScheduledWorkflowC0D4E34F_A93B_4B2F_B025_F8E5C6E4EDE1_2” in the PatchVersionedXaml method.

I tried to use the workflow demo application, but I could not get a schedule workflow to run.

**Comment by apobekiaris** [comment]
posting a sample with instructions can speed up things as I am overloaded at the moment.

**Comment by nwpratt** [comment]
[SystemMonitor.zip](https://github.com/eXpandFramework/eXpand/files/3074148/SystemMonitor.zip)
Here is a sample project. Thanks

**Comment by apobekiaris** [comment]
Thanks for the sample and sorry for the delay. You have to use `special` classes with the XpandWorkFlow. Look how WorkflowTester solution is initializing the WorkFlowServer

https://github.com/eXpandFramework/eXpand/blob/84e8e3e037bae7a4a1460c6657d7bb40a3fb49ca/Demos/Modules/Workflow/WorkflowTester.Win/Program.cs#L60-L68

in addition there is the Scheduled Workflows easytest that passed ok in my tests.
https://github.com/eXpandFramework/eXpand/blob/84e8e3e037bae7a4a1460c6657d7bb40a3fb49ca/Demos/Modules/Workflow/WorkflowTester.Module/FunctionalTests/ScheduledWorkflow/ScheduledWorkflow.ets#L1-L31

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
