### ISSUE TITLE
WebShortcutsController controller: Requested value 'ctrl' was not found error

### ISSUE THREAD

**Issue by okanmazman** [eXpandFramework/eXpand#371]
Hi,

_**Exception occurs while activating the 'Xpand.ExpressApp.Web.SystemModule.WebShortcuts.WebShortcutsController' controller:
Requested value 'ctrl' was not found.**_ 
I have this error on runtime . I could not find any kind of the controller mentioned above.
What may my approach be to solve this issue? Any recommendations would be appreciated.

Regards

**Comment by apobekiaris** [comment]
can you post your log?

the controller lives here at the Xpand.ExpressApp.Web assembly in https://github.com/eXpandFramework/eXpand/blob/84e8e3e037bae7a4a1460c6657d7bb40a3fb49ca/Xpand/Xpand.ExpressApp/Xpand.ExpressApp.Web/SystemModule/WebShortcuts/WebShortcutsController.cs#L28

looking at the source code I guess the exception happens in the script registration? so you might try to disable the controller using the next code 

```cs
XpandModuleBase.DisableControllers(typeof(WebShortcutsController))
```

**Comment by okanmazman** [comment]
My error log without the loaded assemblies info:
Error ID: 7254f30b-dca0-48b4-a98f-4b5dff4871e8
Date: 4/16/2019 10:55:04 AM
Request details:
  Url: http://localhost:2064/default.aspx
  Url referrer: http://localhost:2064/Login.aspx?ReturnUrl=/
  SessionID: bciejirwx3ofrrotuh0zbbtj
  Request type: GET
  User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
  User IP: ::1
  User: Admin.Toksoz
  Authenticated user: Admin.Toksoz
================================================================================
The error occurred:

	Type:       HttpUnhandledException
	Message:    Exception of type 'System.Web.HttpUnhandledException' was thrown.
	Data:       1 entries
			'ASPIMPERSONATING'		''
	Stack trace:

   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.AsyncPageProcessRequestBeforeAsyncPointCancellableCallback(Object state)
   at System.Web.HttpContext.InvokeCancellableCallback(WaitCallback callback, Object state)
   at System.Web.UI.Page.LegacyAsyncPageBeginProcessRequest(HttpContext context, AsyncCallback callback, Object extraData)
   at System.Web.UI.Page.AsyncPageBeginProcessRequest(HttpContext context, AsyncCallback callback, Object extraData)
   at ASP.default_aspx.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object data) in c:\Users\OkanMazmanoglu\AppData\Local\Temp\Temporary ASP.NET Files\vs\75850f0e\4a09adcb\App_Web_a1ucsrw2.1.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
	----------------
	InnerException:

			Type:       InvalidOperationException
			Message:    Exception occurs while activating the 'Xpand.ExpressApp.Web.SystemModule.WebShortcuts.WebShortcutsController' controller:
Requested value 'ctrl' was not found.
			Data:       0 entries
			Stack trace:

   at DevExpress.ExpressApp.Window.ActivateControllers()
   at DevExpress.ExpressApp.Window..ctor(XafApplication application, TemplateContext context, ICollection`1 controllers, Boolean isMain, Boolean activateControllersImmediately)
   at DevExpress.ExpressApp.Web.WebWindow..ctor(XafApplication application, TemplateContext context, ICollection`1 controllers, Boolean isMain, Boolean activateControllersImmediately)
   at DevExpress.ExpressApp.Web.WebApplication.CreateWindowCore(TemplateContext context, ICollection`1 controllers, Boolean isMain, Boolean activateControllersImmediately)
   at DevExpress.ExpressApp.XafApplication.CreateWindow(TemplateContext context, ICollection`1 controllers, Boolean createAllControllers, Boolean isMain, View view)
   at DevExpress.ExpressApp.Web.WebApplication.CreateMainWindow()
   at DevExpress.ExpressApp.Web.WebApplication.GetMainWindowByCurrentContext(Page page)
   at DevExpress.ExpressApp.Web.WebApplication.GetRequestedWindow(Page page)
   at DevExpress.ExpressApp.Web.WebApplication.CreateControlsCore(Page page)
   at DevExpress.ExpressApp.Web.WebApplication.CreateControls(Page page)
   at DevExpress.ExpressApp.Web.Templates.BaseXafPage.CreateControls()
   at DevExpress.ExpressApp.Web.Templates.BaseXafPage.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
			----------------
			InnerException:

					Type:       ArgumentException
					Message:    Requested value 'ctrl' was not found.
					Data:       0 entries
					Stack trace:

   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Xpand.ExpressApp.Web.SystemModule.WebShortcuts.WebShortcutsController.<>c.<ShortcutToKeys>b__7_0(Keys current, String item)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Xpand.ExpressApp.Web.SystemModule.WebShortcuts.WebShortcutsController.ShortcutToKeys(String str)
   at Xpand.ExpressApp.Web.SystemModule.WebShortcuts.WebShortcutsController.ReplaceUnsupportedShortcuts(ActionBase actionBase)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Xpand.ExpressApp.Web.SystemModule.WebShortcuts.WebShortcutsController.GetScript()
   at Xpand.ExpressApp.Web.SystemModule.WebShortcuts.WebShortcutsController.OnActivated()
   at DevExpress.ExpressApp.Controller.activeList_ResultValueChanged(Object sender, BoolValueChangedEventArgs e)
   at DevExpress.ExpressApp.Utils.BoolList.OnResultValueChanged(Boolean oldResultValue, Boolean resultValue)
   at DevExpress.ExpressApp.Utils.BoolList.EndUpdate()
   at DevExpress.ExpressApp.WindowController.SetWindow(Window newWindow)
   at DevExpress.ExpressApp.Window.ActivateControllers()
					InnerException is null

**Comment by okanmazman** [comment]
**The error log without loaded assemblies section:**
The error occurred:

	Type:       HttpUnhandledException
	Message:    Exception of type 'System.Web.HttpUnhandledException' was thrown.
	Data:       1 entries
			'ASPIMPERSONATING'		''
	Stack trace:

   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.AsyncPageProcessRequestBeforeAsyncPointCancellableCallback(Object state)
   at System.Web.HttpContext.InvokeCancellableCallback(WaitCallback callback, Object state)
   at System.Web.UI.Page.LegacyAsyncPageBeginProcessRequest(HttpContext context, AsyncCallback callback, Object extraData)
   at System.Web.UI.Page.AsyncPageBeginProcessRequest(HttpContext context, AsyncCallback callback, Object extraData)
   at ASP.default_aspx.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object data) in c:\Users\OkanMazmanoglu\AppData\Local\Temp\Temporary ASP.NET Files\vs\75850f0e\4a09adcb\App_Web_a1ucsrw2.1.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
	----------------
	InnerException:

			Type:       InvalidOperationException
			Message:    Exception occurs while activating the 'Xpand.ExpressApp.Web.SystemModule.WebShortcuts.WebShortcutsController' controller:
Requested value 'ctrl' was not found.
			Data:       0 entries
			Stack trace:

   at DevExpress.ExpressApp.Window.ActivateControllers()
   at DevExpress.ExpressApp.Window..ctor(XafApplication application, TemplateContext context, ICollection`1 controllers, Boolean isMain, Boolean activateControllersImmediately)
   at DevExpress.ExpressApp.Web.WebWindow..ctor(XafApplication application, TemplateContext context, ICollection`1 controllers, Boolean isMain, Boolean activateControllersImmediately)
   at DevExpress.ExpressApp.Web.WebApplication.CreateWindowCore(TemplateContext context, ICollection`1 controllers, Boolean isMain, Boolean activateControllersImmediately)
   at DevExpress.ExpressApp.XafApplication.CreateWindow(TemplateContext context, ICollection`1 controllers, Boolean createAllControllers, Boolean isMain, View view)
   at DevExpress.ExpressApp.Web.WebApplication.CreateMainWindow()
   at DevExpress.ExpressApp.Web.WebApplication.GetMainWindowByCurrentContext(Page page)
   at DevExpress.ExpressApp.Web.WebApplication.GetRequestedWindow(Page page)
   at DevExpress.ExpressApp.Web.WebApplication.CreateControlsCore(Page page)
   at DevExpress.ExpressApp.Web.WebApplication.CreateControls(Page page)
   at DevExpress.ExpressApp.Web.Templates.BaseXafPage.CreateControls()
   at DevExpress.ExpressApp.Web.Templates.BaseXafPage.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
			----------------
			InnerException:

					Type:       ArgumentException
					Message:    Requested value 'ctrl' was not found.
					Data:       0 entries
					Stack trace:

   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Xpand.ExpressApp.Web.SystemModule.WebShortcuts.WebShortcutsController.<>c.<ShortcutToKeys>b__7_0(Keys current, String item)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Xpand.ExpressApp.Web.SystemModule.WebShortcuts.WebShortcutsController.ShortcutToKeys(String str)
   at Xpand.ExpressApp.Web.SystemModule.WebShortcuts.WebShortcutsController.ReplaceUnsupportedShortcuts(ActionBase actionBase)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Xpand.ExpressApp.Web.SystemModule.WebShortcuts.WebShortcutsController.GetScript()
   at Xpand.ExpressApp.Web.SystemModule.WebShortcuts.WebShortcutsController.OnActivated()
   at DevExpress.ExpressApp.Controller.activeList_ResultValueChanged(Object sender, BoolValueChangedEventArgs e)
   at DevExpress.ExpressApp.Utils.BoolList.OnResultValueChanged(Boolean oldResultValue, Boolean resultValue)
   at DevExpress.ExpressApp.Utils.BoolList.EndUpdate()
   at DevExpress.ExpressApp.WindowController.SetWindow(Window newWindow)
   at DevExpress.ExpressApp.Window.ActivateControllers()
					InnerException is null

--------------------------------------------------------------------------------

**Comment by okanmazman** [comment]
Also I cannot see any controller named like above on the controller section within my Module.cs[Design].

**Comment by apobekiaris** [comment]
why you expect the controller to be there? I already posted a link and the assembly the controller lives.

if you have a sample app happy to debug it for you.

**Comment by okanmazman** [comment]
I know that you got bored this kind of question :) I appreciate your help as a DevExp and XAF newbie .
I managed to disable controller and solve the problem.My next step will be providing full functionality in my existing project.Thanks again!

**Comment by apobekiaris** [comment]
not boring at all if I it looks like due to delays or other reasons is probably cause I am overloaded. Feel free to post your Xpand related issues of any kind. If you explain your problem well everything will roll fast.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
