### ISSUE TITLE
Xpand Enum editor not filtering

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#404]
**Describe the bug**
The DataSourceProperty is not honored

**To Reproduce**
Try to add new record, all nums are shown

**Expected behavior**
Filtered according DataSourceProperty

attached same project
[temp.zip](https://github.com/eXpandFramework/eXpand/files/3194626/temp.zip)

**Comment by expand** [comment]
eXpand.lab release [19.1.301.2](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.301.2) includes commit [EnumPropertyEditor binding issues #404](https://github.com/eXpandFramework/eXpand.lab/commit/b51bfb5553e96567db6ccfa3e4925de906b7039b) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by vimarx** [comment]
Now it filters ok, but  changing the  "switch" property do not refresh the datasource accordingly 

![2019-05-20_21-35-43](https://user-images.githubusercontent.com/226800/58060280-021f2200-7b47-11e9-8ccf-d29ae9ffa4f1.gif)

**Comment by expand** [comment]
eXpand.lab release [19.1.301.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.301.4) includes commit [WinEnumDescriptor: Refresh values when object changed #404](https://github.com/eXpandFramework/eXpand.lab/commit/1f38057034c72876a6371605473d62db59fc2932) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by vimarx** [comment]
Null reference in last build

System.NullReferenceException: Object reference not set to an instance of an object.
at Xpand.ExpressApp.Win.PropertyEditors.EnumPropertyEditor.ObjectSpaceOnObjectChanged(Object sender, ObjectChangedEventArgs e)
at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
at DevExpress.ExpressApp.BaseObjectSpace.OnObjectChanged(ObjectChangedEventArgs args)
at DevExpress.ExpressApp.Xpo.XPObjectSpace.SetModified(Object obj, ObjectChangedEventArgs args)
at Xpand.Persistent.Base.General.XpandObjectSpace.SetModified(Object obj, ObjectChangedEventArgs args)
at DevExpress.ExpressApp.BaseObjectSpace.SetModified(Object obj, IMemberInfo memberInfo)
at DevExpress.ExpressApp.DetailView.Editor_ControlValueChanged(Object sender, EventArgs e)
at System.EventHandler.Invoke(Object sender, EventArgs e)
at DevExpress.ExpressApp.Editors.PropertyEditor.OnControlValueChanged()
at DevExpress.ExpressApp.Win.Editors.DXPropertyEditor.Editor_EditValueChanged(Object sender, EventArgs e)
at System.EventHandler.Invoke(Object sender, EventArgs e)
at DevExpress.XtraEditors.Repository.RepositoryItem.RaiseEditValueChangedCore(EventArgs e)
at DevExpress.XtraEditors.Repository.RepositoryItem.RaiseEditValueChanged(EventArgs e)
at DevExpress.XtraEditors.BaseEdit.RaiseEditValueChanged()
at DevExpress.XtraEditors.BaseEdit.OnEditValueChanged()
at DevExpress.XtraEditors.TextEdit.OnEditValueChanged()
at DevExpress.XtraEditors.PopupBaseEdit.OnEditValueChanged()
at DevExpress.XtraEditors.BaseEdit.OnEditValueChanging(ChangingEventArgs e)
at DevExpress.XtraEditors.TextEdit.OnEditValueChanging(ChangingEventArgs e)
at DevExpress.XtraEditors.BaseEdit.set_EditValue(Object value)
at DevExpress.ExpressApp.Win.Editors.LookupEdit.set_EditValue(Object value)
at DevExpress.XtraEditors.PopupBaseEdit.AcceptPopupValue(Object val)
at DevExpress.XtraEditors.PopupBaseEdit.UpdateEditValueOnClose(PopupCloseMode closeMode, Boolean acceptValue, Object newValue, Object oldValue)
at DevExpress.XtraEditors.PopupBaseEdit.DoClosePopup(PopupCloseMode closeMode)
at DevExpress.XtraEditors.PopupContainerEdit.DoClosePopup(PopupCloseMode closeMode)
at DevExpress.XtraEditors.PopupBaseEdit.ClosePopup(PopupCloseMode closeMode)
at DevExpress.ExpressApp.Win.Editors.LookupEdit.ClosePopup(PopupCloseMode closeMode)
at DevExpress.XtraEditors.Popup.PopupBaseForm.ClosePopup(PopupCloseMode closeMode)
at DevExpress.ExpressApp.Win.Editors.LookupEditPopupForm.processCurrentObjectController_CustomProcessSelectedItem(Object sender, CustomProcessListViewSelectedItemEventArgs e)
at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
at DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.processCurrentObjectAction_OnExecute(Object sender, SimpleActionExecuteEventArgs e)
at DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
19.1.0522.3
Void ObjectSpaceOnObjectChanged(System.Object, DevExpress.ExpressApp.ObjectChangedEventArgs)
at Xpand.ExpressApp.Win.PropertyEditors.EnumPropertyEditor.ObjectSpaceOnObjectChanged(Object sender, ObjectChangedEventArgs e)
at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
at DevExpress.ExpressApp.BaseObjectSpace.OnObjectChanged(ObjectChangedEventArgs args)
at DevExpress.ExpressApp.Xpo.XPObjectSpace.SetModified(Object obj, ObjectChangedEventArgs args)
at Xpand.Persistent.Base.General.XpandObjectSpace.SetModified(Object obj, ObjectChangedEventArgs args)
at DevExpress.ExpressApp.BaseObjectSpace.SetModified(Object obj, IMemberInfo memberInfo)
at DevExpress.ExpressApp.DetailView.Editor_ControlValueChanged(Object sender, EventArgs e)
at System.EventHandler.Invoke(Object sender, EventArgs e)
at DevExpress.ExpressApp.Editors.PropertyEditor.OnControlValueChanged()
at DevExpress.ExpressApp.Win.Editors.DXPropertyEditor.Editor_EditValueChanged(Object sender, EventArgs e)
at System.EventHandler.Invoke(Object sender, EventArgs e)
at DevExpress.XtraEditors.Repository.RepositoryItem.RaiseEditValueChangedCore(EventArgs e)
at DevExpress.XtraEditors.Repository.RepositoryItem.RaiseEditValueChanged(EventArgs e)
at DevExpress.XtraEditors.BaseEdit.RaiseEditValueChanged()
at DevExpress.XtraEditors.BaseEdit.OnEditValueChanged()
at DevExpress.XtraEditors.TextEdit.OnEditValueChanged()
at DevExpress.XtraEditors.PopupBaseEdit.OnEditValueChanged()
at DevExpress.XtraEditors.BaseEdit.OnEditValueChanging(ChangingEventArgs e)
at DevExpress.XtraEditors.TextEdit.OnEditValueChanging(ChangingEventArgs e)
at DevExpress.XtraEditors.BaseEdit.set_EditValue(Object value)
at DevExpress.ExpressApp.Win.Editors.LookupEdit.set_EditValue(Object value)
at DevExpress.XtraEditors.PopupBaseEdit.AcceptPopupValue(Object val)
at DevExpress.XtraEditors.PopupBaseEdit.UpdateEditValueOnClose(PopupCloseMode closeMode, Boolean acceptValue, Object newValue, Object oldValue)
at DevExpress.XtraEditors.PopupBaseEdit.DoClosePopup(PopupCloseMode closeMode)
at DevExpress.XtraEditors.PopupContainerEdit.DoClosePopup(PopupCloseMode closeMode)
at DevExpress.XtraEditors.PopupBaseEdit.ClosePopup(PopupCloseMode closeMode)
at DevExpress.ExpressApp.Win.Editors.LookupEdit.ClosePopup(PopupCloseMode closeMode)
at DevExpress.XtraEditors.Popup.PopupBaseForm.ClosePopup(PopupCloseMode closeMode)
at DevExpress.ExpressApp.Win.Editors.LookupEditPopupForm.processCurrentObjectController_CustomProcessSelectedItem(Object sender, CustomProcessListViewSelectedItemEventArgs e)
at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
at DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.processCurrentObjectAction_OnExecute(Object sender, SimpleActionExecuteEventArgs e)
at DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**Comment by apobekiaris** [comment]
#416

**Comment by expand** [comment]
eXpand.lab release [19.1.302.2](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.302.2) includes commit [Make EnumPropertyEditor non default editors and fix null reference on WinEnumpropertyEditor #416 #404](https://github.com/eXpandFramework/eXpand.lab/commit/99fb80a764328776f87dee4af36ed048a1a2539d) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
For me the enum filter is still not updated when the object changes. 
The new `if (e.MemberInfo != null && e.MemberInfo != MemberInfo) {... } ` check is always false, because e.MemberInfo is null.  Only the e.PropertyName of the ObjectChangedEventArgs is set

**Comment by apobekiaris** [comment]
> For me the enum filter is still not updated when the object changes.
> The new `if (e.MemberInfo != null && e.MemberInfo != MemberInfo) {... } ` check is always false, because e.MemberInfo is null. Only the e.PropertyName of the ObjectChangedEventArgs is set

addiotnal checks added in https://github.com/eXpandFramework/eXpand.lab/releases/tag/19.1.402.7

**Comment by expand** [comment]
eXpand.lab release [19.1.402.8](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.8) includes commit that relate to this task:

* [EnumDescriptor: Filtering is not triggered when object change #404](https://github.com/eXpandFramework/eXpand.lab/commit/cc87da60a37c026441f26d0a2370e39fffc0d25c)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by krombipils** [comment]
Enum filtering is working fine now. Thank you!

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
