### ISSUE TITLE
Error when opening model designer

### ISSUE THREAD

**Issue by jacobdeboer33** [eXpandFramework/eXpand#449]
Hi Tolis

I am trying to open my model designer in Visual Studio of a Win project of our product. I'm getting the following error in the designer.

Exception occurs while initializing the 'Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueModule' module: Method not found: 'System.IObservable`1<System.Reactive.Unit> Xpand.XAF.Modules.Reactive.Extensions.CommonExtensions.ToUnit(System.IObservable`1<!!0>)'.
   at DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()
   at DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   at DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(ModuleBase module, String assembliesPath, List`1 additionalModules, ISecurityStrategyBase securityInstance)
   at DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   at DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   at DevExpress.ExpressApp.Design.ModelEditor.EditorPane.PrivateInit(String fileName, ProjectItem currentProjectItem, IVsHierarchy pvHier)
----------InnerException----------
Method not found: 'System.IObservable`1<System.Reactive.Unit> Xpand.XAF.Modules.Reactive.Extensions.CommonExtensions.ToUnit(System.IObservable`1<!!0>)'.
----------StackTrace----------
   at Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueService.Connect(ApplicationModulesManager modulesManager, XafApplication application)
   at Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueModule.Setup(ApplicationModulesManager moduleManager) in D:\a\1\s\src\Modules\CloneMemberValue\Module.cs:line 15
   at DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()

I'm using the  1.2.32 version of the clonemembervalue and the 1.2.32 version of the reactive module.

Is there something I can do to solve this?

Thanks,
Jacob

**Comment by apobekiaris** [comment]
>Method not found: 'System.IObservable1<System.Reactive.Unit> Xpand.XAF.Modules.Reactive.Extensions.CommonExtensions.ToUnit(System.IObservable1<!!0>)'.

what about System.Reactive package? is this referenced? it should be as a dependency

**Comment by jacobdeboer33** [comment]
It seems that this package is referenced. I will now close this ticket until I have time to look at this further

Thanks,
Jacob

**Comment by apobekiaris** [comment]
in addition I suggest you try the XpandModelEditor instead.
