### ISSUE TITLE
Could not create new dashboard Window with expand version Version 19.1.402.0

### ISSUE THREAD

**Issue by david0villa** [eXpandFramework/eXpand#474]
**Describe the bug**
Version 19.1.402.0

Unable to cast object of type 'System.String' to type 'System.Drawing.Image'.

   at Xpand.ExpressApp.Win.PropertyEditors.RichEdit.RichEditContainerRibbon.InitializeComponent()
   at Xpand.ExpressApp.Win.PropertyEditors.RichEdit.RichEditContainerBase.Create(RibbonFormStyle formStyle, XafApplication application)
   at Xpand.ExpressApp.Win.PropertyEditors.RichEdit.RichEditWinPropertyEditor.CreateControlCore()
   at Xpand.ExpressApp.XtraDashboard.Win.PropertyEditors.DashboardXMLEditor.CreateControlCore()
   at DevExpress.ExpressApp.Editors.ViewItem.CreateControl()
   at DevExpress.ExpressApp.Win.Layout.WinLayoutManager.GetControl(ViewItem viewItem, String name, Boolean forceControlCreation)
   at DevExpress.ExpressApp.Win.Layout.WinLayoutManager.controlItem_QueryControl(Object sender, QueryControlEventArgs e)
   at DevExpress.ExpressApp.Win.Layout.XafLayoutControlItem.RaiseQueryControl()
   at DevExpress.ExpressApp.Win.Layout.XafLayoutControlItem.EnsureControl()
   at DevExpress.ExpressApp.Win.Layout.XafLayoutControlItem.RaiseShowHide(Boolean visible)
   at DevExpress.XtraLayout.BaseLayoutItem.SetVisible(Boolean lVisible)
   at DevExpress.XtraLayout.LayoutGroup.UpdateChild(BaseLayoutItem item, Boolean visible)
   at DevExpress.XtraLayout.LayoutGroup.UpdateChildren(Boolean visible)
   at DevExpress.XtraLayout.TabbedGroup.UpdateChildren(Boolean visible)
   at DevExpress.XtraLayout.LayoutGroup.UpdateChild(BaseLayoutItem item, Boolean visible)
   at DevExpress.XtraLayout.LayoutGroup.UpdateChildren(Boolean visible)
   at DevExpress.XtraLayout.LayoutGroup.UpdateChild(BaseLayoutItem item, Boolean visible)
   at DevExpress.XtraLayout.LayoutGroup.UpdateChildren(Boolean visible)
   at DevExpress.XtraLayout.LayoutControlImplementor.UpdateRoot()
   at DevExpress.XtraLayout.LayoutControlImplementor.InvalidateRootOffsetControlsAndScrolls()
   at DevExpress.XtraLayout.LayoutControlImplementor.Invalidate()
   at DevExpress.XtraLayout.LayoutGroup.Invalidate()
   at DevExpress.XtraLayout.LayoutItemContainer.EndUpdate()
   at DevExpress.XtraLayout.LayoutItemContainer.EndChangeUpdate()
   at DevExpress.XtraLayout.LayoutControlImplementor.ProcessLookAndFeelStyleChanged()
   at DevExpress.XtraLayout.LayoutControlImplementor.EndInitCore()
   at DevExpress.XtraLayout.LayoutControlImplementor.set_UpdatedCount(Int32 value)
   at DevExpress.ExpressApp.Win.Layout.WinLayoutManager.LayoutControls(IModelNode layoutNode, ViewItemsCollection viewItems)
   at DevExpress.ExpressApp.View.CreateControls()
   at DevExpress.ExpressApp.Win.Templates.ViewSiteManager.EnsureViewControl()
   at DevExpress.ExpressApp.Win.Templates.ViewSiteManager.FillViewSite()
   at DevExpress.ExpressApp.Win.Templates.ViewSiteManager.OnViewChanged()
   at DevExpress.ExpressApp.Win.Templates.Ribbon.DetailRibbonFormV2.DevExpress.ExpressApp.Templates.IFrameTemplate.SetView(View view)
   at DevExpress.ExpressApp.Frame.SetTemplateView(View view)
   at DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)

**To Reproduce**
1. Go to Dashboard
2. Click on Create new Dashboard Definition

**Expected behavior**
Creating successfully 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Window

**Smartphone (please complete the following information):**

**Additional context**
This looks like Dashboard Definition table with the column data type should be changed. 
I am not sure which table or fields which should reflect to above error.

**Comment by apobekiaris** [comment]
until is fixed can you try not using the RichEditWinPropertyEditor?

**Comment by david0villa** [comment]
Great. Thank you. It is working now without using RichEditWin

**Comment by apobekiaris** [comment]
fixed in https://github.com/eXpandFramework/eXpand/issues/503

**Comment by expand** [comment]
eXpand.lab release [19.1.502.10](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.10) includes commit that relate to this task:

* [Fix RichEditWinPropertyEditor issues #474 #478 #503](https://github.com/eXpandFramework/eXpand.lab/commit/2c6041db17458b85c36e0427d4803ef2b4da6b75)
* [Fix RichEditWinPropertyEditor issues #474 #478 #503](https://github.com/eXpandFramework/eXpand.lab/commit/801728c32f3df8e189d68dc589af4a82b13891a5)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.502.11](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.502.11) includes commit that relate to this task:

* [Fix RichEditWinPropertyEditor issues #474 #478 #503](https://github.com/eXpandFramework/eXpand.lab/commit/4e2b726fc8ef99632c38f65d8381c9de73590e35)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
