### ISSUE TITLE
Error when creating Dashboard view

### ISSUE THREAD

**Issue by david0villa** [eXpandFramework/eXpand#477]
**Describe the bug**
Sequence contains more than one element

   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Xpand.Persistent.Base.General.Controllers.Dashboard.DashboardInteractionController.OnSelectionChanged(SelectionChangedArgs selectionChangedArgs)
   at Xpand.Persistent.Base.General.Controllers.Dashboard.DashboardInteractionController.ListViewSelectionChangedHandler(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at DevExpress.ExpressApp.View.OnSelectionChanged()
   at DevExpress.ExpressApp.Editors.ListEditor.RaiseSelectionChanged()
   at DevExpress.ExpressApp.Win.Editors.WinColumnsListEditor.OnSelectionChanged()
   at DevExpress.ExpressApp.Win.Editors.WinColumnsListEditor.gridDataSourceManager_DataSourceChanged(Object sender, EventArgs e)
   at DevExpress.ExpressApp.Win.Editors.XafGridControlDataSourceAdapter.OnControlDataSourceChanged()
   at DevExpress.ExpressApp.Win.Editors.XafGridControlDataSourceAdapter.TryAssignDataSourceToGridControl()
   at DevExpress.ExpressApp.Win.Editors.WinColumnsListEditor.OnDataSourceChanged()
   at DevExpress.ExpressApp.ListView.RefreshEditorDataSource()
   at DevExpress.ExpressApp.ListView.collectionSource_CollectionChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at DevExpress.ExpressApp.CollectionSourceBase.OnCollectionChanged()
   at DevExpress.ExpressApp.CollectionSourceBase.ResetCollection(Boolean updateObjectsInCriteria)
   at DevExpress.ExpressApp.CollectionSource.objectSpace_Reloaded(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at DevExpress.ExpressApp.BaseObjectSpace.OnReloaded()
   at DevExpress.ExpressApp.Xpo.XPObjectSpace.Reload()
   at DevExpress.ExpressApp.BaseObjectSpace.Refresh()
   at DevExpress.ExpressApp.SystemModule.RefreshController.Refresh()
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**To Reproduce**
1. Open the Dashboard view
2. See error above

**Expected behavior**
I have just created a custom dashboard view to see many views at one page (as the instruction bellow https://documentation.devexpress.com/eXpressAppFramework/113296/Task-Based-Help/Views/How-to-Display-Several-Views-Side-by-Side) . However, we are using the same view with different filter then the error message came up.

**Screenshots**
![2019-07-26_0857_001](https://user-images.githubusercontent.com/43064318/61914359-a8423a80-af83-11e9-9ef0-c8678c5cc021.png)
![2019-07-26_0857](https://user-images.githubusercontent.com/43064318/61914363-aaa49480-af83-11e9-9073-8b682e33905c.png)

**Desktop (please complete the following information):**
- Window 10

**Smartphone (please complete the following information):**
- N/A

**Additional context**
For interim solution, we are creating the different view and this worked. However, if you can advise me how to fix the above issue, that would be great

**Comment by apobekiaris** [comment]
u can try to disable the related controller for start any way you prefer

```cs
    public class DisableController:DashboardInteractionController {
        protected override void OnActivated() {
            
        }
    }
```

**Comment by apobekiaris** [comment]
fixed in 19.1.503

**Comment by expand** [comment]
eXpand.lab release [19.1.503.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.503.1) includes commit that relate to this task:

* [DashboardInteractionController activates without MasterDetailMode #477](https://github.com/eXpandFramework/eXpand.lab/commit/f547366a763cd56b88711f3da992d6dae980ce32)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.2.300.11](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.300.11) includes commit that relate to this task:

* [DashboardInteraction: Fails if same view DashboardViewItem #477 #603](https://github.com/eXpandFramework/eXpand.lab/commit/940f1aef179d87f7e3bdfdd8ef1911613d63ed58)
* [Revert "DashboardInteractionController activates without MasterDetailMode #477"

This reverts commit f547366a763cd56b88711f3da992d6dae980ce32.](https://github.com/eXpandFramework/eXpand.lab/commit/9aee43b7094582172cdfd366fe95f9e42cfb0c38)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.
