### ISSUE TITLE
Model Mapper mandatory?

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#505]
When trying to edit web model with win app (as before), I had the following exception
Is now mandatory ModelMapper?

Thanks

10.08.19 10:09:24.967	no context	SetupModules
VxERP.Win.exe Error: 0 : 10.08.19 10:09:24.994	no context	================================================================================
The error occurred:

	Type:       AggregateException
	Message:    Se han producido uno o varios errores.
	Data:       0 entries
	Stack trace:

   en Xpand.Utils.Helpers.Retry.Do[T](Func`1 action, TimeSpan retryInterval, Int32 retryCount)
   en Xpand.Utils.Helpers.Retry.Do(Action action, TimeSpan retryInterval, Int32 retryCount)
   en Xpand.Persistent.Base.ModelDifference.ModelLoader.GetMasterModel(Boolean tryToUseCurrentTypesInfo, Action`1 action)
   en Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.GetMasterModelCore(Boolean recreate)
   en Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.GetMasterModel(Boolean recreate)
   en Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.OnCurrentObjectChanged()
   en DevExpress.ExpressApp.Editors.ViewItem.set_CurrentObject(Object value)
   en DevExpress.ExpressApp.ObjectView.InitializeItem(ViewItem item)
   en DevExpress.ExpressApp.DetailView.InitializeItem(ViewItem item)
   en DevExpress.ExpressApp.CompositeView.AddItem(ViewItem item)
   en DevExpress.ExpressApp.CompositeView.LoadModelCore()
   en DevExpress.ExpressApp.ObjectView.LoadModelCore()
   en DevExpress.ExpressApp.View.LoadModel()
   en DevExpress.ExpressApp.View.SetModel(IModelView model)
   en Xpand.ExpressApp.ViewFactory.CreateDetailView(XafApplication xafApplication, String viewId, IObjectSpace objectSpace, Object obj, Boolean isRoot, Boolean enableDelayedObjectLoading)
   en Xpand.ExpressApp.SystemModule.XpandSystemModule.ApplicationOnDetailViewCreating(Object sender, DetailViewCreatingEventArgs args)
   en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   en DevExpress.ExpressApp.XafApplication.OnDetailViewCreating(DetailViewCreatingEventArgs args)
   en DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj, Boolean isDelayedObjectLoading, IEnumerable objectsToPrefetch)
   en DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.ShowObjectCore(Object obj, ShowViewParameters showViewParameters, XafApplication application, View sourceView, IObjectSpace objectSpace, IEnumerable objectsToPrefetch)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.ProcessCurrentObject(SimpleActionExecuteEventArgs e)
   en DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.processCurrentObjectAction_OnExecute(Object sender, SimpleActionExecuteEventArgs e)
   en DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	----------------
	InnerException:

			Type:       InvalidOperationException
			Message:    Exception occurs while initializing the 'Xpand.ExpressApp.Web.SystemModule.XpandSystemAspNetModule' module: _xafWebAssembly check that ModelMapperModule is added to the RequiredModuleTypes collection
			Data:       0 entries
			Stack trace:

   en Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager __instance)
   en SetupModules_Patch1(ApplicationModulesManager )
   en DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   en Xpand.Persistent.Base.ModelDifference.ModelBuilder.CreateModulesManager(XafApplication application, String configFileName, String assembliesPath, ITypesInfo typesInfo)
   en Xpand.Persistent.Base.ModelDifference.ModelBuilder.Build(Boolean rebuild)
   en Xpand.Persistent.Base.ModelDifference.ModelLoader.GetMasterModelCore(Boolean rebuild)
   en Xpand.Persistent.Base.ModelDifference.ModelLoader.GetMasterModel(XafApplication xafApplication, Action`1 action)
   en Xpand.Persistent.Base.ModelDifference.ModelLoader.<>c__DisplayClass12_0.<GetMasterModel>b__0()
   en Xpand.Utils.Helpers.Retry.<>c__DisplayClass0_0.<Do>b__0()
   en Xpand.Utils.Helpers.Retry.Do[T](Func`1 action, TimeSpan retryInterval, Int32 retryCount)
			----------------
			InnerException:

					Type:       NullReferenceException
					Message:    _xafWebAssembly check that ModelMapperModule is added to the RequiredModuleTypes collection
					Data:       0 entries
					Stack trace:

   en Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.CheckRequiredParameters(String xafAssemblyName, String controlAssemblyName)
   en Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.GetModelMapperConfiguration(PredefinedMap predefinedMap)
   en Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.ModelMapperConfiguration(PredefinedMap predefinedMap, Action`1 configure)
   en Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.Extend(ApplicationModulesManager modulesManager, PredefinedMap map, Action`1 configure)
   en Xpand.ExpressApp.Web.SystemModule.XpandSystemAspNetModule.Setup(ApplicationModulesManager moduleManager)
   en Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager __instance)
					InnerException is null

**Comment by apobekiaris** [comment]
this case should probably fail as I never tested and support it. I will update u again.

**Comment by vimarx** [comment]
the editing of web models within win app is not working in 19.1.503.0
BTW, this was a nice feature!

**Comment by apobekiaris** [comment]
1. i created a new win web solution
2. Run the web 
3. copy the web assemblies into the win debug folder
4. run the win and edit both models without errors

happy to research further on a failing sample

**Comment by vimarx** [comment]
Where do I have to include this reference? (the modelmappermodule)  

Type:       NullReferenceException
					Message:    _xafWebAssembly check that ModelMapperModule is added to the RequiredModuleTypes collection
					Data:       0 entries
					Stack trace:

   en Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.CheckRequiredParameters(String xafAssemblyName, String controlAssemblyName)
   en Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.GetModelMapperConfiguration(PredefinedMap predefinedMap)
   en Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.ModelMapperConfiguration(PredefinedMap predefinedMap, Action`1 configure)
   en Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.Extend(ApplicationModulesManager modulesManager, PredefinedMap map, Action`1 configure)
   en Xpand.ExpressApp.Web.SystemModule.XpandSystemAspNetModule.Setup(ApplicationModulesManager moduleManager)
   en Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager __instance)
					InnerException is null

**Comment by apobekiaris** [comment]
it means u need to install the module if not already installed

**Comment by emeyke** [comment]
Has this worked? I am still getting the same modelmapper required error when trying to edit the web model although it is installed.
Just in case my sample project.
https://www.dropbox.com/s/s9gngeouo16qrwf/Core.zip?dl=0

**Comment by isatahiri** [comment]
Hello,

I have the same issue in the module.win model : 

Exception occurs while initializing the 'Xpand.ExpressApp.Win.SystemModule.XpandSystemWindowsFormsModule' module: _xtraLayoutAssembly check that ModelMapperModule is added to the RequiredModuleTypes collection

In the Win module designer, i adde the following : 
this.RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.ModelMapper.ModelMapperModule));

But the error persists and so i cannot open the model in module.win.
I can open the model module, win web.module and web without adding any module. 


Detail : 
at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager applicationModulesManager) in D:\a\1\s\src\Modules\Reactive\ReactiveModuleBase.cs:line 35
   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModulesPatch(ApplicationModulesManager __instance) in D:\a\1\s\src\Modules\Reactive\HarmonyPatches\ReactiveModuleBasePatch.cs:line 17
   at SetupModules_Patch1(ApplicationModulesManager )
   at DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   at DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(ModuleBase module, String assembliesPath, List`1 additionalModules, ISecurityStrategyBase securityInstance)
   at DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   at DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   at DevExpress.ExpressApp.Design.ModelEditor.EditorPane.ReInit()
----------InnerException----------
_xtraLayoutAssembly check that ModelMapperModule is added to the RequiredModuleTypes collection
----------StackTrace----------
   at Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.CheckRequiredParameters(String xafAssemblyName, String controlAssemblyName) in D:\a\1\s\src\Modules\ModelMapper\Services\PredefinedMapService.cs:line 717
   at Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.GetModelMapperConfiguration(PredefinedMap predefinedMap) in D:\a\1\s\src\Modules\ModelMapper\Services\PredefinedMapService.cs:line 632
   at Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.ModelMapperConfiguration(PredefinedMap predefinedMap, Action`1 configure) in D:\a\1\s\src\Modules\ModelMapper\Services\PredefinedMapService.cs:line 250
   at Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.Extend(ApplicationModulesManager modulesManager, PredefinedMap map, Action`1 configure) in D:\a\1\s\src\Modules\ModelMapper\Services\PredefinedMapService.cs:line 173
   at Xpand.ExpressApp.Win.SystemModule.XpandSystemWindowsFormsModule.Setup(ApplicationModulesManager moduleManager) in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\SystemModule\XpandSystemWindowsFormsModule.cs:line 88
   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager applicationModulesManager) in D:\a\1\s\src\Modules\Reactive\ReactiveModuleBase.cs:line 28

**Comment by isatahiri** [comment]
Actually after rebooting VS it worked. The clean and rebuild did not work.

**Comment by vimarx** [comment]
> Has this worked? I am still getting the same modelmapper required error when trying to edit the web model although it is installed.
> Just in case my sample project.
> https://www.dropbox.com/s/s9gngeouo16qrwf/Core.zip?dl=0

is this issue solved in 19.2.300.x?

**Comment by vimarx** [comment]
Sample project in 19.2.3 failing to load web model in Win 
[repos.zip](https://github.com/eXpandFramework/eXpand/files/3810598/repos.zip)

This was a nice feature!

**Comment by vimarx** [comment]
the problem is still in 19.2.4, anyone had some success on workaround it?

**Comment by vimarx** [comment]
any news on this?

**Comment by apobekiaris** [comment]
adding a priority tag

**Comment by apobekiaris** [comment]
Issue is prioritized as it contains one of the following labels ***sponsor***, **installation**, **contribution**, **nuget**, **breakingchange**, **ReproSample**, **Deployment**, ***Backer***

**Comment by apobekiaris** [comment]
[Solution9.zip](https://github.com/eXpandFramework/eXpand/files/4093451/Solution9.zip)
I failed to repro the case please modify my sample to demo the problem

**Comment by vimarx** [comment]
I added several modules lines and 
 private void InitializeComponent() {
            // 
            // Solution9AspNetModule
            // 
            this.RequiredModuleTypes.Add(typeof(Solution9.Module.Solution9Module));
            this.RequiredModuleTypes.Add(typeof(DevExpress.ExpressApp.Web.SystemModule.SystemAspNetModule));
            this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ModelDifference.Web.ModelDifferenceAspNetModule));
            this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ExcelImporter.Web.ExcelImporterWebModule));
           
             this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Validation.Web.XpandValidationWebModule));
            this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Web.SystemModule.XpandSystemAspNetModule));
        }
[b1.zip](https://github.com/eXpandFramework/eXpand/files/4094351/b1.zip)
fails

**Comment by apobekiaris** [comment]
thnks for the sample, I researched this case and will be fixed in the next minor. However I want to make a few notes that was respected before and now.

1. You may get FileLoadExceptions if for some reason the assembly is not found in the bin of your win app, the solution is to add it there manually or reference it in your web so it will be copied once build as in the sample where I faced an issue where the Xpand.ExpressApp.ExcelImporter which after I reference it it worked. it really depends on your config and how the assemblies are discovered. If for e.g there are in GAC or you have some other config they should be discovered.
2. Due to the `hacking nature` of this feature sometimes if there is an exception of some TypeNotFound e.g. for Xpand validation rules just reference the platform module in both sides Win/Web

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ModelMapper: Reset TypeMappingService and skip assembly validation for supprting custom TypesInfo usage #505](https://github.com/eXpandFramework/DevExpress.XAF/commit/e21df771910e24094578375abb66777794c2636e)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the [Xpand.XAF.Modules](https://github.com/eXpandFramework/DevExpress.XAF) directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
[Solution9.zip](https://github.com/eXpandFramework/eXpand/files/4134300/Solution9.zip)

posting my modified sample which respects the previous notes

**Comment by expand** [comment]
eXpand.lab release [19.2.502.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.502.4) includes commit that relate to this task:

* [Reset ModelMapper subscriptions to support custom TypesInfo usage #505](https://github.com/eXpandFramework/eXpand.lab/commit/e56f898dd22bb91a504af035a56678ff2f08a938)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Issue is `deprioritized` as `no Assignee found` and scheduled for `auto-close` if no activity in the next `60 days`.

**Comment by emeyke** [comment]
@vimarx can you confirm it is working for you now? I.e. opening web model.

**Comment by vimarx** [comment]
@emeyke now waiting for #669

**Comment by apobekiaris** [comment]
did u test the sample posted b4?

https://github.com/eXpandFramework/eXpand/issues/505#issuecomment-580270585

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
