### ISSUE TITLE
 An asynchronous operation error thrown in iis

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#514]
Hi,

I use the version 19.1.503.1 in my application which i deploy on a Win2016 Srv with iis 10.

When i start the app, i come to the login form. When i enter the username and password, nothing happen and i have a refresh of the login form. 

In the log i see many time this exception : 

`Delayed exception 5:

		Type:       DelayedException
		Message:    An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.. 'Xpand.XAF.Modules.SuppressConfirmation.SuppressConfirmationModule'
		Data:       0 entries
		Stack trace:

		----------------
		InnerException:

				Type:       InvalidOperationException
				Message:    An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.
				Data:       0 entries
				Stack trace:

   at System.Web.AspNetSynchronizationContext.OperationStarted()
   at System.Reactive.Concurrency.SynchronizationContextExtensions.PostWithStartComplete(SynchronizationContext context, Action action)
   at System.Reactive.Concurrency.SynchronizationContextScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action)
   at System.Reactive.Linq.ObservableImpl.EventProducer`2.Session.<>c.<Connect>b__5_0(ValueTuple`3 tuple)
   at System.Reactive.Disposables.AnonymousDisposable`1.Dispose()
   at System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
   at System.Reactive.SafeObserver`1.Dispose(Boolean disposing)
   at System.Reactive.Disposables.CompositeDisposable.Dispose()
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.Dispose(Boolean disposing)
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
   at System.Reactive.Linq.ObservableImpl.TakeUntil`2._.Dispose(Boolean disposing)
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
   at System.Reactive.SafeObserver`1.Dispose(Boolean disposing)
   at System.Reactive.AnonymousSafeObserver`1.OnCompleted()
   at System.Reactive.Sink`1.ForwardOnCompleted()
   at System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OtherObserver.OnNext(TOther value)
   at System.Reactive.SafeObserver`1.WrappingSafeObserver.OnNext(TSource value)
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value)
   at System.Reactive.Linq.ObservableImpl.FirstAsync`1.Sequence._.OnNext(TSource value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at System.ComponentModel.Component.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at DevExpress.Persistent.Base.SafeExecutor.Execute(Method method, Object targetObject, String targetObjectIdentifier)
				InnerException is null`
The default.aspx has the async tag : 
<%@ Page Language="C#" AutoEventWireup="true" Inherits="Default" EnableViewState="false" ValidateRequest="false" CodeBehind="Default.aspx.cs" Async="true" %>

Any idea ? 

BR
ISA

**Comment by isatahiri** [comment]
The first  error in the log is : 
Type:       DelayedExceptionList
	Message:    An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.. 'Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueModule'. 'PME_Affaire.Web.PME_AffaireAspNetApplication'

[logs.txt](https://github.com/eXpandFramework/eXpand/files/3503378/logs.txt)

**Comment by isatahiri** [comment]
The worse is that from visual studio when I run the app with direct connection to the db of my Windows 2016 Server the application starts. But it does not start from iis of the Windows 2016 directly.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [Dynamic action registration fails with IIS #514](https://github.com/eXpandFramework/DevExpress.XAF/commit/d39e2bedd6a67c762b62f45919fc558eece8b490)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.503.2](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.503.2) includes commit that relate to this task:

* [Bump standalone packages #514](https://github.com/eXpandFramework/eXpand.lab/commit/6016db9d47a56019bd7b17e6d2b4dcd25dc3e3c2)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by isatahiri** [comment]
Great one !!! Thanks Tolis. No Error anymore.
