### ISSUE TITLE
ConstraintViolationException

### ISSUE THREAD

**Issue by JakeLogan2019** [eXpandFramework/eXpand#535]
When new DB is created for World Creator when i try to create a new persistent assembly through web UI I get error below.

================================================================================
The error occurred:

	Type:       ConstraintViolationException
	Message:    Executing Sql 'insert into "dbo"."XPWeakReference"("Oid","TargetType","TargetKey","OptimisticLockField","GCRecord","ObjectType")values(@p0,@p1,@p2,@p3,null,@p4) insert into "dbo"."AuditedObjectWeakReference"("Oid","GuidId","IntId","DisplayName")values(@p5,@p6,null,@p7) insert into "dbo"."XPWeakReference"("Oid","TargetType","TargetKey","OptimisticLockField","GCRecord","ObjectType")values(@p8,@p9,@p10,@p11,null,@p12) set @r=1' with parameters '{d31dc16e-4158-4a49-9fca-c3b752539fa4},{13},{[Guid]'b61e62a6-0897-4ebe-80bf-969ae194556c'},{0},{4},{d31dc16e-4158-4a49-9fca-c3b752539fa4},{b61e62a6-0897-4ebe-80bf-969ae194556c},{FullName},{197b89b2-deec-4ea2-930f-1b917cc63750},{14},{[Guid]'95c8d11e-84a9-416a-8663-1e4abda2c70f'},{0},{4},{1}' exception 'System.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_XPWeakReference_TargetType". The conflict occurred in database "Solution1", table "dbo.XPObjectType", column 'OID'.
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_AuditedObjectWeakReference_Oid". The conflict occurred in database "Solution1", table "dbo.XPWeakReference", column 'Oid'.
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_XPWeakReference_TargetType". The conflict occurred in database "Solution1", table "dbo.XPObjectType", column 'OID'.
The statement has been terminated.
The statement has been terminated.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DevExpress.Xpo.DB.MSSqlConnectionProvider.<>c__DisplayClass71_0.<Exec>b__1()
   at DevExpress.Xpo.Logger.LogManager.Log(String category, LogHandlerVoid handler, MessageHandler`1 createMessageHandler, ExceptionHandler exceptionHandler)
   at DevExpress.Xpo.DB.MSSqlConnectionProvider.<>c__DisplayClass71_0.<Exec>b__0()
ClientConnectionId:df186a06-744b-4337-b90f-a43d2dbb7e91
Error Number:547,State:0,Class:16'
	Data:       0 entries
	Stack trace:

   at DevExpress.Xpo.DB.MSSqlConnectionProvider.<>c__DisplayClass71_0.<Exec>b__0()
   at DevExpress.Xpo.Logger.LogManager.Log[T](String category, LogHandler`1 handler, MessageHandler`1 createMessageHandler)
   at DevExpress.Xpo.DB.MSSqlConnectionProvider.Exec(IDbCommand command, IDictionary parameters)
   at DevExpress.Xpo.DB.MSSqlConnectionProvider.ProcessModifyData(ModificationStatement[] dmlStatements)
   at DevExpress.Xpo.DB.DataStoreSerializedBase.ModifyData(ModificationStatement[] dmlStatements)
   at DevExpress.Xpo.DB.ConnectionProviderSql.ModifyData(ModificationStatement[] dmlStatements)
   at DevExpress.Xpo.SimpleDataLayer.<>c__DisplayClass6_0.<ModifyData>b__0()
   at DevExpress.Xpo.SimpleDataLayer.ReentrancyAndThreadSafetyChecked[T](Func`1 action)
   at DevExpress.Xpo.SimpleDataLayer.ModifyData(ModificationStatement[] dmlStatements)
   at DevExpress.Xpo.SimpleObjectLayer.CommitChanges(Session session, ICollection fullListForDelete, ICollection completeListForSave)
   at DevExpress.Xpo.Session.FlushChangesInsideTransaction()
   at DevExpress.Xpo.Session.FlushChanges()
   at DevExpress.Xpo.Session.<CommitTransaction>b__314_0()
   at DevExpress.Xpo.Logger.LogManager.Log(String category, LogHandlerVoid handler, MessageHandler`1 createMessageHandler, ExceptionHandler exceptionHandler)
   at DevExpress.Xpo.Session.CommitTransaction()
   at DevExpress.Xpo.UnitOfWork.CommitChanges()
   at DevExpress.Persistent.AuditTrail.AuditDataStore`2.Save(Session session, List`1 itemsToSave, IAuditTimestampStrategy timestampStrategy, String currentUserName)
   at DevExpress.Persistent.AuditTrail.AuditTrailService.SaveAuditDataByDefault(Session session, List`1 itemsToSave)
   at DevExpress.Persistent.AuditTrail.AuditTrailService.InternalSaveAuditData(Session session, List`1 itemsToSave)
   at DevExpress.Persistent.AuditTrail.AuditTrailService.SaveAuditData(Session session)
   at DevExpress.ExpressApp.AuditTrail.AuditTrailModule.ObjectSpace_Committed(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at DevExpress.ExpressApp.BaseObjectSpace.OnCommitted()
   at DevExpress.ExpressApp.BaseObjectSpace.CommitChanges()
   at DevExpress.ExpressApp.Web.SystemModule.WebModificationsController.Save(SimpleActionExecuteEventArgs args)
   at DevExpress.ExpressApp.SystemModule.ModificationsController.saveAction_OnExecute(Object sender, SimpleActionExecuteEventArgs e)
   at DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	----------------
	InnerException:

			Type:       SqlException
			Message:    The INSERT statement conflicted with the FOREIGN KEY constraint "FK_XPWeakReference_TargetType". The conflict occurred in database "Solution1", table "dbo.XPObjectType", column 'OID'.
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_AuditedObjectWeakReference_Oid". The conflict occurred in database "Solution1", table "dbo.XPWeakReference", column 'Oid'.
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_XPWeakReference_TargetType". The conflict occurred in database "Solution1", table "dbo.XPObjectType", column 'OID'.
The statement has been terminated.
The statement has been terminated.
The statement has been terminated.
			Data:       6 entries
					'HelpLink.ProdName'		'Microsoft SQL Server'
					'HelpLink.ProdVer'		'13.00.4001'
					'HelpLink.EvtSrc'		'MSSQLServer'
					'HelpLink.EvtID'		'547'
					'HelpLink.BaseHelpUrl'		'http://go.microsoft.com/fwlink'
					'HelpLink.LinkId'		'20476'
			Stack trace:

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DevExpress.Xpo.DB.MSSqlConnectionProvider.<>c__DisplayClass71_0.<Exec>b__1()
   at DevExpress.Xpo.Logger.LogManager.Log(String category, LogHandlerVoid handler, MessageHandler`1 createMessageHandler, ExceptionHandler exceptionHandler)
   at DevExpress.Xpo.DB.MSSqlConnectionProvider.<>c__DisplayClass71_0.<Exec>b__0()
			InnerException is null

--------------------------------------------------------------------------------

**Comment by apobekiaris** [comment]
again clear and detailed repro instructions wanted

**Comment by JakeLogan2019** [comment]
[Solution1.zip](https://github.com/eXpandFramework/eXpand/files/3603534/Solution1.zip)

Pretty much for both of my issues... You may have to re-map some of the eXpand dlls in Module, etc...

**Comment by apobekiaris** [comment]
again I fail to reproduce the issue with the posted sample neither wit a new Xpand solution. Can you try to delete the DB?

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ProgressBarViewItem: Cross thread exception observe on SynchronizationContext.Current #535](https://github.com/eXpandFramework/DevExpress.XAF/commit/8465d426d4979a12b3e1cb380064d903ea4d3758)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ProgressBarViewItem: Cross thread exception observe on SynchronizationContext.Current #535](https://github.com/eXpandFramework/DevExpress.XAF/commit/8465d426d4979a12b3e1cb380064d903ea4d3758)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
