### ISSUE TITLE
Exception occurs while initializing the CloneMemberValueModule module: Method not found.

### ISSUE THREAD

**Issue by gerritmulder** [eXpandFramework/eXpand#546]
We got this when starting our application, we use the SystemModule with version 19.1.503 together with XAF 19.1.5

```
Exception occurs while initializing the 'Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueModule' module: Method not found: 'System.IObservable`1<!!0> Xpand.XAF.Modules.Reactive.Extensions.CommonExtensions.Tracer(System.IObservable`1<!!0>, Boolean)'.

   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager __instance)
   at SetupModules_Patch1(ApplicationModulesManager )
   at DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   at DevExpress.ExpressApp.XafApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   at DevExpress.ExpressApp.Win.WinApplication.<>c__DisplayClass77_0.<SetupCore>b__0()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by gerritmulder** [comment]
I have tested this with a barebone XAF app and the error does not occur, therefore I will close the issue.

**Comment by gerritmulder** [comment]
@apobekiaris for your knowledge. The problem was that I had a different version of ViewEditMode installed then the CloneMemberValue of eXpandSystem. When installing the same, the problem disappeared.

**Comment by apobekiaris** [comment]
there was a problematic nuspec declaration for the CloneMemberValue probably it affected this case as well
