### ISSUE TITLE
GridListEditorEventController Error

### ISSUE THREAD

**Issue by cevious** [eXpandFramework/eXpand#566]
Hi
GridListEditorEventController Error during for FotterOptionOn and User RightClick

Error Log
Object reference not set to an instance of an object.

   at Xpand.ExpressApp.Win.SystemModule.RuleCollector..ctor(IModelListView modelListView) in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\SystemModule\GridListEditorEventController.cs:line 129
   at Xpand.ExpressApp.Win.SystemModule.GridListEditorEventController.GridViewOnPopupMenuShowing(Object sender, PopupMenuShowingEventArgs e) in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp.Win\SystemModule\GridListEditorEventController.cs:line 38
   at DevExpress.XtraGrid.Views.Grid.PopupMenuShowingEventHandler.Invoke(Object sender, PopupMenuShowingEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.GridView.RaisePopupMenuShowing(PopupMenuShowingEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.GridView.DoShowGridMenu(GridMenuEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.Handler.GridHandler.OnMouseDown(MouseEventArgs ev)
   at DevExpress.Utils.Controls.BaseHandler.ProcessEvent(EventType etype, Object args)
   at DevExpress.XtraGrid.GridControl.OnMouseDown(MouseEventArgs ev)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   at DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by apobekiaris** [comment]
please post more details on how to repro it

**Comment by cevious** [comment]
Open Model Edtior
Enable IsFooterVisible in ListView
Go and RightCLick on FooterPanel

Exception Raised

**Comment by apobekiaris** [comment]
I fail to repro the problem from the info you posted. This is what I tried:

1. Create a new Empty XAF solution
2. Install latest nuget SystemWin package from lab servers 
3. Modify the model
3. Right click with no issues
attaching my sample
[Solution267.zip](https://github.com/eXpandFramework/eXpand/files/3694051/Solution267.zip)

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
