### ISSUE TITLE
XpandListView use SimpleDataLayer instead of ThreadSafeDataLayer 

### ISSUE THREAD

**Issue by larspl** [eXpandFramework/eXpand#586]
**Question**
This runtime Error is unclear for me. 

i use a xafDataLayer Proxy and set 
`
private ThreadSafeDataLayer xafDataLayer;

 IDisposable[] disposableObjects;
xafDataStore = XpoDefault.GetConnectionProvider(xafConnectionString, AutoCreateOption.DatabaseAndSchema, out disposableObjects);
            xafDataLayer = new ThreadSafeDataLayer(xafDictionary, xafDataStore);
DataLayerUtil.XAFDataLayer = xafDataLayer;
`
so that the XAFDataLayer is ThreadSafe in my opinion. 

why the XpandListView dont use the xafDataLayer? 

**Additional context**
`================================================================================
The error occurred:

	Type:       InvalidOperationException
	Message:    Exception occurs while assigning the 'XpandListView, ID:IBoMBE_ListView_Default' view to XpandWebWindow:
Reentrancy or cross thread operation detected. Use ThreadSafeDataLayer or find the cause of the cross thread access to the SimpleDataLayer instance from your code. To suppress this exception, set DevExpress.Xpo.SimpleDataLayer.SuppressReentrancyAndThreadSafetyCheck = true
	Data:       0 entries
	Stack trace:

   at DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
   at DevExpress.ExpressApp.Web.ShowViewStrategy.ShowViewInCurrentWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Frame.ProcessActionCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.OnProcessCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	----------------
	InnerException:

			Type:       InvalidOperationException
			Message:    Reentrancy or cross thread operation detected. Use ThreadSafeDataLayer or find the cause of the cross thread access to the SimpleDataLayer instance from your code. To suppress this exception, set DevExpress.Xpo.SimpleDataLayer.SuppressReentrancyAndThreadSafetyCheck = true
			Data:       0 entries
			Stack trace:

   at DevExpress.Xpo.SimpleDataLayer.ReentrancyAndThreadSafetyChecked[T](Func`1 action)
   at DevExpress.Xpo.Helpers.ObjectCollectionLoader.InternalLoadData(ObjectsQuery[] queries)
   at DevExpress.Xpo.Helpers.ObjectCollectionLoader.LoadObjects(ObjectsQuery[] queries)
   at DevExpress.Xpo.SimpleObjectLayer.LoadObjects(Session session, ObjectsQuery[] queries)
   at DevExpress.Xpo.Logger.LogManager.Log[T](String category, LogHandler`1 handler, MessageHandler`1 createMessageHandler)
   at DevExpress.Xpo.Session.GetObjects(ObjectsQuery query)
   at DevExpress.Xpo.XPBaseCollection.Load()
   at DevExpress.Xpo.XPBaseCollection.get_Objects()
   at DevExpress.Xpo.XPBaseCollection.get_Count()
   at DevExpress.Data.Helpers.BaseDataControllerHelper.get_Count()
   at DevExpress.Data.DataController.get_VisibleListSourceRowCount()
   at DevExpress.Data.DataController.CheckRaiseVisibleCountChanged(Int32 prevVCount)
   at DevExpress.Data.DataController.DoRefresh(Boolean useRowsKeeper)
   at DevExpress.Data.DataController.EndUpdateCore(Boolean sortUpdate)
   at DevExpress.Data.DataControllerBase.OnListSourceChanged()
   at DevExpress.Data.DataControllerBase.SetListSourceCore(IList value)
   at DevExpress.Web.Data.WebDataControllerProvider.CreateDataController(Object dataSource)
   at DevExpress.Web.Data.WebDataControllerProvider.SetDataSource(Object dataSource)
   at DevExpress.Web.Data.WebDataProxy.SetDataSource(Object dataSource)
   at DevExpress.Web.ASPxGridBase.PerformDataBinding(String dataHelperName, IEnumerable data)
   at DevExpress.Web.Internal.DataHelper.OnDataSourceViewSelectCallback(IEnumerable data)
   at DevExpress.Web.Internal.DataContainer.PerformSelect()
   at DevExpress.Web.ASPxDataWebControlBase.DataBindInternal()
   at DevExpress.Web.ASPxWebControl.DataBind()
   at DevExpress.ExpressApp.Web.Editors.ASPx.ASPxGridListEditor.DataBind()
   at DevExpress.ExpressApp.Web.Editors.ASPx.ASPxGridListEditor.grid_Init(Object sender, EventArgs e)
   at System.Web.UI.Control.OnInit(EventArgs e)
   at DevExpress.Web.ASPxWebControlBase.OnInit(EventArgs e)
   at DevExpress.Web.ASPxDataWebControlBase.OnInit(EventArgs e)
   at DevExpress.Web.ASPxGridBase.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DevExpress.ExpressApp.Web.Controls.ViewSiteControl.view_ControlsCreated(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at DevExpress.ExpressApp.View.OnControlsCreated()
   at Xpand.ExpressApp.XpandListView.OnControlsCreated() in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp\XpandListView.cs:line 35
   at DevExpress.ExpressApp.View.CreateControls()
   at DevExpress.ExpressApp.Web.Controls.ViewSiteControl.SetView(View view)
   at DevExpress.ExpressApp.Web.Templates.BaseXafPage.SetView(View view)
   at DevExpress.ExpressApp.Frame.SetTemplateView(View view)
   at DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
			InnerException is null
`

**Comment by apobekiaris** [comment]
maybe u have more DataLayers? the modules do not create DataLayers they use the one from DefaultOpjectSpaceProvider

**Comment by larspl** [comment]
Yes, 

in AspNetApplication i override : 

protected override void OnCreateCustomObjectSpaceProvider(CreateCustomObjectSpaceProviderEventArgs args){
//            base.OnCreateCustomObjectSpaceProvider(args);
            _provider = new XpoDataStoreProvider();
            args.ObjectSpaceProvider = new XPObjectSpaceProvider(_provider);
            args.ObjectSpaceProviders.Add(new NonPersistentObjectSpaceProvider());
        }

        protected override void OnCustomCheckCompatibility(CustomCheckCompatibilityEventArgs args){
            base.OnCustomCheckCompatibility(args);


            if (!_provider.IsInitialized){
                _provider.Initialize(((XPObjectSpaceProvider) ObjectSpaceProvider).XPDictionary,
                    ConfigurationManager.ConnectionStrings["OnlineDB1ConnectionString"].ConnectionString,
                    ConfigurationManager.ConnectionStrings["OnlineDB2ConnectionString"].ConnectionString,
                    ConfigurationManager.ConnectionStrings["XAFDatabaseConnectionString"].ConnectionString);
            }
            
            //GlobalSettings.BuildDynamicViewIDsString(ObjectSpaceProvider.CreateObjectSpace());
        }

this will we used in 

  public class XpoDataStoreProxy : IDataStore
    {
        private ThreadSafeDataLayer onlineDB1TsDataLayer;
        private IDataStore onlineDB1DataStore;
        private ThreadSafeDataLayer onlineDB2DataLayer;
        private IDataStore onlineDB2DataStore;
        private ThreadSafeDataLayer xafDataLayer;
        private IDataStore xafDataStore;
...

this are all ThreadSafe

**how i can initial set the DefaultObjectSpaceProvider to ThreadSafe?**

**Comment by apobekiaris** [comment]
u need to make sure its the same datalyer we are talking here the exception lead us that is not the same or something change its behaviour. Tha obly module that deals with DataLayer is WC and from what u said u do not have it installed

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
