### ISSUE TITLE
 TypeInitializationException in Xpand.XAF.Modules.Reactive.Logger.ReactiveTraceListener

### ISSUE THREAD

**Issue by larspl** [eXpandFramework/eXpand#588]
**Describe the bug**
In A XAF Web App ( System.Web) the  Xpand.XAF.Modules.Reactive.Logger.ReactiveTraceListener' can't open after IISReset the own created log file anymore. 

The same is happens when more then **ONE** user will access the **webserver** 

i think this is the rout cause and not the **TypeInitializationException**

> Type:       IOException
> 			Message:    The process cannot access the file 'D:\www_cdb1\bin\9027e41c_RXLogger.log' because it is being used by another process.
> 			Data:       0 entries
> 			Stack trace:
> 

**To Reproduce**
System.Web App

**Additional context**

> w3wp.exe Error: 0 : 13.10.19 12:41:06.892	a0kyfwbfe0wqukpo312ekyrb	================================================================================
The error occurred:

	Type:       TypeInitializationException
	Message:    The type initializer for 'Xpand.XAF.Modules.Reactive.Logger.ReactiveTraceListener' threw an exception.
	Data:       1 entries
			'ASPIMPERSONATING'		''
	Stack trace:

   at Xpand.XAF.Modules.Reactive.Logger.ReactiveTraceListener..ctor(String applicationTitle) in D:\a\1\s\src\Modules\Reactive.Logger\ReactiveTraceListener.cs:line 14
   at Xpand.XAF.Modules.Reactive.Logger.ReactiveLoggerService.Connect(ReactiveLoggerModule reactiveLoggerModule) in D:\a\1\s\src\Modules\Reactive.Logger\ReactiveLoggerService.cs:line 47
   at Xpand.XAF.Modules.Reactive.Logger.ReactiveLoggerModule.Setup(XafApplication application) in D:\a\1\s\src\Modules\Reactive.Logger\Module.cs:line 33
   at DevExpress.ExpressApp.ModuleList.OnInsert(Int32 index, Object value)
   at System.Collections.CollectionBase.System.Collections.IList.Add(Object value)
   at DevExpress.ExpressApp.ApplicationModulesManager.AddModuleIntoList(ModuleBase module, IList`1 moduleList, List`1 requiredModules)
   at DevExpress.ExpressApp.ApplicationModulesManager.EnsureModuleInList(Type moduleType, IList`1 moduleList, List`1 requiredModules)
   at DevExpress.ExpressApp.ApplicationModulesManager.AddModuleIntoList(ModuleBase module, IList`1 moduleList, List`1 requiredModules)
   at DevExpress.ExpressApp.ModuleList.RefreshRequiredModules()
   at DevExpress.ExpressApp.Utils.BindingListBase`1.EndInit()
   at pnc.dgv.cdb.Web.CdbAspNetApplication..ctor() in c:\tfsagents\dgvcrmagent\_work\35\s\pnc.dgv.cdb.Web\WebApplication.cs:line 149
   at pnc.dgv.cdb.Web.Global.Session_Start(Object sender, EventArgs e) in c:\tfsagents\dgvcrmagent\_work\35\s\pnc.dgv.cdb.Web\Global.asax.cs:line 111
   at System.Web.SessionState.SessionStateModule.CompleteAcquireState()
   at System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
	----------------
	InnerException:

			Type:       IOException
			Message:    The process cannot access the file 'D:\www_cdb1\bin\9027e41c_RXLogger.log' because it is being used by another process.
			Data:       0 entries
			Stack trace:

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Xpand.XAF.Modules.Reactive.Logger.ReactiveTraceListener.<>c.<.cctor>b__7_0() in D:\a\1\s\src\Modules\Reactive.Logger\ReactiveTraceListener.cs:line 13
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Xpand.XAF.Modules.Reactive.Logger.ReactiveTraceListener..cctor() in D:\a\1\s\src\Modules\Reactive.Logger\ReactiveTraceListener.cs:line 12
			InnerException is null

--------------------------------------------------------------------------------
Loaded assemblies
#565 #587

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ReactiveLogger: Fix File IOException on RXLogger.log #588 #587 #583](https://github.com/eXpandFramework/DevExpress.XAF/commit/59cf652096ebee9add61e7adc2bd2747fd2652a9)
* [ReactiveLogger: Do_Not_Trace_If_TraceSources_Level_Off #588 #587 #583](https://github.com/eXpandFramework/DevExpress.XAF/commit/996b7a7454cbdf516066d0c3df894e1184864ade)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.605.6](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.605.6) includes commit that relate to this task:

* [Bump standalone packages
 1. ReactiveLogger: Do_Not_Trace_If_TraceSources_Level_Off #588 #587 #583
1. ReactiveLogger: Fix File IOException on RXLogger.log #588 #587 #583](https://github.com/eXpandFramework/eXpand.lab/commit/b44eef6c180e5b1662b5b0323e2f675302570adf)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
