### ISSUE TITLE
Still having DelayedException in production

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#597]
Hello,

I'm in the version 19.1.605.9 and i also have a DelayedException, in production. 
In 24hours i have 2MB in the eXpressAppFramework. 

No access denied exception in the log. 

Is this the same error as #543 ?

Was this error corrected ? 

[eXpressAppFramework.log](https://github.com/eXpandFramework/eXpand/files/3752713/eXpressAppFramework.log)
`Delayed exception 4:

		Type:       DelayedException
		Message:    An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.. 'Xpand.XAF.Modules.RefreshView.RefreshViewModule'
		Data:       0 entries
		Stack trace:

		----------------
		InnerException:

				Type:       InvalidOperationException
				Message:    An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.
				Data:       0 entries
				Stack trace:

   at System.Web.AspNetSynchronizationContext.OperationStarted()
   at System.Reactive.Concurrency.SynchronizationContextExtensions.PostWithStartComplete(SynchronizationContext context, Action action) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\SynchronizationContextExtensions.cs:line 35
   at System.Reactive.Concurrency.SynchronizationContextScheduler.Schedule[TState](TState state, Func`3 action) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\SynchronizationContextScheduler.cs:line 71
   at System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 61
   at System.Reactive.Linq.ObservableImpl.EventProducer`2.Session.<>c.<Connect>b__5_0(ValueTuple`3 tuple) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\FromEvent.cs:line 294
   at System.Reactive.Disposables.AnonymousDisposable`1.Dispose() in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Disposables\AnonymousDisposable.cs:line 73
   at System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Disposables\Disposable.cs:line 238
   at System.Reactive.SafeObserver`1.Dispose(Boolean disposing) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\SafeObserver.cs:line 93
   at System.Reactive.Disposables.CompositeDisposable.Dispose() in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Disposables\CompositeDisposable.cs:line 243
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.Dispose(Boolean disposing) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\SelectMany.cs:line 900
   at System.Reactive.Sink`1.Dispose() in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 31
   at System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Disposables\Disposable.cs:line 238
   at System.Reactive.Sink`1.Dispose() in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 31
   at System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Disposables\Disposable.cs:line 238
   at System.Reactive.Sink`1.Dispose() in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 31
   at System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Disposables\Disposable.cs:line 238
   at System.Reactive.Linq.ObservableImpl.TakeUntil`2._.Dispose(Boolean disposing) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\TakeUntil.cs:line 52
   at System.Reactive.Sink`1.Dispose() in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 31
   at System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Disposables\Disposable.cs:line 238
   at System.Reactive.SafeObserver`1.Dispose(Boolean disposing) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\SafeObserver.cs:line 93
   at System.Reactive.AnonymousSafeObserver`1.OnCompleted() in d:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 74
   at System.Reactive.Sink`1.ForwardOnCompleted() in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 55
   at System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OtherObserver.OnNext(TOther value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\TakeUntil.cs:line 93
   at System.Reactive.SafeObserver`1.WrappingSafeObserver.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\SafeObserver.cs:line 31
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 50
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 48
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 48
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\SelectMany.cs:line 946
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at System.ComponentModel.Component.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at DevExpress.Persistent.Base.SafeExecutor.Execute(Method method, Object targetObject, String targetObjectIdentifier)
				InnerException is null`

**Comment by apobekiaris** [comment]
Hi

Clear pros instruction or a sample is needed

**Comment by isatahiri** [comment]
Hi,

Publish you web project (right click Publish)
Copy files into iis in server. 
Run the app via Chrome. 

In the logger, everything is set to OFF. 

BR
ISA

**Comment by apobekiaris** [comment]
I do not see any sample here, r u still having issues?

**Comment by vimarx** [comment]
is this issue still open? I have the same problem in 19.2.301.x

**Comment by vimarx** [comment]
@isatahiri have you fixed it?

**Comment by isatahiri** [comment]
Sorry for the late answer.
I cannot answer to that yet as i have not migrated to the 19.2 due to some issue.
As soon as i do the migration to the 19.2, i'll answer in this issue. 

Does your question mean that you have migrated to 19.2 and still have this issue ?

BR
ISA

**Comment by vimarx** [comment]
@isatahiri  I have the problem in 19.2.x  in login.aspx in web

**Comment by vimarx** [comment]
I'm in a hurry, can't solve this exception in web! even with last lab or with 19.1.700.x ported to 19.2

System.InvalidOperationException: Una operación asincrónica no se puede comenzar en este momento. Solo se pueden comenzar operaciones asincrónicas dentro de un controlador o módulo asincrónico o durante ciertos eventos en el ciclo de vida de la página. Si esta excepción se produjo mientras se ejecutaba una página, asegúrese de que la página esté marcada con . Esta excepción puede también indicar que se intentó llamar a un método "async void" que generalmente no es compatible con el procesamiento de solicitudes de ASP.NET. En su lugar, el método asincrónico debería devolver una Tarea y el llamador debería esperarla.
en System.Web.AspNetSynchronizationContext.OperationStarted()
en System.Reactive.Concurrency.SynchronizationContextExtensions.PostWithStartComplete(SynchronizationContext context, Action action)
en System.Reactive.Concurrency.SynchronizationContextScheduler.Schedule[TState](TState state, Func`3 action)
en System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action)
en System.Reactive.Linq.ObservableImpl.EventProducer`2.Session.<>c.b__5_0(ValueTuple`3 tuple)
en System.Reactive.Disposables.AnonymousDisposable`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Sink`1.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Sink`1.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Sink`1.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Sink`1.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Sink`1.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Sink`1.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Sink`1.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TrySetSerial(IDisposable& fieldRef, IDisposable value)
en System.Reactive.ConcatSink`1.OnCompleted()
en System.Reactive.Sink`1.ForwardOnCompleted()
en System.Reactive.Sink`2.OnCompleted()
en System.Reactive.Sink`1.ForwardOnCompleted()
en System.Reactive.Linq.ObservableImpl.FirstAsync`1.Sequence._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.BufferClosingObserver.OnNext(TBufferClosing value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.FirstAsync`1.Sequence._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.FirstAsync`1.Sequence._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Subjects.Subject`1.OnNext(T value)
en System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.b__1(Object sender, TEventArgs eventArgs)
en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
en DevExpress.ExpressApp.XafApplication.OnObjectSpaceCreated(IObjectSpace objectSpace)
en DevExpress.ExpressApp.XafApplication.CreateObjectSpace(Type objectType)
en Xpand.ExpressApp.ModelDifference.DictionaryStores.XpoDictionaryDifferenceStore..ctor(XafApplication application)
en Xpand.ExpressApp.ModelDifference.ModelDifferenceModule.ApplicationOnCreateCustomUserModelDifferenceStore(Object sender, CreateCustomModelDifferenceStoreEventArgs createCustomModelDifferenceStoreEventArgs)
en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
en DevExpress.ExpressApp.XafApplication.CreateUserModelDifferenceStore(CreateCustomModelDifferenceStoreEventArgs args)
en DevExpress.ExpressApp.XafApplication.LoadUserDifferences()
en DevExpress.ExpressApp.XafApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
en DevExpress.ExpressApp.XafApplication.showLogonAction_OnExecute(Object sender, PopupWindowShowActionExecuteEventArgs args)
en DevExpress.ExpressApp.Actions.PopupWindowShowAction.RaiseExecute(ActionBaseEventArgs eventArgs)
en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
WEB
Void OperationStarted()
en System.Web.AspNetSynchronizationContext.OperationStarted()
en System.Reactive.Concurrency.SynchronizationContextExtensions.PostWithStartComplete(SynchronizationContext context, Action action)
en System.Reactive.Concurrency.SynchronizationContextScheduler.Schedule[TState](TState state, Func`3 action)
en System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action)
en System.Reactive.Linq.ObservableImpl.EventProducer`2.Session.<>c.b__5_0(ValueTuple`3 tuple)
en System.Reactive.Disposables.AnonymousDisposable`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Sink`1.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Sink`1.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Sink`1.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Sink`1.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Sink`1.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Sink`1.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
en System.Reactive.Sink`1.Dispose(Boolean disposing)
en System.Reactive.Sink`1.Dispose()
en System.Reactive.Disposables.Disposable.TrySetSerial(IDisposable& fieldRef, IDisposable value)
en System.Reactive.ConcatSink`1.OnCompleted()
en System.Reactive.Sink`1.ForwardOnCompleted()
en System.Reactive.Sink`2.OnCompleted()
en System.Reactive.Sink`1.ForwardOnCompleted()
en System.Reactive.Linq.ObservableImpl.FirstAsync`1.Sequence._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.BufferClosingObserver.OnNext(TBufferClosing value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.FirstAsync`1.Sequence._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.FirstAsync`1.Sequence._.OnNext(TSource value)
en System.Reactive.Sink`1.ForwardOnNext(TTarget value)
en System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
en System.Reactive.Subjects.Subject`1.OnNext(T value)
en System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.b__1(Object sender, TEventArgs eventArgs)
en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
en DevExpress.ExpressApp.XafApplication.OnObjectSpaceCreated(IObjectSpace objectSpace)
en DevExpress.ExpressApp.XafApplication.CreateObjectSpace(Type objectType)
en Xpand.ExpressApp.ModelDifference.DictionaryStores.XpoDictionaryDifferenceStore..ctor(XafApplication application)
en Xpand.ExpressApp.ModelDifference.ModelDifferenceModule.ApplicationOnCreateCustomUserModelDifferenceStore(Object sender, CreateCustomModelDifferenceStoreEventArgs createCustomModelDifferenceStoreEventArgs)
en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
en DevExpress.ExpressApp.XafApplication.CreateUserModelDifferenceStore(CreateCustomModelDifferenceStoreEventArgs args)
en DevExpress.ExpressApp.XafApplication.LoadUserDifferences()
en DevExpress.ExpressApp.XafApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
en DevExpress.ExpressApp.XafApplication.showLogonAction_OnExecute(Object sender, PopupWindowShowActionExecuteEventArgs args)
en DevExpress.ExpressApp.Actions.PopupWindowShowAction.RaiseExecute(ActionBaseEventArgs eventArgs)
en DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**Comment by apobekiaris** [comment]
Without a repro cases cannot help much. As u probably know this is a generic message from an async call out of context and provides no further info. You can work it out removing parts of the framework step by step until u identify the problem.

**Comment by apobekiaris** [comment]
see #661

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
