### ISSUE TITLE
Dashboard Not Refreshing

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#603]
I have two list views in a dashboard. One selection used to filter the second list. It does not fire now. I think this broke it.

https://github.com/eXpandFramework/eXpand/issues/477

My listviews are not masterdetail so the OnSelectionChanged(new SelectionChangedArgs((ListView) sender, viewItem)); is not happening.

**Comment by expand** [comment]
eXpand.lab release [19.2.300.11](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.300.11) includes commit that relate to this task:

* [DashboardInteraction: Fails if same view DashboardViewItem #477 #603](https://github.com/eXpandFramework/eXpand.lab/commit/940f1aef179d87f7e3bdfdd8ef1911613d63ed58)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by capricciobob** [comment]
[Xpand] The V2 feed at 'https://xpandnugetserver.azurewebsites.net/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='net461'&includePrerelease=false&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '404 Not Found'.

**Comment by capricciobob** [comment]
Problem updating from the lab in Visual Studio.

  GET https://xpandnugetserver.azurewebsites.net/nuget/Packages(Id='eXpandImportWizard',Version='19.2.300.14')
  GET https://api.nuget.org/v3/registration4-gz-semver2/expandimportwizard/index.json
  GET https://xpandnugetserver.azurewebsites.net/Packages(Id='eXpandImportWizard',Version='19.2.300.14')
  OK https://xpandnugetserver.azurewebsites.net/nuget/Packages(Id='eXpandImportWizard',Version='19.2.300.14') 215ms
  NotFound https://xpandnugetserver.azurewebsites.net/Packages(Id='eXpandImportWizard',Version='19.2.300.14') 306ms
  OK https://api.nuget.org/v3/registration4-gz-semver2/expandimportwizard/index.json 346ms
  GET https://xpandnugetserver.azurewebsites.net/FindPackagesById()?id='eXpandImportWizard'&semVerLevel=2.0.0
Resolved actions to install package 'eXpandImportWizard.19.2.300.14'
Failed to fetch results from V2 feed at 'https://xpandnugetserver.azurewebsites.net/FindPackagesById()?id='eXpandImportWizard'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 404 (Not Found).
  Response status code does not indicate success: 404 (Not Found).
Time Elapsed: 00:00:00.6910226
========== Finished ==========

**Comment by capricciobob** [comment]
It looks like the /nuget is missing somewhere in the references.

**Comment by capricciobob** [comment]
It was on my end. I have the package now and will try the fix.

**Comment by capricciobob** [comment]
Okay, when I click an item in the first list it throws this error.

Object reference not set to an instance of an object.

   at Xpand.Persistent.Base.General.Controllers.Dashboard.DashboardInteractionController.CriteriaSelectionOperator(ListView listView, IModelColumn filteredColumn) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\Controllers\Dashboard\DashboardInteraction.cs:line 170
   at Xpand.Persistent.Base.General.Controllers.Dashboard.DashboardInteractionController.FilteredListView(ListView listView, DashboardViewItem dashboardViewItem, IModelDashboardViewItemEx modelDashboardViewItemFiltered) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\Controllers\Dashboard\DashboardInteraction.cs:line 164
   at Xpand.Persistent.Base.General.Controllers.Dashboard.DashboardInteractionController.OnSelectionChanged(SelectionChangedArgs selectionChangedArgs) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\Controllers\Dashboard\DashboardInteraction.cs:line 120
   at Xpand.Persistent.Base.General.Controllers.Dashboard.DashboardInteractionController.ListViewSelectionChangedHandler(Object sender, EventArgs e) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\Controllers\Dashboard\DashboardInteraction.cs:line 76
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at DevExpress.ExpressApp.View.OnSelectionChanged()
   at DevExpress.ExpressApp.ListView.listEditor_SelectionChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at DevExpress.ExpressApp.Editors.ListEditor.RaiseSelectionChanged()
   at DevExpress.ExpressApp.Win.Editors.WinColumnsListEditor.OnSelectionChanged()
   at DevExpress.ExpressApp.Win.Editors.WinColumnsListEditor.view_FocusedRowObjectChanged(Object sender, FocusedRowObjectChangedEventArgs e)
   at DevExpress.XtraGrid.Views.Base.ColumnView.RaiseFocusedRowObjectChanged(FocusedRowObjectChangedEventArgs e)
   at DevExpress.XtraGrid.Views.Base.ColumnView.OnCurrentControllerRowObjectChanged(CurrentRowChangedEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.GridView.OnCurrentControllerRowObjectChanged(CurrentRowChangedEventArgs e)
   at DevExpress.XtraGrid.Views.Base.ColumnView.DevExpress.Data.IDataControllerCurrentSupport.OnCurrentControllerRowObjectChanged(CurrentRowChangedEventArgs e)
   at DevExpress.Data.BaseGridController.OnCurrentControllerRowObjectChanging(Object oldObject, Object newObject, Int32 level, Int32 sourceIndex)
   at DevExpress.Data.BaseGridController.SetCurrentControllerRowObject(Object value, Int32 level, Int32 sourceIndex)
   at DevExpress.Data.BaseGridController.CheckCurrentControllerRowObject(ListChangedEventArgs e)
   at DevExpress.Data.BaseGridController.OnCurrentControllerRowChanged()
   at DevExpress.Data.BaseGridController.OnCurrentControllerRowChanging(Int32 oldControllerRow, Int32 newControllerRow)
   at DevExpress.Data.BaseGridController.set_CurrentControllerRow(Int32 value)
   at DevExpress.XtraGrid.Views.Grid.GridView.DoChangeFocusedRow(Int32 currentRowHandle, Int32 newRowHandle, Boolean raiseUpdateCurrentRow)
   at DevExpress.XtraGrid.Views.Base.ColumnView.DoChangeFocusedRowInternal(Int32 newRowHandle, Boolean updateCurrentRow)
   at DevExpress.XtraGrid.Views.Base.ColumnView.set_FocusedRowHandle(Int32 value)
   at DevExpress.XtraGrid.Views.Grid.Handler.GridRegularRowNavigator.OnMouseDown(GridHitInfo hitInfo, DXMouseEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.Handler.GridHandler.OnMouseDown(MouseEventArgs ev)
   at DevExpress.Utils.Controls.BaseHandler.ProcessEvent(EventType etype, Object args)
   at DevExpress.XtraGrid.Views.Base.Handler.BaseViewHandler.ProcessEvent(EventType etype, Object args)
   at DevExpress.XtraGrid.GridControl.OnMouseDown(MouseEventArgs ev)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   at DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)vvv

**Comment by expand** [comment]
eXpand.lab release [19.2.300.15](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.300.15) includes commit that relate to this task:

* [Dashboard: Cascading ListView Filtering throws #603](https://github.com/eXpandFramework/eXpand.lab/commit/28d33cc240154bd6d0eff7076072ab964113a12c)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by capricciobob** [comment]
Installed 19.2.301.1 to test the fix, but ran into this issue. Cannot get past login to verify this bug.

https://github.com/eXpandFramework/eXpand/issues/619

**Comment by capricciobob** [comment]
Testing complete. This appears to be working in the lab. Thanks!
