### ISSUE TITLE
ILogicRule GetView Missing

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#619]
After upgrading to 19.2.301 to fix another issue, when I login to the client I get the following error. The web is fine.

Method not found: 'DevExpress.ExpressApp.Model.IModelView Xpand.Persistent.Base.Logic.ILogicRule.get_View()'.

Stack Trace:
   at DevExpress.ExpressApp.XafApplication.CheckCompatibilityCore()
   at DevExpress.ExpressApp.Win.WinApplication.CheckCompatibilityCore()
   at DevExpress.ExpressApp.XafApplication.CheckCompatibility()
   at DevExpress.ExpressApp.XafApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
   at DevExpress.ExpressApp.Win.WinApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)

**Comment by apobekiaris** [comment]
ru on the latest lab? Can you run an empty XAF solution where you installed the ModelArtifactState module?

**Comment by capricciobob** [comment]
ModelArtifactState module was missing from my module. I really only want ViewVariants and ModelDifference, but those seems seem to need a ton of other dlls. ;(
