### ISSUE TITLE
How to create disabled model store and load it in code

### ISSUE THREAD

**Issue by sam105kelly** [eXpandFramework/eXpand#667]
i am using the sample code from 
[http://apobekiaris.blogspot.com/search/label/ModelDifference](url)
my goal is to use these snippets 

` public class Updater : ModuleUpdater {

        public Updater(Session session, Version currentDBVersion) : base(session, currentDBVersion) { }

        public override void UpdateDatabaseAfterUpdateSchema() {

            base.UpdateDatabaseAfterUpdateSchema();

            CreateDisabledModelDifferenceObject(typeof(ManagerModelStore));

            CreateDisabledModelDifferenceObject(typeof(ReceptionistModelStore));

        }

 

        void CreateDisabledModelDifferenceObject(Type storeBaseType) {

            var modelDifferenceObject = Session.FindObject<ModelDifferenceObject>(o => o.Name == storeBaseType.Name);

            if (modelDifferenceObject == null) {

                ModelDifferenceObject differenceObject = new ModelDifferenceObject(Session).InitializeMembers(storeBaseType.Name);

                var layer = new ModelApplicationBuilder(differenceObject.PersistentApplication.ExecutableName).GetLayer(storeBaseType);

                differenceObject.CreateAspects(layer);

                differenceObject.Disabled = true;

                differenceObject.Save();

            }

        }

    }`
and

`  modelApplicationLoader.EnableModel(o => o.Name == "ReceptionistModelStore", new[] { "ManagerModelStore" });`

to switch models at runtime

please update the sample to work on the current version of expand

**Additional context**

**Comment by sam105kelly** [comment]
What I am after is the exact sample on `http://apobekiaris.blogspot.com/search/label/ModelDifference`
to work on version 19.2.5

**Comment by sam105kelly** [comment]
looking at 
`void CreateDisabledModelDifferenceObject(Type storeBaseType) {

            var modelDifferenceObject = Session.FindObject<ModelDifferenceObject>(o => o.Name == storeBaseType.Name);

            if (modelDifferenceObject == null) {

                ModelDifferenceObject differenceObject = new ModelDifferenceObject(Session).InitializeMembers(storeBaseType.Name);

                var layer = new ModelApplicationBuilder(differenceObject.PersistentApplication.ExecutableName).GetLayer(storeBaseType);

                differenceObject.CreateAspects(layer);

                differenceObject.Disabled = true;

                differenceObject.Save();

            }`
the line `ModelApplicationBuilder(differenceObject.PersistentApplication.ExecutableName).GetLayer(storeBaseType);` does not compile

**Comment by apobekiaris** [comment]
did u try to replace the Session with ObjectSpace and lose the line

**Comment by apobekiaris** [comment]
lose also the CreateAspects line

**Comment by apobekiaris** [comment]
and the Save -> ObjectSpace.CommitChanges()

this blog is really old XAF has changed a lot since then so eXpand

**Comment by apobekiaris** [comment]
RDO is just a persistent object treat line one

**Comment by apobekiaris** [comment]
use the RDO XmlContent property to store initial your model diffs if any

**Comment by sam105kelly** [comment]
Thanks alot

**Comment by sam105kelly** [comment]
[Solution3.Module.zip](https://github.com/eXpandFramework/eXpand/files/4117707/Solution3.Module.zip)

In the sample the model does not show up in the listview.I dont know why

Also there is another issue with RDO_Users_RoleDifference.xafml
if you log in as Admin it works file 
the logout and login as user it works fine too

exit and start and login as 'user'
gives an eror

**Comment by sam105kelly** [comment]
Value cannot be null.
Parameter name: Users

   at Xpand.ExpressApp.ModelDifference.DictionaryStores.ResourcesLayerBuilder.CreateDifferenceObject(String resourceName, String prefix) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ModelDifference\DictionaryStores\ResourcesLayerBuilder.cs:line 51
   at Xpand.ExpressApp.ModelDifference.DictionaryStores.ResourcesLayerBuilder.GetModelDifferenceObjectInfo(String prefix, Dictionary`2 loadedModelDifferenceObjectInfos, String resourceName, ModelApplicationBase model) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ModelDifference\DictionaryStores\ResourcesLayerBuilder.cs:line 74
   at Xpand.ExpressApp.ModelDifference.DictionaryStores.ResourcesLayerBuilder.AddLayers(String modelApplicationPrefix, Dictionary`2 loadedModelDifferenceObjectInfos, ModelApplicationBase model) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ModelDifference\DictionaryStores\ResourcesLayerBuilder.cs:line 34
   at Xpand.ExpressApp.ModelDifference.DictionaryStores.XpoModelDictionaryDifferenceStore.CreateResourceRoleModels(ResourcesLayerBuilder resourcesLayerBuilder, Dictionary`2 loadedModelDifferenceObjectInfos, ModelApplicationBase model) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ModelDifference\DictionaryStores\XpoModelDictionaryDifferenceStore.cs:line 155
   at Xpand.ExpressApp.ModelDifference.DictionaryStores.XpoModelDictionaryDifferenceStore.CreateResourceModels(ModelApplicationBase model, Dictionary`2 loadedModelDifferenceObjectInfos) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ModelDifference\DictionaryStores\XpoModelDictionaryDifferenceStore.cs:line 148
   at Xpand.ExpressApp.ModelDifference.DictionaryStores.XpoModelDictionaryDifferenceStore.Load(ModelApplicationBase model) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ModelDifference\DictionaryStores\XpoModelDictionaryDifferenceStore.cs:line 55
   at Xpand.ExpressApp.ModelDifference.ModelDifferenceModule.LoadApplicationModels(ModelApplicationBase model) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ModelDifference\Module.cs:line 223
   at Xpand.ExpressApp.ModelDifference.ModelDifferenceModule.LoadModels() in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ModelDifference\Module.cs:line 206
   at Xpand.ExpressApp.ModelDifference.ModelDifferenceModule.OnUserDifferencesLoaded(Object sender, EventArgs eventArgs) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ModelDifference\Module.cs:line 201
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at DevExpress.ExpressApp.XafApplication.LoadUserDifferences()
   at DevExpress.ExpressApp.XafApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)
   at DevExpress.ExpressApp.Win.WinApplication.Logon(PopupWindowShowActionExecuteEventArgs logonWindowArgs)

**Comment by sam105kelly** [comment]
it only occurs if you login fist time as user

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.
1. [❤ Sponsor Bronze](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor%20Bronze)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by sam105kelly** [comment]
Is there a workaround

**Comment by sam105kelly** [comment]
Is there a workaround you can suggest.

**Comment by apobekiaris** [comment]
the bot already informed u how the cases are prioritized, and this is prioritized for research as it contains a sample. However it is on number 9 where there are many cases before it.

http://priorityissues.expandframework.com/

double posting won't help. Thanks for the understanding

**Comment by apobekiaris** [comment]
I have now research this case below my results.

1. I do not recommend u use embedded RDO_RoleName_SomeName models they were design for devlopment purposes and not for production
2. The exception u get is saying that the User u try to login cannot find the Role Users and this means that does not have permissions
3. I modified your updater like to demo how u can create a role model from code
```cs
        void CreateDisabledModelDifferenceObject(string storeBaseType, ISecurityRole usersRole)
        {
            var modelDifferenceObject = ObjectSpace.FindObject<RoleModelDifferenceObject>(new BinaryOperator("Name", storeBaseType));
            if (modelDifferenceObject == null)
            {
                modelDifferenceObject = ObjectSpace.Create<RoleModelDifferenceObject>();
                modelDifferenceObject.InitializeMembers(storeBaseType, ApplicationHelper.Instance.Application, Xpand.Persistent.Base.ModelDifference.DeviceCategory.All);
                modelDifferenceObject.Name = storeBaseType;
                using (var streamReader = new StreamReader(GetType().Assembly.GetManifestResourceStream(typeof(Solution3Module), "RDO_Users_RoleDifference.xafml"))){
                    modelDifferenceObject.XmlContent = streamReader.ReadToEnd();
                }

                ((XPBaseCollection) modelDifferenceObject.GetMemberValue("Roles")).BaseAdd(usersRole);
                modelDifferenceObject.Disabled = true;
                modelDifferenceObject.Save();

            }
        }
```
4. all Models are visible in my side even the "BursarModel"
5. Again you need to focus on your permissions these MDO,RDO,UDo are persistent objects and they need permissions. The module provides a default Role you can use.
https://github.com/eXpandFramework/eXpand/blob/ba6c9bf4c293cac8478ad291ca5430c554a7e658/Xpand/Xpand.ExpressApp.Modules/ModelDifference/Security/Extensions.cs#L19-L37

**Comment by expand** [comment]
Issue is `deprioritized` as `no Assignee found` and scheduled for `auto-close` if no activity in the next `60 days`. Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
