### ISSUE TITLE
Can't open win model editor in 19.2.601.0 (using model difference module option)

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#669]
The error occurred:
[Solution2.zip](https://github.com/eXpandFramework/eXpand/files/4149537/Solution2.zip)

	Type:       IndexOutOfRangeException
	Message:    Index was outside the bounds of the array.
	Data:       0 entries
	Stack trace:

   at invoke(Object , Object[] )
   at Fasterflect.MethodInfoExtensions.Call(MethodInfo methodInfo, Object obj, Object[] parameters)
   at Xpand.Persistent.Base.ModelAdapter.InterfaceBuilder.set_SkipAssemblyCleanup(Boolean value)
   at Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.GetMasterModelCore(Boolean recreate)
   at Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.GetMasterModel(Boolean recreate)
   at Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.OnCurrentObjectChanged()
   at DevExpress.ExpressApp.Editors.ViewItem.set_CurrentObject(Object value)
   at DevExpress.ExpressApp.ObjectView.InitializeItem(ViewItem item)
   at DevExpress.ExpressApp.DetailView.InitializeItem(ViewItem item)
   at DevExpress.ExpressApp.CompositeView.AddItem(ViewItem item)
   at DevExpress.ExpressApp.CompositeView.LoadModelCore()
   at DevExpress.ExpressApp.ObjectView.LoadModelCore()
   at DevExpress.ExpressApp.View.LoadModel()
   at DevExpress.ExpressApp.View.SetModel(IModelView model)
   at Xpand.ExpressApp.ViewFactory.CreateDetailView(XafApplication xafApplication, String viewId, IObjectSpace objectSpace, Object obj, Boolean isRoot, Boolean enableDelayedObjectLoading)
   at Xpand.ExpressApp.SystemModule.XpandSystemModule.ApplicationOnDetailViewCreating(Object sender, DetailViewCreatingEventArgs args)
   at DevExpress.ExpressApp.XafApplication.OnDetailViewCreating(DetailViewCreatingEventArgs args)
   at DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj, Boolean isDelayedObjectLoading, IEnumerable objectsToPrefetch)
   at DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj)
   at DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.ShowObjectCore(Object obj, ShowViewParameters showViewParameters, XafApplication application, View sourceView, IObjectSpace objectSpace, IEnumerable objectsToPrefetch)
   at DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.ProcessCurrentObject(SimpleActionExecuteEventArgs e)
   at DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.processCurrentObjectAction_OnExecute(Object sender, SimpleActionExecuteEventArgs e)
   at DevExpress.ExpressApp.Actions.SimpleActionExecuteEventHandler.Invoke(Object sender, SimpleActionExecuteEventArgs e)
   at DevExpress.ExpressApp.Actions.SimpleAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	InnerException is null

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order. For all other issues the posting time is respected.
1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by rSeeFip** [comment]
after upgrading from 19.2.503 to 19.2.601 the same issue by opening model out from application settings

Der Index war außerhalb des Arraybereichs.

   bei invoke(Object , Object[] )
   bei Xpand.Persistent.Base.ModelAdapter.InterfaceBuilder.set_SkipAssemblyCleanup(Boolean value)
   bei Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.GetMasterModelCore(Boolean recreate)
   bei Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.GetMasterModel(Boolean recreate)
   bei Xpand.ExpressApp.ModelDifference.Win.PropertyEditors.ModelEditorPropertyEditor.OnCurrentObjectChanged()
   bei DevExpress.ExpressApp.Editors.ViewItem.set_CurrentObject(Object value)
   bei DevExpress.ExpressApp.ObjectView.InitializeItem(ViewItem item)
   bei DevExpress.ExpressApp.CompositeView.AddItem(ViewItem item)
   bei DevExpress.ExpressApp.CompositeView.LoadModelCore()
   bei DevExpress.ExpressApp.View.LoadModel()
   bei DevExpress.ExpressApp.View.SetModel(IModelView model)
   bei Xpand.ExpressApp.ViewFactory.CreateDetailView(XafApplication xafApplication, String viewId, IObjectSpace objectSpace, Object obj, Boolean isRoot, Boolean enableDelayedObjectLoading)
   bei Xpand.ExpressApp.SystemModule.XpandSystemModule.ApplicationOnDetailViewCreating(Object sender, DetailViewCreatingEventArgs args)
   bei DevExpress.ExpressApp.XafApplication.OnDetailViewCreating(DetailViewCreatingEventArgs args)
   bei DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj, Boolean isDelayedObjectLoading, IEnumerable objectsToPrefetch)
   bei DevExpress.ExpressApp.XafApplication.CreateDetailView(IObjectSpace objectSpace, String detailViewID, Boolean isRoot, Object obj)
   bei DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.ShowObjectCore(Object obj, ShowViewParameters showViewParameters, XafApplication application, View sourceView, IObjectSpace objectSpace, IEnumerable objectsToPrefetch)
   bei DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.ProcessCurrentObject(SimpleActionExecuteEventArgs e)
   bei DevExpress.ExpressApp.SystemModule.ListViewProcessCurrentObjectController.processCurrentObjectAction_OnExecute(Object sender, SimpleActionExecuteEventArgs e)
   bei DevExpress.ExpressApp.Actions.SimpleActionExecuteEventHandler.Invoke(Object sender, SimpleActionExecuteEventArgs e)
   bei DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**Comment by vimarx** [comment]
@apobekiaris any chance to workaround/solve this before next week?

**Comment by apobekiaris** [comment]
thnks for the reminder, hopefully we will have a build during weeend. Is high priority and already delayed.

**Comment by expand** [comment]
eXpand.lab release [19.2.601.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.601.1) includes commit that relate to this task:

* [ModelEditor fails when ModelMapper is used #669](https://github.com/eXpandFramework/eXpand.lab/commit/b35ec12dbd191806a2e7474d3561e66d400bbdd5)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by vimarx** [comment]
Hi, Now in 19.2.601.1 the model editor opens and works fine, but AFTER closing it, it raises this exception

13.02.20 17:01:46.328	Window closed: Gestion de Mutuales/Financieras - Application Settings
13.02.20 17:01:46.810	================================================================================
The error occurred:

	Type:       NullReferenceException
	Message:    Object reference not set to an instance of an object.
	Data:       0 entries
	Stack trace:

   at DevExpress.ExpressApp.Win.Templates.XtraFormTemplateBase.get_View()
   at DevExpress.ExpressApp.Office.Win.OfficeDocumentManagerController.CheckOfficePropertyEditors(IViewHolder viewHolder)
   at DevExpress.ExpressApp.Office.Win.OfficeDocumentManagerController.View_DocumentDeactivated(Object sender, DocumentEventArgs e)
   at DevExpress.XtraBars.Docking2010.Views.DocumentEventHandler.Invoke(Object sender, DocumentEventArgs e)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.RaiseDocumentDeactivated(BaseDocument document)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.OnDocumentDeactivated(BaseDocument document)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.SetActiveDocumentCore(BaseDocument document)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.ActivateDocument(Control control)
   at DevExpress.XtraBars.Docking2010.MDIClientManagementStrategy.OnMdiChildActivate(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnMdiChildActivate(EventArgs e)
   at DevExpress.XtraEditors.XtraForm.OnMdiChildActivate(EventArgs e)
   at System.Windows.Forms.Form.WmMdiActivate(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
	InnerException is null

================================================================================
13.02.20 17:01:49.059	================================================================================
The error occurred:

	Type:       NullReferenceException
	Message:    Object reference not set to an instance of an object.
	Data:       0 entries
	Stack trace:

   at DevExpress.ExpressApp.Win.Templates.XtraFormTemplateBase.get_View()
   at DevExpress.ExpressApp.Office.Win.OfficeDocumentManagerController.CheckOfficePropertyEditors(IViewHolder viewHolder)
   at DevExpress.ExpressApp.Office.Win.OfficeDocumentManagerController.View_DocumentDeactivated(Object sender, DocumentEventArgs e)
   at DevExpress.XtraBars.Docking2010.Views.DocumentEventHandler.Invoke(Object sender, DocumentEventArgs e)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.RaiseDocumentDeactivated(BaseDocument document)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.OnDocumentDeactivated(BaseDocument document)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.SetActiveDocumentCore(BaseDocument document)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.CheckActiveDocument(CollectionChangedEventArgs`1 ea)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.OnDocumentCollectionChanged(CollectionChangedEventArgs`1 ea)
   at DevExpress.XtraBars.Docking2010.Base.CollectionChangedHandler`1.Invoke(CollectionChangedEventArgs`1 ea)
   at DevExpress.XtraBars.Docking2010.Base.BaseMutableList`1.RaiseCollectionChanged(CollectionChangedEventArgs`1 ea)
   at DevExpress.XtraBars.Docking2010.Base.BaseMutableListEx`1.OnElementRemoved(T element)
   at DevExpress.XtraBars.Docking2010.Views.BaseDocumentCollection.OnElementRemoved(BaseDocument element)
   at DevExpress.XtraBars.Docking2010.Base.BaseMutableList`1.Remove(T element)
   at DevExpress.XtraBars.Docking2010.Views.BaseViewController.RemoveDocumentFromView(BaseDocument document)
   at DevExpress.XtraBars.Docking2010.Views.BaseViewController.RemoveDocument(Control control)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.RemoveDocument(Control control)
   at DevExpress.XtraBars.Docking2010.DocumentManager.OnControlRemoved(Control control)
   at System.Windows.Forms.Control.OnControlRemoved(ControlEventArgs e)
   at System.Windows.Forms.Control.ControlCollection.Remove(Control value)
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.Windows.Forms.Form.Dispose(Boolean disposing)
   at DevExpress.XtraEditors.XtraForm.Dispose(Boolean disposing)
   at DevExpress.ExpressApp.Win.Templates.XtraFormTemplateBase.Dispose(Boolean disposing)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at DevExpress.ExpressApp.Win.Templates.XtraFormTemplateBase.WndProc(Message& msg)
	InnerException is null

================================================================================
13.02.20 17:01:49.082	================================================================================
The error occurred:

	Type:       NullReferenceException
	Message:    Object reference not set to an instance of an object.
	Data:       0 entries
	Stack trace:

   at DevExpress.ExpressApp.Win.Templates.XtraFormTemplateBase.get_View()
   at DevExpress.ExpressApp.Office.Win.OfficeDocumentManagerController.CheckOfficePropertyEditors(IViewHolder viewHolder)
   at DevExpress.ExpressApp.Office.Win.OfficeDocumentManagerController.View_DocumentDeactivated(Object sender, DocumentEventArgs e)
   at DevExpress.XtraBars.Docking2010.Views.DocumentEventHandler.Invoke(Object sender, DocumentEventArgs e)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.RaiseDocumentDeactivated(BaseDocument document)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.OnDocumentDeactivated(BaseDocument document)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.SetActiveDocumentCore(BaseDocument document)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.CheckActiveDocument(CollectionChangedEventArgs`1 ea)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.OnDocumentCollectionChanged(CollectionChangedEventArgs`1 ea)
   at DevExpress.XtraBars.Docking2010.Base.CollectionChangedHandler`1.Invoke(CollectionChangedEventArgs`1 ea)
   at DevExpress.XtraBars.Docking2010.Base.BaseMutableList`1.RaiseCollectionChanged(CollectionChangedEventArgs`1 ea)
   at DevExpress.XtraBars.Docking2010.Base.BaseMutableListEx`1.OnElementRemoved(T element)
   at DevExpress.XtraBars.Docking2010.Views.BaseDocumentCollection.OnElementRemoved(BaseDocument element)
   at DevExpress.XtraBars.Docking2010.Base.BaseMutableList`1.Remove(T element)
   at DevExpress.XtraBars.Docking2010.Views.BaseViewController.RemoveDocumentFromView(BaseDocument document)
   at DevExpress.XtraBars.Docking2010.Views.BaseViewController.RemoveDocument(Control control)
   at DevExpress.XtraBars.Docking2010.Views.BaseView.RemoveDocument(Control control)
   at DevExpress.XtraBars.Docking2010.DocumentManager.OnControlRemoved(Control control)
   at System.Windows.Forms.Control.OnControlRemoved(ControlEventArgs e)
   at System.Windows.Forms.Control.ControlCollection.Remove(Control value)
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.Windows.Forms.Form.Dispose(Boolean disposing)
   at DevExpress.XtraEditors.XtraForm.Dispose(Boolean disposing)
   at DevExpress.ExpressApp.Win.Templates.XtraFormTemplateBase.Dispose(Boolean disposing)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at DevExpress.ExpressApp.Win.Templates.XtraFormTemplateBase.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
	InnerException is null

================================================================================
13.02.20 17:01:50.551	Action 'SaveAndClose' done

**Comment by apobekiaris** [comment]
do u use the same sample? I failed to repro it. What I tried is open the MDO, modified and then SaveAndClose. Please provide exact repro steps or a screencast may also be in help

**Comment by vimarx** [comment]
Hi, attached sample and screencast.
Please enable IsDelayedDetailviewDataloading in program.cs
![image](https://user-images.githubusercontent.com/226800/74605982-7b827b80-50ab-11ea-86f5-c576452b97d5.png)

[Solution9.zip](https://github.com/eXpandFramework/eXpand/files/4209810/Solution9.zip)
[delayeddetailview.zip](https://github.com/eXpandFramework/eXpand/files/4209811/delayeddetailview.zip)

**Comment by vimarx** [comment]
IsDelayedDetailviewDataloading was disabled by mistake in solution9.zip, enable it and try

**Comment by vimarx** [comment]
Hi, anyone had a success editing web model in win app?
I'm stuck with #674

**Comment by vimarx** [comment]
Hi, using 19.2.601.5 you can see in the attached log, that both model adapters are loaded twice 
![image](https://user-images.githubusercontent.com/226800/74764710-f9d44e80-5260-11ea-9714-839df32bab5f.png)

and here is the repro screencast 
![trytoeditmodel](https://user-images.githubusercontent.com/226800/74764751-0c4e8800-5261-11ea-8283-8cea274ab0bc.gif)

and the complete log
[eXpressAppFramework.zip](https://github.com/eXpandFramework/eXpand/files/4220900/eXpressAppFramework.zip)

**Comment by vimarx** [comment]
btw, the modeladapter....dll is still created  in the web path, not in web\bin

**Comment by apobekiaris** [comment]
yes i see there is a version problem standalone packages are not upgraded in the release u tested. Pushing a new one.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [Build: Xpand.XAF.All packages versions not getting increased #669](https://github.com/eXpandFramework/DevExpress.XAF/commit/4c1c3591946aa96308b66343dcb6a617655d334f)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the [Xpand.XAF.Modules](https://github.com/eXpandFramework/DevExpress.XAF) directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.2.601.6](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.601.6) includes commit that relate to this task:

* [ModelDifference: Disable DelayedObjectLoading for views thats use the ModelEditorPropertyEditor #669](https://github.com/eXpandFramework/eXpand.lab/commit/06a174b426bd68fffa534b09073c6bfd08b6dceb)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
i tested 19.2.601.7 and assemblies are not in GAC anymore

**Comment by expand** [comment]
Issue is `deprioritized` as `no Assignee found` and scheduled for `auto-close` if no activity in the next `60 days`. Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.2.602.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.602.4) includes commit that relate to this task:

* [ModelDifference: ModelApplicationCreator creates multiple models throwing CannotCreateModelNodeByTypeException #669 #674 #681](https://github.com/eXpandFramework/eXpand.lab/commit/59abc383a7cab15d00306afe8a4e20cc58a299bc)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
