### ISSUE TITLE
XpandNavigationItem throws odd error on incorrect view name

### ISSUE THREAD

**Issue by DSCmattb** [eXpandFramework/eXpand#672]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
Setting an Incorrect view name in XPandNavigationItem throws the following exception

`Operation could destabilize the runtime.

   at CreateWindow_Patch1(XafApplication context, TemplateContext controllers, ICollection`1 createAllControllers, Boolean isMain, Boolean view, View )
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.CreateWindow(ShowViewParameters parameters, ShowViewSource showViewSource, Boolean isMain)
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.ShowStartupWindowCore()
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowStartupWindowCore()
   at DevExpress.ExpressApp.Win.WinApplication.ShowStartupWindow()
   at DevExpress.ExpressApp.Win.WinApplication.DoStartupLogic(IOverlaySplashScreenHandle overlayFormHandle)
   at DevExpress.ExpressApp.Win.WinApplication.Start()`

𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
Create a basic object, for example Reminder and then add the XpandNavigationItem attribute to the class and set the name of the view to Reminders_ListView which is obviously not the name of the view as it is not plural.
𝗘𝘅𝗽𝗲𝗰𝘁𝗲𝗱 𝗯𝗲𝗵𝗮𝘃𝗶𝗼𝗿
Throw a clearly defined error so that the programmer is not confused and spends hours trying to find the error in the code. This error is pretty generic on google as well so it doesn't help.

**Comment by apobekiaris** [comment]
check out this

https://github.com/eXpandFramework/eXpand/issues/513#issuecomment-523386924

which implies that the problem might be somewhere else. A repro sample therefore is mandatory for further research.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
