### ISSUE TITLE
Exception on starting up XAF application ported to .NET core

### ISSUE THREAD

**Issue by neuropseudolonicher** [eXpandFramework/eXpand#673]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
After porting an  existing XAF application from source framework 4.7.2 to .NET Core 3.1,
the ported application throws an exception with the following details:

System.TypeInitializationException
  HResult=0x80131534
  Message = The type initializer for 'myApp.Win.myAppWindowsFormsApplication' threw an exception.
  Source = myApp.Win
  Stack trace:
   at myApp.Win.myAppWindowsFormsApplication..ctor() in C:\Users\me\source\repos\myApp_Lab\myApp.Win\WinApplication.vb:line 45
   at myApp.Win.Program.Main(String[] arguments) in C:\Users\me\source\repos\myApp_Lab\myApp.Win\Program.vb:line 33

Inner Exception 1:
TypeInitializationException: The type initializer for 'Xpand.Persistent.Base.General.XpandModuleBase' threw an exception.

Inner Exception 2:
MissingMethodException: Method not found: 'System.String System.AppDomainSetup.get_PrivateBinPath()'.

Thus, the application is not starting up at all.

𝗘𝘅𝗽𝗲𝗰𝘁𝗲𝗱 𝗯𝗲𝗵𝗮𝘃𝗶𝗼𝗿
XAF application to start up without the exception.

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order. For all other issues the posting time is respected.
1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by expand** [comment]
eXpand.lab release [19.2.601.2](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.601.2) includes commit that relate to this task:

* [Use appdomain.basedirectory when PrivateBinPath not exists #673](https://github.com/eXpandFramework/eXpand.lab/commit/05363ddd8c3000430aaa36d3775717e97de36755)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Issue is `deprioritized` as `no Assignee found` and scheduled for `auto-close` if no activity in the next `60 days`.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
