### ISSUE TITLE
Class with Pessimistic Locking, Detail View Save

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#675]
Hi,

I have a Class with the pessimisticlockig attribute. If I create a new Dataobject it works fine but if I try to edit the dataobject I get an error. How to edit/save such an object?

The class:
    [PessimisticLocking]
    [Custom("ViewEditMode", "View")]
   public partial class AccountingVoucherNumber : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        Mandatory fMandatory;
        [DevExpress.Persistent.Validation.RuleRequiredField(DevExpress.Persistent.Validation.DefaultContexts.Save)]
        public Mandatory Mandatory
        {
            get { return fMandatory; }
            set { SetPropertyValue<Mandatory>("Mandatory", ref fMandatory, value); }
        }
        AccountingPeriod fAccountingPeriod;
        [Association(@"AccountingVoucherNumberReferencesAccountingPeriod")]
        [DevExpress.Persistent.Validation.RuleRequiredField(DevExpress.Persistent.Validation.DefaultContexts.Save)]
        public AccountingPeriod AccountingPeriod
        {
            get { return fAccountingPeriod; }
            set { SetPropertyValue<AccountingPeriod>("AccountingPeriod", ref fAccountingPeriod, value); }
        }
        AccountingSection fAccountingSection;
        [Association(@"AccountingVoucherNumberReferencesAccountingSection")]
        [DevExpress.Persistent.Validation.RuleRequiredField(DevExpress.Persistent.Validation.DefaultContexts.Save)]
        public AccountingSection AccountingSection
        {
            get { return fAccountingSection; }
            set { SetPropertyValue<AccountingSection>("AccountingSection", ref fAccountingSection, value); }
        }
        int fNextNumber;
        [ColumnDefaultValue(1)]
        public int NextNumber
        {
            get { return fNextNumber; }
            set { SetPropertyValue<int>("NextNumber", ref fNextNumber, value); }
        }
		
		public AccountingVoucherNumber(Session session) : base(session) { }
        public override void AfterConstruction() { base.AfterConstruction(); }

    }

The Error when editing the name and click the save button:
Key cannot be null.
Parameter name: key

   at System.Collections.Specialized.ListDictionary.get_Item(Object key)
   at System.Collections.Specialized.HybridDictionary.get_Item(Object key)
   at System.ComponentModel.PropertyDescriptorCollection.Find(String name, Boolean ignoreCase)
   at DevExpress.ExpressApp.Xpo.DataLockingHelper.CollectObjectLockingInfo(Session session, XPClassInfo classInfo, List`1 objectToSaveKeys, UInt16 hostParametersMaxNumber)
   at DevExpress.ExpressApp.Xpo.DataLockingHelper.GetDataLockingInfo(Session session, UInt16 hostParametersMaxNumber)
   at DevExpress.ExpressApp.Xpo.XPObjectSpace.DevExpress.ExpressApp.IDataLockingManager.GetDataLockingInfo()
   at DevExpress.ExpressApp.SystemModule.ProcessDataLockingInfoController.GetDataLockingInfo()
   at DevExpress.ExpressApp.SystemModule.ProcessDataLockingInfoController.action_Executing(Object sender, CancelEventArgs e)
   at System.ComponentModel.CancelEventHandler.Invoke(Object sender, CancelEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.OnExecuting(CancelEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order. For all other issues the posting time is respected.
1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by apobekiaris** [comment]
hmm i do not see how it relates to this framework, does it? the stacktrace you provided has no reference nor I recall a related feature. I can say my opinion but I am not the best to handle this case u should probably ask the xpo support guys.

the posible line that throws in the xaf code base is :

```cs
private static IEnumerable<ObjectLockingInfo> CollectObjectLockingInfo(Session session, XPClassInfo classInfo, List<Object> objectToSaveKeys, UInt16 hostParametersMaxNumber) {
	List<ObjectLockingInfo> result = new List<ObjectLockingInfo>();
	IEnumerable<ViewRecord> view = GetDataFromDataLayer(session, classInfo, objectToSaveKeys, hostParametersMaxNumber);
	foreach(ViewRecord record in view) {
		Object objectToSave = session.GetLoadedObjectByKey(classInfo, record[classInfo.KeyProperty.Name]);
		Boolean isLocked;
		if(classInfo.OptimisticLockingBehavior == OptimisticLockingBehavior.ConsiderOptimisticLockingField) {
			Object valueInSession = classInfo.OptimisticLockFieldInDataLayer.GetValue(objectToSave);
			//THROWS IN THE NEXT LINE
			Object valueInDataLayer = record[classInfo.OptimisticLockFieldName];  
			isLocked = !AreEqual(valueInDataLayer, valueInSession);
		}
		else {
			isLocked = IsLocked(session, classInfo, objectToSave, record);
		}
		if(isLocked) {
			IList<String> serverSideModifiedMemberNames = null;
			Boolean canMerge = CanMerge(session, classInfo, objectToSave, record, out serverSideModifiedMemberNames);
			result.Add(new ObjectLockingInfo(objectToSave, canMerge, serverSideModifiedMemberNames));
		}
	}
	return result;
}	
```

given this fact my focus would be some related IntermediateClassInfo that causes this effect. However cannot guess more if you want to debug it your self you can use the steps described at [1. Index the symbols to your custom DevExpresss installation location] (https://github.com/eXpandFramework/DevExpress.XAF/wiki/How-to-boost-your-DevExpress-Debugging-Experience#1-index-the-symbols-to-your-custom-devexpresss-installation-location)
to step in the XAF code and see what exactly is going on

hoev

**Comment by CWolffIF** [comment]
Hi Tolis,

I changed at the top to

[PessimisticLocking]
[Custom("ViewEditMode", "View")]
**[OptimisticLocking(false)]**

then no error occurs, only the merge Window, so that you can merge and save.
![Merge](https://user-images.githubusercontent.com/43132306/74593298-19cdfd00-502a-11ea-9154-eb981a771181.PNG)

**Comment by apobekiaris** [comment]
good work!

i now have a better picture the Xpand.Persistent.Base.General.Controllers.PessimisticLockingAttribute is an eXpandFramework attribute. Got confused apologies.

Looking a bit deeper I see there is a code to add the OptimisticLocking false

https://github.com/eXpandFramework/eXpand/blob/f916916dcf045b5317c48a8d7740fdc169f86fe4/Xpand/Xpand.ExpressApp/Xpand.ExpressApp/SystemModule/XpandSystemModule.cs#L96-L108

not clear though why it did not work

**Comment by expand** [comment]
Issue is `deprioritized` as `no Assignee found` and scheduled for `auto-close` if no activity in the next `60 days`.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
