### ISSUE TITLE
eXpand email module installation

### ISSUE THREAD

**Issue by scrawny-5** [eXpandFramework/eXpand#677]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
I would like to make use of the “eXpandEmail” module in order to send out emails when certain transactions happen on business objects (hopefully this is a valid use-case for that module). I have opted to install xpand via powershell (install-xpand) which seems to be the easiest option so far. I have managed to get this to work and now my Visual Studio has an Xpand menu (but no items in the toolbox). I have gone to nuget package manager and can see that the eXpandEmail module is also available from the various package sources. Is it sufficient to install that email module from there to my existing XAF Module project? I tried doing that and could build the project, but the module designer shows the following error:

`System.ComponentModel.Design.Serialization.CodeDomSerializerException: Could not find type 'Xpand.ExpressApp.Email.EmailModule'.  Please make sure that the assembly that contains this type is referenced.  If this type is a part of your development project, make sure that the project has been successfully built using settings for your current platform or Any CPU.
   at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.Error(IDesignerSerializationManager manager, String exceptionText, String helpLink)
   at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.DeserializeExpression(IDesignerSerializationManager manager, String name, CodeExpression expression)
   at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.DeserializeExpression(IDesignerSerializationManager manager, String name, CodeExpression expression)
   at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.DeserializeStatement(IDesignerSerializationManager manager, CodeStatement statement)`

I have tried adding the line RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Email.EmailModule)); to the designer source for the Module.Designer.cs file. I have also tried the same to the constructor (as per the read-me). But the issue remains. Project references do show the Xpand.ExpressApp.Email libraries. I am still on DevExpress 19.1.9 at the moment.  

What am I doing wrong?

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order. For all other issues the posting time is respected.
1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by apobekiaris** [comment]
do not use multiple installation sources, use either the powershell installer which will send assemblies to the GAC and will install the Xpand.VSIX which in his turn installs the toolbox and New Project templates, or use nugets which the do not have design-time support (toolbox and new project wizard.

to register any module e.g the email module prefer code than designer as it will save u from headaches.

the next line in your constructor of your platfrom agnostic module is all the registration u need.
e.g
```
RequiredModulesTypes.Add(typeOf(Xpand.ExpressApp.Email.EmailModule))
```

the above works with eiter source u chooce. Now if u use the installer there is also a wizard the can do that for u
![image](https://user-images.githubusercontent.com/159464/74620866-41fd4f00-5143-11ea-9f1d-cea872493bfd.png)

prefer running VS as admin to workaround various issues

**Comment by scrawny-5** [comment]
Thanks Apostolis. I will give this a try. Nuget + module registration at the code level sounds to be the easier way for me. I will uninstall the local Xpand installation.

Quick question: can this be added to an existing XAF module without any other modification (apart from constructor module registration)? As in, the XAF module was not generated from the eXpand Solution Wizard. It was done using DevExpress' XAF wizard. Does this matter?

PS. Agreed that VS as admin is the only way this works so far. We have strict security policies which have blocked all other attempts at getting this up and running (probably something to do with unsigned powershell scripts or similar).

**Comment by scrawny-5** [comment]
Ok, so after removing and re-adding the package via nuget, I seem to be getting an error when opening the designer for the Module.cs

**Comment by scrawny-5** [comment]
Should I install a previous version of the nuget package so that it is compatible with DX 19.1.9? 
It looks like the converter works though...? I ran the Xpand.VersionConverter.ps1 script on my project and it seems fine.
`All packages already patched for 19.1.9.0`

I'll try cleaning out the obj cache and rebuild.

**Comment by apobekiaris** [comment]
there are 2 kind of packages the standalone at http://xaf.expandframework.com/ and the main framework packages. Versionconverter is desgined to patch only the standalone which are used from the main framework.

so to answer your question u should go for a 19.1.9xx version as email module is not a standlone package

**Comment by scrawny-5** [comment]
Ah! So it looks like v. 19.1.701 is the highest that it goes. I'll give that a try.

**Comment by scrawny-5** [comment]
So it seems to build in the Module project builds now with that version, but the Web project designer is now showing a similar error:
`Could not load file or assembly 'DevExpress.ExpressApp.v19.1, Version=19.1.7.0, Culture=neutral,...`

I don't really want to downgrade to 19.1.7 if I can help it as it contains the issue that I raised with DX (T827697) whereby the mobile app fails to launch.

Any suggestions?

**Comment by apobekiaris** [comment]
get the source code for 19..17 from the releases page and build it against 19.1.9

**Comment by expand** [comment]
Issue is `deprioritized` as `no Assignee found` and scheduled for `auto-close` if no activity in the next `60 days`.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
