### ISSUE TITLE
ME throws exception for 'Xpand.Persistent.Base.General.XpandModuleBase'  / Mono.Cecil.DefaultReflectionImporter

### ISSUE THREAD

**Issue by neuropseudolonicher** [eXpandFramework/eXpand#753]
When trying to update Model on the projects in my solution or trying to start the Model Editor in VS 2019, both of the actions fail with "The type initializer for 'Xpand.Persistent.Base.General.XpandModuleBase' threw an exception."

Exception details:

_Unable to create an instance of the "myApp.Win.myAppWindowsFormsApplication" type.
Reason: "The type initializer for 'Xpand.Persistent.Base.General.XpandModuleBase' threw an exception."

at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
   at DevExpress.Persistent.Base.ReflectionHelper.CreateObject(Type objectType, Object[] args)
   at DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   at DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   at DevExpress.ExpressApp.Design.ModelEditor.EditorPane.ReInit()
----------InnerException----------
The type initializer for 'Xpand.Persistent.Base.General.XpandModuleBase' threw an exception.
----------StackTrace----------
   at Xpand.Persistent.Base.General.XpandModuleBase..ctor()
   at Xpand.ExpressApp.Win.SystemModule.XpandSystemWindowsFormsModule..ctor()
   at myApp.Win.myAppWindowsFormsApplication.InitializeComponent() in D:\source\repos\WinApplication.Designer.vb:line 57
   at myApp.Win.myAppWindowsFormsApplication..ctor() in D:\source\repos\WinApplication.vb:line 40
   at Create_myAppWindowsFormsApplication()
   at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
----------InnerException----------
Could not load type 'Mono.Cecil.DefaultReflectionImporter' from assembly 'Mono.Cecil, Version=0.10.0.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'.
----------StackTrace----------
   at MonoMod.Utils.MMReflectionImporter..ctor(ModuleDefinition module)
   at MonoMod.Utils.MMReflectionImporter._Provider.GetReflectionImporter(ModuleDefinition module)
   at Mono.Cecil.ModuleDefinition.CreateModule(String name, ModuleParameters parameters)
   at HarmonyLib.HarmonySharedState.CreateModule()
   at HarmonyLib.HarmonySharedState.GetState()
   at HarmonyLib.HarmonySharedState.GetPatchInfo(MethodBase method)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)
   at Xpand.Persistent.Base.General.XpandModuleBase..cctor()_

System Information:
Windows 10 1809
VS 2019 Professional Version 16.7.1
eXpand-Version 20.1.401.0
DevExpress Version 20.1.4.0
Framework Version 4.7.2

**Comment by apobekiaris** [comment]
can u post the machine.config addition for reference pleasse

**Comment by apobekiaris** [comment]
```xml
<runtime>
	<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
	  <dependentAssembly>
		<assemblyIdentity name="Mono.Cecil" publicKeyToken="50cebf1cceb9d05e" culture="neutral" />
		<bindingRedirect oldVersion="0.0.0.0-0.10.1.0" newVersion="0.11.2.0" />
	  </dependentAssembly>
  </assemblyBinding>
</runtime>
```
