### ISSUE TITLE
Middle  tier sample

### ISSUE THREAD

**Issue by sam105kelly** [eXpandFramework/eXpand#768]
Please provide E4036-WCF sample with the current version of expand framework including workflow server.
thanks

**Comment by apobekiaris** [comment]
even if a sample exists the real issue is the long time support of it. Publishing a sample that works only for now makes no sesnse tests/easytest must be added in the pipe. If u have an issue with a specific module set installation provide a sample and repro details

**Comment by sam105kelly** [comment]
i din't mean to include in expand.
let me try to make it work.will provide a sample

**Comment by apobekiaris** [comment]
expand has a lot of packages currently:

```ps1
(Get-XpandPackageNames).count
224
```

and unfortunately there is no list nor tests which they work in such a scenario

**Comment by apobekiaris** [comment]
try to be specific to your needs

**Comment by apobekiaris** [comment]
a label also exist, a lookup to see if u can get help

https://github.com/eXpandFramework/eXpand/issues?q=label%3AMiddleTier+

**Comment by sam105kelly** [comment]
[middletier.zip](https://github.com/eXpandFramework/eXpand/files/5183168/middletier.zip)
Problem appears to come from sequence generator.
Also I dont know the purpose of IModelDifferenceServerModels

**Comment by sam105kelly** [comment]
IS there a way to disable the sequence generator.
Am asking because am using sqllite which doesnt support it

**Comment by apobekiaris** [comment]
from the wiki of the sequencegenerator module 

>The module works only for MSSQL, MySql, and Oracle databases.

https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator#issues-debugging-troubleshooting

**Comment by apobekiaris** [comment]
let me know if the unload feature does not work as expected

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❇️ Exclusive-Services](https://github.com/eXpandFramework/eXpand/labels/❇️%20Exclusive-Services)
 1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by sam105kelly** [comment]
Unload feature works but wcf channel is in a faulted state after logon.I am still trying to determine the cause

**Comment by sam105kelly** [comment]
App server is now working. Just edited the default XAF project template and added this.
` 
`public class ALevelServerApplication : ServerApplication, IModelDifferenceServerModels
    {
        public IQueryable<ModelDifferenceObject> Where(IQueryable<ModelDifferenceObject> modelDifferenceObjects)
        {
            return modelDifferenceObjects;
        }
        protected override string GetModelAssemblyFilePath()
        {
            return this.GetModelFilePath();
        }
    }`

However unload fails on the Workflow Server with null reference exception
stacktrace


   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.<>c__DisplayClass5_0.<Unload>b__0(ApplicationModulesManager _)
   at System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Sink`1.ForwardOnError(Exception error)
   at System.Reactive.Sink`1.ForwardOnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager applicationModulesManager)
   at DevExpress.ExpressApp.ApplicationModulesManager.SetupModules_Patch1(ApplicationModulesManager this)
   at DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   at DevExpress.ExpressApp.XafApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   at DevExpress.ExpressApp.XafApplication.Setup()
   at Solution2.WorkflowServerService.Solution2WorkflowServer.Start()
   at Solution2.WorkflowServerService.Program.<>c.<Main>b__0_3(Solution2WorkflowServer execute)
   at Topshelf.ServiceConfiguratorExtensions.<>c__DisplayClass2_0`1.<WhenStarted>b__0(T service, HostControl control)
   at Topshelf.Builders.DelegateServiceBuilder`1.DelegateServiceHandle.Start(HostControl hostControl)
   at Topshelf.Hosts.ConsoleRunHost.Run()

**Comment by sam105kelly** [comment]
Also Enlighten me on the proper implementation of IModelDifferenceServerModels

**Comment by mbogaerts** [comment]
> Also Enlighten me on the proper implementation of IModelDifferenceServerModels

+1

**Comment by sam105kelly** [comment]
faulted state after login occurs  when you add xpand workflow module.
Otherwise it works fine.
Also I have Added
            Xpand.XAF.Modules.Reactive.ReactiveModuleBase.Unload(typeof(Xpand.XAF.Modules.PositionInListview.PositionInListViewModule));

because throws nullreferenceexception when creating initial database schema in updater

**Comment by sam105kelly** [comment]
PositionInListview throws nullreferenceexception when i store model differences in database.

**Comment by apobekiaris** [comment]
> Also Enlighten me on the proper implementation of IModelDifferenceServerModels

whats the problem with it? u can llok the git history on the file which point back to #234  u can also search for code dependecies to get a better clue.

>PositionInListview throws nullreferenceexception when i store model differences in database.

sample gives a chance to resolve the case at some point.

**Comment by sam105kelly** [comment]
[middletier.zip](https://github.com/eXpandFramework/eXpand/files/5197337/middletier.zip)

**Comment by Johnkag** [comment]
decided to just reset the client channel at after logon

**Comment by apobekiaris** [comment]
thanks for commenting but keep in mind that is very hard to understand your last comment at research time. Try a bit more detailed commenting if possible

**Comment by Johnkag** [comment]
Added this 
 `wcfSecuredClient.ClientChannel.Opening += ClientChannel_Opening;`
and the handler
`private static void ClientChannel_Opening(object sender, EventArgs e)
        {
            ((IClientChannel)sender).Faulted += (clientChannelSender, clientChannelEventHandler) =>
            {
                ((IClientChannel)clientChannelSender).Abort();
                Thread.Sleep(1000);
                wcfSecuredClient.ResetChannel();
                wcfSecuredClient.ClientChannel.Opening += ClientChannel_Opening;
                wcfSecuredClient.Logon();
            };


        }`
just to deal with the faulted wcf channel at startup

**Comment by apobekiaris** [comment]
added tests for the following cases

SequenceGenerator: UnSupported_DataStore_registration_should_not_throw 
SequenceGenerator: Middle_Tier_registration_should_not_throw

**Comment by expand** [comment]
The pre-release [2.201.21.4](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.21.4) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [SequenceGenerator: Middle_Tier_registration_should_not_throw #768](https://github.com/eXpandFramework/DevExpress.XAF/commit/ac07f1a5bda7612adcc5e7652f4fe9509f4fbe27)
* [SequenceGenerator: UnSupported_DataStore_registration_should_not_throw #768](https://github.com/eXpandFramework/DevExpress.XAF/commit/624056324af9b5883ad0ec9a554a613d163b1c4f)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
<a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions'>Xpand.Extensions v.2.202.59.4</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud'>Xpand.Extensions.Office.Cloud v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor'>Xpand.Extensions.Office.Cloud.Google.Blazor v.2.202.4.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive'>Xpand.Extensions.Reactive v.2.202.60.7</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF'>Xpand.Extensions.XAF v.2.202.60.8</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules'>Xpand.XAF.Core.All v.2.202.44.4</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit'>Xpand.XAF.Modules.AutoCommit v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue'>Xpand.XAF.Modules.CloneMemberValue v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView'>Xpand.XAF.Modules.CloneModelView v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor'>Xpand.XAF.Modules.GridListEditor v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar'>Xpand.XAF.Modules.HideToolBar v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade'>Xpand.XAF.Modules.LookupCascade v.2.202.62.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail'>Xpand.XAF.Modules.MasterDetail v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper'>Xpand.XAF.Modules.ModelMapper v.2.202.60.6</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance'>Xpand.XAF.Modules.ModelViewInheritance v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google'>Xpand.XAF.Modules.Office.Cloud.Google v.2.202.21.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar'>Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.2.202.11.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks'>Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.2.202.18.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft'>Xpand.XAF.Modules.Office.Cloud.Microsoft v.2.202.61.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Calendar'>Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar v.2.202.32.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo'>Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.2.202.31.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.DocumentStyleManager'>Xpand.XAF.Modules.Office.DocumentStyleManager v.2.202.8.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView'>Xpand.XAF.Modules.OneView v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/PositionInListView'>Xpand.XAF.Modules.PositionInListView v.2.202.31.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem'>Xpand.XAF.Modules.ProgressBarViewItem v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive'>Xpand.XAF.Modules.Reactive v.2.202.60.9</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger'>Xpand.XAF.Modules.Reactive.Logger v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win'>Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub'>Xpand.XAF.Modules.Reactive.Logger.Hub v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView'>Xpand.XAF.Modules.RefreshView v.2.202.61.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator'>Xpand.XAF.Modules.SequenceGenerator v.2.202.60.8</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation'>Xpand.XAF.Modules.SuppressConfirmation v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode'>Xpand.XAF.Modules.ViewEditMode v.2.202.60.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewItemValue'>Xpand.XAF.Modules.ViewItemValue v.2.202.26.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewWizard'>Xpand.XAF.Modules.ViewWizard v.2.202.22.5</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules'>Xpand.XAF.Web.All v.2.202.44.4</a>
 <a href='https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules'>Xpand.XAF.Win.All v.2.202.44.4</a>

</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Issue is `deprioritized` as `no Assignee found` and scheduled for `auto-close` if no activity in the next `60 days`. Thanks a lot for your contribution.

**Comment by emeyke** [comment]
Hi @Johnkag 
Would you be able to post your last working sample from this issue?
Last on referenced does not open.

Thanks
Evgeniy

**Comment by Johnkag** [comment]
I don't have the original sample now but I can create for you one of these three samples.
1. A working sample with a workaround or
2. A new sample if the current release fixed the issue.

**Comment by emeyke** [comment]
Thanks. I think I am fine for now!

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
