### ISSUE TITLE
 Office calendar module : Path cannot be the empty string or all whitespace

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#797]
Hello,

Pretty strange, after the migration to the 20.2.3, my project runs in visual studio but not in IIS in remote serer. 
I checked the security on folder of IIS but this is not the issue. 

Does this exceltion talk to you ? 

The error occurred:

	Type:       ObjectCreatingException
	Message:    Unable to create an instance of the "Xpand.XAF.Modules.Office.Cloud.Microsoft.MicrosoftModule" type.
Reason: "The type initializer for 'Xpand.XAF.Modules.Reactive.ReactiveModuleBase' threw an exception."
	Data:       1 entries
			'ASPIMPERSONATING'		''
	Stack trace:

   at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
   at DevExpress.ExpressApp.ModuleBase.CreateModule(Type moduleType, ModelStoreBase diffsStore)
   at DevExpress.ExpressApp.Core.ModuleFactory.ModuleFactoryWithResourcesDiffsStore.CreateModule(Type moduleType)
   at DevExpress.ExpressApp.ApplicationModulesManager.EnsureModuleInList(Type moduleType, IList`1 moduleList, List`1 requiredModules)
   at DevExpress.ExpressApp.ApplicationModulesManager.AddModuleIntoList(ModuleBase module, IList`1 moduleList, List`1 requiredModules)
   at DevExpress.ExpressApp.ModuleList.RefreshRequiredModules()
   at DevExpress.ExpressApp.Utils.BindingListBase`1.EndInit()
   at PME_Affaire.Web.PME_AffaireAspNetApplication..ctor()
   at PME_Affaire.Web.Global.Session_Start(Object sender, EventArgs e)
   at System.Web.SessionState.SessionStateModule.CompleteAcquireState()
   at System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
	----------------
	InnerException:

			Type:       TypeInitializationException
			Message:    The type initializer for 'Xpand.XAF.Modules.Reactive.ReactiveModuleBase' threw an exception.
			Data:       0 entries
			Stack trace:

   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase..ctor()
   at Xpand.XAF.Modules.Office.Cloud.Microsoft.MicrosoftModule..ctor()
   at Create_MicrosoftModule()
   at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
			----------------
			InnerException:

					Type:       TypeInitializationException
					Message:    The type initializer for 'HarmonyLib.FileLog' threw an exception.
					Data:       0 entries
					Stack trace:

   at HarmonyLib.FileLog.GetBuffer(Boolean clear)
   at HarmonyLib.MethodBodyReader.FinalizeILCodes(Emitter emitter, List`1 transpilers, List`1 endLabels, Boolean& hasReturnCode)
   at HarmonyLib.MethodCopier.Finalize(Emitter emitter, List`1 endLabels, Boolean& hasReturnCode)
   at HarmonyLib.MethodPatcher.CreateReplacement(Dictionary`2& finalInstructions)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)
   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase..cctor()
					----------------
					InnerException:

							Type:       ArgumentException
							Message:    Path cannot be the empty string or all whitespace.
							Data:       0 entries
							Stack trace:

   at System.IO.Directory.CreateDirectory(String path)
   at HarmonyLib.FileLog..cctor()
							InnerException is null

**Comment by apobekiaris** [comment]
it relates to Harmony and from what I see in their source code it has been fixed but our dependecy is outdated. You have to wait a bit to publish to IIS at least until next lab minor

**Comment by apobekiaris** [comment]
add a dependency to Xpand.Patcher 2.0.27 and let me know

**Comment by expand** [comment]
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❇️ Exclusive-Services](https://github.com/eXpandFramework/eXpand/labels/❇️%20Exclusive-Services)
 1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by isatahiri** [comment]
just tried, seems to work. 
Thanks

**Comment by expand** [comment]
Issue is `deprioritized` as `no Assignee found` and scheduled for `auto-close` if no activity in the next `60 days`. Thanks a lot for your contribution.
