### ISSUE TITLE
Opening Xpand Model Editor throws the following errors on startup

### ISSUE THREAD

**Issue by DSCmattb** [eXpandFramework/eXpand#802]
App is running net462.

```
Unable to create an instance of the "MoveObjectUpActionViewController" type.
Reason: "The given key was not present in the dictionary."

The given key was not present in the dictionary.

   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Xpand.XAF.Modules.Reactive.Services.Actions.ActionsService.Notify(Controller controller)
   at MoveObjectUpActionViewController..ctor()
   at Create_MoveObjectUpActionViewController()
   at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
```

Unable to create an instance of the "ViewItemValueActionViewController" type.
Reason: "The given key was not present in the dictionary."

```
The given key was not present in the dictionary.

   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Xpand.XAF.Modules.Reactive.Services.Actions.ActionsService.Notify(Controller controller)
   at ViewItemValueActionViewController..ctor()
   at Create_ViewItemValueActionViewController()
   at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
```

The application is being run from command line at the current stage.

Used to work in 20.1.401.0 prior to upgrade.

**Comment by apobekiaris** [comment]
can u sample it?

**Comment by apobekiaris** [comment]
>Used to work in 20.1.401.0 prior to upgrade.

I know that making a sample is hard work and for that reason it many times reveal the problem solution as you build it. 

I also understand that migration to latest must give you pains so I want you to note that if you can afford to pay a few hours on one of my tiers I can work directly on your project saving you of all that pain.

Those said I expect to see repro samples in your tickets where u use nuget packages so the sample can run fine in all environment  system so I can quickly provide an  advice. At least I wasn't able to run your last sample as u used XAF from references and something was wrong and couldn't afford more time on it.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
