### ISSUE TITLE
unable to open model editor

### ISSUE THREAD

**Issue by mbogaerts** [eXpandFramework/eXpand#811]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
Cannot load designer
𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
1. install al latest versions of xpand and open de model editor
2. exception:
at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
   at DevExpress.Persistent.Base.ReflectionHelper.CreateObject(Type objectType, Object[] args)
   at DevExpress.ExpressApp.Design.TreeBuilder`1.CreateModuleReferenceTreeItem(TreeView treeView, Type moduleType, Boolean useToolboxImage)
   at DevExpress.ExpressApp.Design.ModuleTypesTreeBuilder.BuildTree(TreeView treeView, ModuleBase dataSource)
   at DevExpress.ExpressApp.Design.ModuleTypesTreeViewTray.RefreshNodes()
   at DevExpress.ExpressApp.Design.TreeViewTray`1.set_DataSource(DataSourceType value)
   at DevExpress.ExpressApp.Design.XafModuleRootDesignerGUI.Initialize(XafModuleRootDesigner designer)
   at DevExpress.ExpressApp.Design.XafModuleRootDesigner.InitializeView()
   at DevExpress.ExpressApp.Design.XafRootDesignerBase.DesignerHost_LoadComplete(Object sender, EventArgs e)
----------InnerException----------
The type initializer for 'Xpand.XAF.Modules.Reactive.ReactiveModuleBase' threw an exception.
----------StackTrace----------
   at Xpand.XAF.Modules.HideToolBar.HideToolBarModule..ctor()
   at Create_HideToolBarModule()
   at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
----------InnerException----------
The type initializer for 'Xpand.Extensions.XAF.AppDomainExtensions.AppDomainExtensions' threw an exception.
----------StackTrace----------
   at Xpand.Extensions.XAF.AppDomainExtensions.AppDomainExtensions.Patch(AppDomain appDomain, Action`1 patch)
   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase..cctor()
----------InnerException----------
Could not load type 'Mono.Cecil.DefaultReflectionImporter' from assembly 'Mono.Cecil, Version=0.10.0.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'.
----------StackTrace----------
   at MonoMod.Utils.MMReflectionImporter..ctor(ModuleDefinition module)
   at MonoMod.Utils.MMReflectionImporter._Provider.GetReflectionImporter(ModuleDefinition module)
   at Mono.Cecil.ModuleDefinition.CreateModule(String name, ModuleParameters parameters)
   at HarmonyLib.HarmonySharedState.CreateModule()
   at HarmonyLib.HarmonySharedState.GetState()
   at HarmonyLib.HarmonySharedState.GetPatchInfo(MethodBase method)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)
   at Xpand.Extensions.XAF.AppDomainExtensions.AppDomainExtensions.<>c.<.cctor>b__1_0(Harmony harmony)
   at Xpand.Extensions.XAF.AppDomainExtensions.AppDomainExtensions.Patch(AppDomain appDomain, Action`1 patch)
   at Xpand.Extensions.XAF.AppDomainExtensions.AppDomainExtensions..cctor()
𝗘𝘅𝗽𝗲𝗰𝘁𝗲𝗱 𝗯𝗲𝗵𝗮𝘃𝗶𝗼𝗿
𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁𝘀
𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

01. ❇️ Exclusive-Services
01. ❤ Bronze Sponsor
02. ❤ Sponsor
03. ❤ Backer
04. Installation
05. ShowStopper
06. Nuget
07. Contribution
08. BreakingChange
09. ReproSample
10. Deployment
11. Must-Have

For all other issues the posting time is respected.

**Comment by apobekiaris** [comment]
>'Mono.Cecil, Version=0.10.0.0,

looks similar #753

**Comment by mbogaerts** [comment]
Yes it does apparently,

I have been investigating the reason but have not found a direct cause. Keep you posted I might find anything related.
For now I have excluded xpand from this project until I have time to investigate further.

With expand and the vsix installed the solution is not stable (and fast) enough at this point. I need to pass the project on to a non XAF dev so I need it to go smooth.

Thnx however for your effort

**Comment by apobekiaris** [comment]
still confused the #753 should resolve this case, isn't it?

**Comment by mbogaerts** [comment]
1) It does not thown the exception anymore but I don’t get beyond this because the VS crashes (on 2 different corporate systems)
2) I do not want to update machine configs on all dev systems
3) there has to be a reason for this … and I would like to find it 😊

**Comment by apobekiaris** [comment]
here the conflict back then

https://github.com/eXpandFramework/eXpand/issues/724#issuecomment-657214257.

**Comment by apobekiaris** [comment]
> It does not thown the exception anymore but I don’t get beyond this because the VS crashes (on 2 different corporate systems)

looks like it just tries to load the missing assembly and it stackoverflows thats why VS crash and not throwing

**Comment by apobekiaris** [comment]
also in latest versions VSIX is not a requirement any more

**Comment by mbogaerts** [comment]
Disabled the vsix, now I’m having issue #802…

**Comment by mbogaerts** [comment]
VSIX Light would be nice then 😊
only the Models List and easy model editor laucher OTB.

M.

**Comment by apobekiaris** [comment]
I think there is a working solution with the machine.config and and then end this is why machine.config exists, to solve problems like this one. Net Core XAF uses a standalone modeleditor so most problably such issues won't exist there

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
