### ISSUE TITLE
Cannot Open WorkflowInstances of a Scheduled Workflow

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#813]
I want to see if I should be able to do this. If so, I will look further and see if I can find the issue. Didn't want to start digging if it is not supposed to work.

I have a scheduled workflow. When I click the action to "Show Workflow Instances" a list view comes up with the instances. When I try to open a detail view it gives an error. Should I be able to open a detail view for scheduled workflow instance?

Exception: System.InvalidOperationException: Exception occurs while assigning the 'DetailView, ID:XpoRunningWorkflowInstanceInfo_DetailView' view to WinWindow:
Input string was not in a correct format. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at DevExpress.ExpressApp.Workflow.Visualization.RunningWorkflowInstanceInfoControllerBase`1.GetUserActivityVersion(IRunningWorkflowInstanceInfo info)
   at DevExpress.ExpressApp.Workflow.Visualization.RunningWorkflowInstanceInfoControllerBase`1.GetWorkflowXaml(IRunningWorkflowInstanceInfo info)
   at DevExpress.ExpressApp.Workflow.Visualization.TrackingVisualizationController.UpdateWorkflowTrackingRecordVisualization(String selectedActivityId)
   at DevExpress.ExpressApp.Workflow.Win.WinTrackingVisualizationController.UpdateWorkflowTrackingRecordVisualization(String selectedActivityId)
   at DevExpress.ExpressApp.Workflow.Visualization.TrackingVisualizationController.OnActivated()
   at DevExpress.ExpressApp.Controller.activeList_ResultValueChanged(Object sender, BoolValueChangedEventArgs e)
   at DevExpress.ExpressApp.Utils.BoolList.OnResultValueChanged(Boolean oldResultValue, Boolean resultValue)
   at DevExpress.ExpressApp.Utils.BoolList.EndUpdate()
   at DevExpress.ExpressApp.ViewController.SetView(View newView)
   at DevExpress.ExpressApp.Frame.ActivateViewControllers()
   at DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
   --- End of inner exception stack trace ---
   at DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.CreateWindow(ShowViewParameters parameters, ShowViewSource showViewSource, Boolean isMain)
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.CreateInspectorWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.CreateInspectorWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewInInspector(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.ShowViewInNewWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewFromCommonView(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.ShowViewStrategyBase.ShowViewCore(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewCore(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.ShowViewStrategyBase.ShowView(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Frame.ProcessActionCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Win.WinWindow.ProcessActionCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Frame.ShowViewAction_ProcessCreatedView(Object sender, ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.OnProcessCreatedView(ActionBaseEventArgs e)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs) Inner Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at DevExpress.ExpressApp.Workflow.Visualization.RunningWorkflowInstanceInfoControllerBase`1.GetUserActivityVersion(IRunningWorkflowInstanceInfo info)
   at DevExpress.ExpressApp.Workflow.Visualization.RunningWorkflowInstanceInfoControllerBase`1.GetWorkflowXaml(IRunningWorkflowInstanceInfo info)
   at DevExpress.ExpressApp.Workflow.Visualization.TrackingVisualizationController.UpdateWorkflowTrackingRecordVisualization(String selectedActivityId)
   at DevExpress.ExpressApp.Workflow.Win.WinTrackingVisualizationController.UpdateWorkflowTrackingRecordVisualization(String selectedActivityId)
   at DevExpress.ExpressApp.Workflow.Visualization.TrackingVisualizationController.OnActivated()
   at DevExpress.ExpressApp.Controller.activeList_ResultValueChanged(Object sender, BoolValueChangedEventArgs e)
   at DevExpress.ExpressApp.Utils.BoolList.OnResultValueChanged(Boolean oldResultValue, Boolean resultValue)
   at DevExpress.ExpressApp.Utils.BoolList.EndUpdate()
   at DevExpress.ExpressApp.ViewController.SetView(View newView)
   at DevExpress.ExpressApp.Frame.ActivateViewControllers()
   at DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)

**Comment by apobekiaris** [comment]
>Should I be able to open a detail view for scheduled workflow instance?

isn't obvious? yes u should, let me know what your research finds out

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
