### ISSUE TITLE
Win Assembly reference in web project

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#834]
This is old.
Using Dashboards in Web app requires a Win Dll, that it is correct?

`System.InvalidOperationException: Exception occurs while assigning the 'DashboardView, ID:Socio_DashBoard_Publico' view to WebWindow:
Could not load file or assembly '**DevExpress.ExpressApp.Win.v20.2**, Version=20.2.4.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'DevExpress.ExpressApp.Win.v20.2, Version=20.2.4.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a' or one of its dependencies. The system cannot find the file specified.
at **Xpand.Persistent.Base.General.Controllers.Dashboard.DashboardInteractionController.OnActivated()**
at DevExpress.ExpressApp.Controller.activeList_ResultValueChanged(Object sender, BoolValueChangedEventArgs e)
at DevExpress.ExpressApp.Utils.BoolList.OnResultValueChanged(Boolean oldResultValue, Boolean resultValue)
at DevExpress.ExpressApp.Utils.BoolList.EndUpdate()
at DevExpress.ExpressApp.ViewController.SetView(View newView)
at DevExpress.ExpressApp.Frame.ActivateViewControllers()
at DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)`

**Comment by apobekiaris** [comment]
can u test on a sample solution please?

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
