### ISSUE TITLE
wanting more info about " Possible fix as per issue #753**" exception

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#837]
While porting an existing app to blazor (there still net461 targets), I hit the following exception
(I'm new with blazor, but I had success porting another existing xaf app)

`f.Blazor.Server Error: 0 : 23.01.21 22:27:21.742	ba52b82f-8f37-4612-8d36-da69ad04af3a	================================================================================
The error occurred:

	Type:       ObjectCreatingException
	Message:    Unable to create an instance of the "Xpand.ExpressApp.Security.XpandSecurityModule" type.
Reason: "The type initializer for 'Xpand.Persistent.Base.General.XpandModuleBase' threw an exception."
	Data:       0 entries
	Stack trace:

   at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
   at DevExpress.ExpressApp.Utils.Reflection.TypeHelper.CreateInstance(Type type, Object[] args)
   at DevExpress.ExpressApp.ModuleBase.CreateModule(Type moduleType, ModelStoreBase diffsStore)
   at DevExpress.ExpressApp.Core.ModuleFactory.ModuleFactoryWithResourcesDiffsStore.CreateModule(Type moduleType)
   at DevExpress.ExpressApp.ApplicationModulesManager.EnsureModuleInList(Type moduleType, IList`1 moduleList, List`1 requiredModules)
   at DevExpress.ExpressApp.ApplicationModulesManager.AddModuleIntoList(ModuleBase module, IList`1 moduleList, List`1 requiredModules)
   at DevExpress.ExpressApp.ApplicationModulesManager.AddModuleIntoList(ModuleBase module, IList`1 moduleList)
   at DevExpress.ExpressApp.ModuleList.RefreshRequiredModules()
   at DevExpress.ExpressApp.ModuleList.OnInitializeComplete()
   at DevExpress.ExpressApp.Utils.BindingListBase`1.EndInit()
   at DevExpress.ExpressApp.XafApplication.EndInit()
   at f.Blazor.Server.fBlazorApplication.InitializeComponent() in C:\TFS2020\F2011\F\f.Blazor.Server\BlazorApplication.Designer.cs:line 67
   at f.Blazor.Server.fBlazorApplication..ctor() in C:\TFS2020\F2011\F\f.Blazor.Server\BlazorApplication.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at DevExpress.ExpressApp.Blazor.Services.StartupExtensions.<>c__DisplayClass4_0`1.<AddXaf>b__1()
   at DevExpress.ExpressApp.Blazor.Services.XafApplicationFactory.CreateApplication()
   at DevExpress.ExpressApp.Blazor.Services.XafApplicationProvider.CreateApplication()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at DevExpress.ExpressApp.Blazor.Services.XafApplicationProvider.GetApplication()
   at DevExpress.ExpressApp.Blazor.Templates.LoginPageBase.CreateControl()
   at DevExpress.ExpressApp.Blazor.Templates.LoginPage.<BuildRenderTree>b__0_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at DevExpress.ExpressApp.Blazor.Components.XafExceptionHandler.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
	----------------
	InnerException:

			Type:       TypeInitializationException
			Message:    The type initializer for 'Xpand.Persistent.Base.General.XpandModuleBase' threw an exception.
			Data:       0 entries
			Stack trace:

   at Xpand.Persistent.Base.General.XpandModuleBase..ctor()
   at Xpand.ExpressApp.Security.XpandSecurityModule..ctor()
   at Create_XpandSecurityModule()
   at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
			----------------
			InnerException:

					Type:       Exception
					**Message:    Possible fix as per issue #753**
					Data:       0 entries
					Stack trace:

   at Xpand.Persistent.Base.General.XpandModuleBase..cctor()
					----------------
					InnerException:

							Type:       TypeLoadException
							Message:    Could not load type 'System.Web.UI.Control' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
							Data:       0 entries
							Stack trace:

   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.Assembly.GetType(String name)
   at Xpand.Persistent.Base.General.XpandModuleBase.LoadAssemblyRegularTypes()
   at Xpand.Persistent.Base.General.XpandModuleBase..cctor()
							InnerException is null`

**Comment by apobekiaris** [comment]
the main framework packages are not compatible with blazor at least not yet, some will never be

**Comment by apobekiaris** [comment]
>there still net461 targets

makes no sense, u either want netstandard2.0, netstandard2.1 or netCore3.1, net5

**Comment by vimarx** [comment]
in this case, the Xpand.Expressapp.Security module is throwing this exception, which is referenced by the Xpand.IO Module, that  is the module that I need to use .
is there any posible workaround?

**Comment by apobekiaris** [comment]
can try experiment to unload the security module like we do in reactive packages? it might work or if u want to support your own custom branch just remove the Security module dependecies from ModelArtifactState package or remove the ModelArtiFact from IO

https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire#issues-debugging-troubleshooting

**Comment by apobekiaris** [comment]
the IO looks like a module that can live in Blazor however it will be rewritten using RX

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
