### ISSUE TITLE
Xpand.XAF.Modules.LookupCascade - Bug - System.MissingMethodException

### ISSUE THREAD

**Issue by txt2203** [eXpandFramework/eXpand#859]
XAF project: DevexPress 20.2.5 + XPand 20.2.504 + XAF 4.202.52
Debug XAF Web project, Bug at line : "WebApplication.Instance.Setup();" in file Glocal.asax.cs.
show :
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.IObservable`1<System.ValueTuple`2<!!0,!!1>> System.Reactive.Linq.ObservableEx.CombineLatest(System.IObservable`1<!!0>, System.IObservable`1<!!1>)'.
  Source=Xpand.XAF.Modules.LookupCascade
  StackTrace:
   at Xpand.XAF.Modules.LookupCascade.LookupCascadeService.RegisterClientScripts(XafApplication application) in D:\a\1\s\src\Modules\LookupCascade\LookupCascadeService.cs:line 45
   at Xpand.XAF.Modules.LookupCascade.LookupCascadeService.<>c.<Connect>b__4_0(XafApplication application) in D:\a\1\s\src\Modules\LookupCascade\LookupCascadeService.cs:line 32
   at Xpand.XAF.Modules.Reactive.Services.ApplicationModulesManagerService.<>c__DisplayClass0_1`1.<WhenApplication>b__1() in D:\a\1\s\src\Modules\Reactive\Services\ApplicationModulesManagerService.cs:line 20
   at System.Reactive.Linq.ObservableImpl.Defer`1._.Run() in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Defer.cs:line 37

I installed eXpandAnogstic , eXpandWeb, XPand.XAF.Core.All, Xpand.XAF.Web.All. But not solved.
Please advise.

**Comment by apobekiaris** [comment]
are u interested in the LookupCascade module? what about if u not install it?

**Comment by txt2203** [comment]
I could not remove LookupCascade module because other important modules depend on it. Actually I don't want to use it.

**Comment by apobekiaris** [comment]
what other important modules? did u tried the wiki instructions?

https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/LookupCascade#issues-debugging-troubleshooting

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
