### ISSUE TITLE
exception in my First winform app migrated to net5 

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#883]
https://user-images.githubusercontent.com/226800/132349102-3239695e-8d5b-4394-9ffe-0bbb98f0b93c.mp4

Hi, I've migrated an existing noncritical xaf app to net5 (the rest of assemblies were left as there are)
It works very well!

found an exception while using right-click for adding a summary to a group

The error occurred:

	Type:       NullReferenceException
	Message:    Object reference not set to an instance of an object.
	Data:       0 entries
	Stack trace:

   at Xpand.ExpressApp.Win.SystemModule.RuleCollector..ctor(IModelListView modelListView)
   at Xpand.ExpressApp.Win.SystemModule.GridListEditorEventController.GridViewOnPopupMenuShowing(Object sender, PopupMenuShowingEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.GridView.RaisePopupMenuShowing(PopupMenuShowingEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.GridView.DoShowGridMenu(GridMenuEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.GridView.DoShowGridMenu(GridViewMenu menu, GridHitInfo hitInfo)
   at DevExpress.XtraGrid.Views.Grid.Handler.GridHandler.DoCheckShowMenu()
   at DevExpress.XtraGrid.Views.Grid.Handler.GridHandler.OnMouseDown(MouseEventArgs ev)
   at DevExpress.Utils.Controls.BaseHandler.ProcessEvent(EventType etype, Object args)
   at DevExpress.XtraGrid.Views.Base.Handler.BaseViewHandler.ProcessEvent(EventType etype, Object args)
   at DevExpress.XtraGrid.GridControl.OnMouseDown(MouseEventArgs ev)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   at DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
	InnerException is null

**Comment by apobekiaris** [comment]
i do not see how it relates to .net5, probably your system changed a bit. Anyway I can attempt a fix in the next minor

**Comment by apobekiaris** [comment]
eXpand.lab release [21.1.501.2](https://github.com/eXpandFramework/eXpand.lab/releases/21.1.501.2) includes commit that relate to this task:

* [Null Reference exception #883](https://github.com/eXpandFramework/eXpand.lab/commit/403f90ba4fb5cd49a7d29249ea191a22080dac9c)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
eXpand.lab release [21.1.600.0](https://github.com/eXpandFramework/eXpand.lab/releases/21.1.600.0) includes commit that relate to this task:

* [Null Reference exception #883](https://github.com/eXpandFramework/eXpand.lab/commit/31576123fdc3012cc427d3ed0a75ae99c926b973)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
