### ISSUE TITLE
Error with DashboardModule ,  XpandReportsModule, XpandPivotGridWinModule

### ISSUE THREAD

**Issue by txt2203** [eXpandFramework/eXpand#901]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
When adding modules below :
RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Dashboard.DashboardModule));
RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.Reports.XpandReportsModule));
RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.PivotGrid.Win.XpandPivotGridWinModule));
=> Then build and open Model editor, an same Err dialog showed for all cases (but then Model Editor still opened after pressing OK) :
There is already a node with Id 'DashboardDefinitionViewer_DetailView'. The node: Application/Views/DashboardDefinitionViewer_DetailView. To avoid this error, analyze your custom code or XAFML model differences for possible duplicate nodes creation or follow the www.devexpress.com/kb=S19870 KB article, if you have several classes in different namespaces, but with the same name.
   at DevExpress.ExpressApp.Model.Core.ModelNode.AddNodeCore(ModelNode node)
   at DevExpress.ExpressApp.Model.Core.ModelNode.AddNodeCore(String id, Type type)
   at DevExpress.ExpressApp.Model.Core.ModelNode.AddNode(String id, Type type)
   at DevExpress.ExpressApp.Model.Core.ModelNode.AddNode[NodeType](String id)
   at Xpand.XAF.Modules.CloneModelView.CloneModelViewService.NewModelView(IModelViews modelViews, CloneModelViewAttribute cloneViewAttribute, IModelClass modelClass) in D:\a\1\s\src\Modules\CloneModelView\CloneModelViewService.cs:line 45
   at Xpand.XAF.Modules.CloneModelView.CloneModelViewService.GenerateModel(IModelViews views, IModelClass classInfo) in D:\a\1\s\src\Modules\CloneModelView\CloneModelViewService.cs:line 73
   at Xpand.XAF.Modules.CloneModelView.CloneModelViewService.<>c.<Connect>b__0_1(IModelViews views) in D:\a\1\s\src\Modules\CloneModelView\CloneModelViewService.cs:line 17
   at System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Do.cs:line 38
--- End of stack trace from previous location ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
   at System.Reactive.ExceptionHelpers.Throw(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:line 16
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 62
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error) in /_/Rx.NET/Source/src/System.Reactive/Internal/HalfSerializer.cs:line 77
   at System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnError(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeUntil.cs:line 62
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Do.cs:line 42
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 50
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 952
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 50
   at System.Reactive.Linq.ObservableImpl.Cast`2._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Cast.cs:line 40
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at Xpand.XAF.Modules.Reactive.Services.ApplicationModulesManagerService.NodesUpdater`1.UpdateNode(ModelNode node) in D:\a\1\s\src\Modules\Reactive\Services\ApplicationModulesManagerService.cs:line 90
   at DevExpress.ExpressApp.Model.ModelNodesGeneratorBase.RunUpdaters(ModelNode node, Boolean enableModelCache)
   at DevExpress.ExpressApp.Model.ModelNodesGeneratorBase.GenerateNodes(ModelNode node)
   at DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGenerator(ModelNodesGeneratorBase generator)
   at DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGeneratorForFirstLayer()
   at DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGenerator()
   at DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes(Boolean alwaysCreate)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetNode(String id, Boolean inThisLayer)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetNode(String id)
   at DevExpress.ExpressApp.Model.Core.ModelValuePersistentPathCalculator.Calculate(ModelNode node, String valueName, Boolean runDefaultCalculator, Boolean inThisLayer)
   at DevExpress.ExpressApp.Model.Core.ModelValuePersistentPathCalculator.Calculate(ModelNode originalNode, String propertyName)
   at DevExpress.ExpressApp.Model.Core.ModelNodeInfo.DefaultValueItem.CalcValue(ModelNode node, String propertyName)
   at DevExpress.ExpressApp.Model.Core.ModelNodeInfo.GetDefaultValue(ModelNode node, String propertyName)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetDefaultValue(String name)
   at DevExpress.ExpressApp.Model.Core.ModelNode.<>c.<GetDefaultValueCore>b__297_0(ModelNode node, String key)
   at DevExpress.ExpressApp.Model.Core.ModelNodeValuesCache.GetValue(ModelNode modelNode, String name, Func`3 getValueMethod)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetDefaultValueCore(ModelValueInfo info, String name)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[T](String name, Int32 aspectIndex, Boolean complex)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetValue[T](String name)
   at ModelClass.get_DefaultListView()
   at DevExpress.ExpressApp.SystemModule.NavigationItemNodeGenerator.GenerateNodesCore(ModelNode node)
   at DevExpress.ExpressApp.Model.ModelNodesGeneratorBase.GenerateNodes(ModelNode node)
   at DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGenerator(ModelNodesGeneratorBase generator)
   at DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGeneratorForFirstLayer()
   at DevExpress.ExpressApp.Model.Core.ModelNode.RunNodesGenerator()
   at DevExpress.ExpressApp.Model.Core.ModelNode.EnsureNodes(Boolean alwaysCreate)
   at DevExpress.ExpressApp.Model.Core.ModelNode.GetNode(String id, Boolean inThisLayer)
   at DevExpress.ExpressApp.Model.Core.ModelNodeInfo.GetChildNodes(ModelNode modelNode)
   at DevExpress.ExpressApp.Model.ModelEditorHelper.GetChildNodes(ModelNode modelNode)
   at DevExpress.ExpressApp.Win.Core.ModelEditor.ModelInterfaceAdapter.GetChildrenCore(Object nodeObject)
   at DevExpress.ExpressApp.Win.Core.ModelEditor.ModelInterfaceAdapter.HasChildren(Object nodeObject)
   at DevExpress.ExpressApp.Win.Core.ModelEditor.ExtendModelInterfaceAdapter.HasChildren(Object nodeObject)

𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
1. New XAF 21.2.4 with Blazor + Winform.
2. Add Xpand.XAF.Core.All, XpandWin, XpandWeb.
3. Error happend when adding above modules.

𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁𝘀
Attached.

For all other issues the posting time is respected
![XAF-mistakes-2](https://user-images.githubusercontent.com/55611923/149895331-1406a1bd-2ab7-4192-8b1e-9f5061aa87dd.png)
.

**Comment by emeyke** [comment]
Getting the same with 21.2.4 opening MDO runtime.

**Comment by apobekiaris** [comment]
without a sample using nuget latests I cannot spent my resources in vain

>Add Xpand.XAF.Core.All, XpandWin, XpandWeb.

what this even means? which modules u used and from where totally unclear

**Comment by apobekiaris** [comment]
see #908 is the same should be also treated here

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
