### ISSUE TITLE
21.2.6 WebApi project fails to run 

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#913]
21.2.6 WebApi project fails to run 
Looks like the same issue as https://supportcenter.devexpress.com/ticket/details/t1037737/api-the-xafapplicationedmmodelbuilder-getedmmodel-method-raises-the but it is claiming it is fixed in 21.2.6

System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot define keys on type 'Xpand.Extensions.XAF.NonPersistentObjects.ObjectType' deriving from 'DevExpress.ExpressApp.NonPersistentBaseObject'. The base type in the entity inheritance hierarchy already contains keys.
  Source=Microsoft.OData.ModelBuilder
  StackTrace:
   at Microsoft.OData.ModelBuilder.EntityTypeConfiguration.DerivesFrom(EntityTypeConfiguration baseType)
   at Microsoft.OData.ModelBuilder.ODataConventionModelBuilder.DiscoverInheritanceRelationships()
   at Microsoft.OData.ModelBuilder.ODataConventionModelBuilder.GetEdmModel()
   at DevExpress.ExpressApp.WebApi.Services.XafApplicationEdmModelBuilder.<>c__DisplayClass3_0.<GetEdmModel>b__0()
   at DevExpress.ExpressApp.Blazor.AmbientContext.ValueManagerStorageContext.<>c__DisplayClass4_0`1.<DevExpress.ExpressApp.Blazor.AmbientContext.IValueManagerStorageContext.RunWithStorage>b__0()
   at DevExpress.ExpressApp.Blazor.AmbientContext.ValueManagerContext.<IsolatedContext>d__16`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DevExpress.ExpressApp.Blazor.AmbientContext.ValueManagerContext.RunIsolated[T](Func`1 function)
   at DevExpress.ExpressApp.Blazor.AmbientContext.ValueManagerStorageContext.DevExpress.ExpressApp.Blazor.AmbientContext.IValueManagerStorageContext.RunWithStorage[T](Func`1 function)
   at DevExpress.ExpressApp.WebApi.Services.XafApplicationEdmModelBuilder.GetEdmModel()
   at EarthCape.WebApi.Startup.<>c__DisplayClass4_0.<ConfigureServices>b__4(ODataOptions options) in C:\Repos\earthcape\Projects\EarthCape.WebApi\Startup.cs:line 68
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)

  This exception was originally thrown at this call stack:
    [External Code]
    EarthCape.WebApi.Startup.ConfigureServices.AnonymousMethod__4(Microsoft.AspNetCore.OData.ODataOptions) in Startup.cs
    [External Code]

**Comment by apobekiaris** [comment]
can u sample me?

**Comment by emeyke** [comment]
Here you go.
[DXApplication7.zip](https://github.com/eXpandFramework/eXpand/files/8212821/DXApplication7.zip)

**Comment by apobekiaris** [comment]
fixed

**Comment by emeyke** [comment]
Works in 21.2.7
