### ISSUE TITLE
Runtime ModelDifference object does not open in 22.1.4

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#947]
Hi

With the latest Expand release I get this when opening model difference object runtime. Any hints what is going on. I failed to recreate the situation in a sample project - hopefully the stack gives a clue.

Actions with the duplicate 'Search' identifier are detected in the 'Xpand.ExpressApp.ModelDifference.Win.Controllers.ModelEditorTemplateViewController+ModelEditorActionsController' and 'Xpand.ExpressApp.Win.SystemModule.SearchFromDetailViewController' controllers. For a solution, see http://www.devexpress.com/kb=T191034.

   at DevExpress.ExpressApp.SystemModule.ActionCollection.Add(ActionBase action)
   at DevExpress.ExpressApp.SystemModule.ActionCollection.AddRange(IEnumerable`1 actions)
   at DevExpress.ExpressApp.SystemModule.ActionControlsSiteController.CollectActions()
   at DevExpress.ExpressApp.SystemModule.ActionControlsSiteController.SetupActionControlsSite(IActionControlsSite site)
   at DevExpress.ExpressApp.Win.WinWindow.OnTemplateChanged()
   at DevExpress.ExpressApp.Frame.SetTemplate(IFrameTemplate val)
   at DevExpress.ExpressApp.Win.WinWindow..ctor(XafApplication application, TemplateContext context, ICollection`1 controllers, Boolean isMain, Boolean activateControllersImmediately)
   at Xpand.ExpressApp.Win.XpandWinWindow..ctor(XafApplication application, TemplateContext context, ICollection`1 controllers, Boolean isMain, Boolean activateControllersImmediatelly)
   at Xpand.ExpressApp.Win.XpandWinApplication.CreateWindowCore(TemplateContext context, ICollection`1 controllers, Boolean isMain, Boolean activateControllersImmediatelly)
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.CreateWindow(ShowViewParameters parameters, ShowViewSource showViewSource, Boolean isMain)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.CreateInspectorWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewInInspector(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.ShowViewInNewWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewFromCommonView(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)

**Comment by apobekiaris** [comment]
if you not use the `Xpand.ExpressApp.SystemModule.Search.SearchFromDetailViewController` u can try disabling it and let me know if that works cause I did not test it

```
XpandModuleBase.DisableControllers(typeof(SearchFromDetailViewController));
```

**Comment by emeyke** [comment]
Yes that worked after disabling these both:
XpandModuleBase.DisableControllers(typeof(Xpand.ExpressApp.SystemModule.Search.SearchFromDetailViewController));
XpandModuleBase.DisableControllers(typeof(Xpand.ExpressApp.Win.SystemModule.SearchFromDetailViewController));

It would be great to use the search module though!

**Comment by apobekiaris** [comment]
eXpand.lab release [22.1.500.1](https://github.com/eXpandFramework/eXpand.lab/releases/22.1.500.1) includes commit that relate to this task:

* [Rename Search to SearchFromDetailView #947](https://github.com/eXpandFramework/eXpand.lab/commit/55522662477d62326f44a1b209dba25b5c2c1a5e)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment]
eXpand.lab release [22.2.400.0](https://github.com/eXpandFramework/eXpand.lab/releases/22.2.400.0) includes commit that relate to this task:

* [Rename Search to SearchFromDetailView #947](https://github.com/eXpandFramework/eXpand.lab/commit/911ecdb17271b0d7b39e979c5d748c43547ec6d1)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
