### ISSUE TITLE
JobScheduler.Hangfire throws a BinaryFormatter error at runtime

### ISSUE THREAD

**Issue by ramilcatalandomingo** [eXpandFramework/eXpand#957]
Hello,

I have created a fresh XAF Blazor 22.1.5 project and installed the JobScheduler.Hangfire 4.221.8 version from nuget.  The entire solution compiles without a problem but throws the following error at runtime.

[2022-10-13T04:42:12.854Z] Error: DevExpress.ExpressApp.DC.ObjectCreatingException: Unable to create an instance of the "Xpand.XAF.Modules.JobScheduler.Hangfire.JobSchedulerModule" type.
Reason: "The type initializer for 'Xpand.XAF.Modules.Reactive.ReactiveModuleBase' threw an exception."
 ---> System.TypeInitializationException: The type initializer for 'Xpand.XAF.Modules.Reactive.ReactiveModuleBase' threw an exception.
 ---> System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at HarmonyLib.PatchInfoSerialization.Serialize(PatchInfo patchInfo)
   at HarmonyLib.HarmonySharedState.UpdatePatchInfo(MethodBase original, MethodInfo replacement, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)
   at Xpand.Extensions.Harmony.HarmonyExtensions.PatchWith(MethodInfo method, HarmonyMethod prefix, HarmonyMethod postFix, HarmonyMethod transpiler, HarmonyMethod finalizer)
   at Xpand.Extensions.Harmony.HarmonyExtensions.PreFix(HarmonyMethod harmonyMethod, MethodInfo method)
   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase..cctor()
   --- End of inner exception stack trace ---
   at Xpand.XAF.Modules.JobScheduler.Hangfire.JobSchedulerModule..ctor() in D:\a\1\s\src\Modules\JobScheduler.Hangfire\Module.cs:line 25
   at Create_JobSchedulerModule()
   at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
   --- End of inner exception stack trace ---
   at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
   at DevExpress.ExpressApp.ModuleBase.CreateModule(Type moduleType, ModelStoreBase diffsStore)
   at DevExpress.ExpressApp.Core.ModuleFactory.ModuleFactoryWithResourcesDiffsStore.CreateModule(Type moduleType)
   at DevExpress.ExpressApp.ModuleList.EnsureModuleInList(Type moduleType, IList`1 moduleList, List`1 requiredModules)
   at DevExpress.ExpressApp.ModuleList.AddModuleIntoList(ModuleBase module, IList`1 moduleList, List`1 requiredModules)
   at DevExpress.ExpressApp.ModuleList.RefreshRequiredModules()
   at DevExpress.ExpressApp.Utils.BindingListBase`1.EndInit()
   at DevExpress.ExpressApp.Blazor.ApplicationBuilder.BlazorApplicationBuilder.Build(IServiceProvider serviceProvider)
   at DevExpress.ExpressApp.Blazor.Services.XafApplicationFactory`1.DevExpress.ExpressApp.AspNetCore.Core.IXafAspNetCoreApplicationFactory<DevExpress.ExpressApp.Blazor.BlazorApplication>.CreateApplication()
   at DevExpress.ExpressApp.AspNetCore.Core.Internal.XafApplicationServiceProviderInitializer`1.CreateApplication()
   at DevExpress.ExpressApp.AspNetCore.Core.Internal.XafApplicationSecurityInitializer`1.CreateApplication()
   at DevExpress.ExpressApp.AspNetCore.Core.Internal.ApplicationCustomizerCore`1.CreateApplication()
   at DevExpress.ExpressApp.Blazor.Services.XafApplicationFactory`1.DevExpress.ExpressApp.AspNetCore.Core.IXafAspNetCoreApplicationFactory<DevExpress.ExpressApp.Blazor.BlazorApplication>.CreateApplication()
   at DevExpress.ExpressApp.Blazor.Services.XafApplicationProvider.CreateApplication()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at DevExpress.ExpressApp.Blazor.Pages.LoginPageBase.CreateControl()
   at DevExpress.ExpressApp.Blazor.Pages.LoginPage.<BuildRenderTree>b__0_0(RenderTreeBuilder __builder2)
   at DevExpress.ExpressApp.Blazor.Components.XafExceptionHandler.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

I have here the sample project for reference.

[DXApplication2.zip](https://github.com/eXpandFramework/eXpand/files/9770866/DXApplication2.zip)

Please advise.  Thank you.

**Comment by ramilcatalandomingo** [comment]
Hello @apobekiaris. I hope you don't me asking if you have any ETA for a fix on this bug please? Thank you.

**Comment by apobekiaris** [comment]
sorry I forgot to answer here, sample please without sample I will not schedule resources. 

The case looks very strange as harmony which cause it does not use BinaryFormatters any more so I do not have a context how you repro this.

**Comment by ramilcatalandomingo** [comment]
No problem @apobekiaris.  The example is in the first message I sent over above.  I uploaded it with filename DXApplication2.zip.

**Comment by apobekiaris** [comment]
oops yes, I will see to it, hopefully soon as this build has many problems.

**Comment by ramilcatalandomingo** [comment]
Looking forward to a swift resolution @apobekiaris so I can move forward with my project.  As always, I appreciate your contribution to the XAF community and thank you very much for attending to my issues.

**Comment by apobekiaris** [comment]
fyi I will always reply cases that I am assinged especially with samples. I suggest you have a very easy to upgrade downgrade process/script and do not stop your works because of such bugs.

**Comment by apobekiaris** [comment]
e.g. downgrading eXpand/DX should be as easy as find/replace their versions in you solution csproj.

**Comment by ramilcatalandomingo** [comment]
Yup I do have branches to my projects so I can stop and switch to other tasks.  But thank you for your tip.  I appreciate it.  What I wanted to convey is that I am now in the stage of my project where automation is key in order for me to truly see the benefit of realizing the application I am building for XAF Blazor.  I can do away with creating the Hangfire integration from scratch but I do believe in not reinventing the wheel since your extension is what I am looking for.

**Comment by apobekiaris** [comment]
cool here another one some times you could also search this repo for a temp solution :)

https://github.com/eXpandFramework/eXpand/issues?q=BinaryFormatter

there lies your temp fix but as I say it shoul;d not happen with latest harmony somthing is really wrong there

**Comment by ramilcatalandomingo** [comment]
Looks like adding the `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>` flag to the csproj resolved the BinaryFormatter issue but now it throws a new one that I am not sure how to address.

[2022-10-17T05:16:59.515Z] Error: System.InvalidOperationException: Exception occurs while initializing the 'Xpand.XAF.Modules.Blazor.BlazorModule' module: Install the Xpand.XAF.Modules.Blazor package in the front end project and add: [assembly: HostingStartup(typeof(Xpand.XAF.Modules.Blazor.BlazorStartup))]
 ---> System.InvalidOperationException: Install the Xpand.XAF.Modules.Blazor package in the front end project and add: [assembly: HostingStartup(typeof(Xpand.XAF.Modules.Blazor.BlazorStartup))]
   at Xpand.XAF.Modules.Reactive.Services.XafApplicationRxExtensions.CheckBlazor(XafApplication xafApplication, String hostingStartupType, String requiredPackage)

I have already added the nuget package like so...

![image](https://user-images.githubusercontent.com/31090302/196095056-dc658934-a4d2-46c6-a378-80fdcb420661.png)

**Comment by ramilcatalandomingo** [comment]
Hello @apobekiaris. Would you know a version of your JobScheduler.Hangfire extension that works with XAF 22.1.5?

**Comment by apobekiaris** [comment]
did u tried following the instructions

>---> System.InvalidOperationException: Install the Xpand.XAF.Modules.Blazor package in the front end project and add: [assembly: HostingStartup(typeof(Xpand.XAF.Modules.Blazor.BlazorStartup))]
at Xpand.XAF.Modules.Reactive.Services.XafApplicationRxExtensions.CheckBlazor(XafApplication xafApplication, String hostingStartupType, String requiredPackage)

**Comment by apobekiaris** [comment]
also I see 1.7.31 hangfire version  which does not match the one the package uses, but I am not certain why

```ps1
Get-NugetPackageDependencies Xpand.xaf.modules.Jobscheduler.Hangfire|sls hang

Hangfire.AspNetCore [1.7.30, )
Hangfire.Core [1.7.30, )
```

**Comment by ramilcatalandomingo** [comment]
> did u tried following the instructions
> 
> > ---> System.InvalidOperationException: Install the Xpand.XAF.Modules.Blazor package in the front end project and add: [assembly: HostingStartup(typeof(Xpand.XAF.Modules.Blazor.BlazorStartup))]
> > at Xpand.XAF.Modules.Reactive.Services.XafApplicationRxExtensions.CheckBlazor(XafApplication xafApplication, String hostingStartupType, String requiredPackage)

I apologize @apobekiaris but I am still learning XAF so even though I installed this package, I am uncertain how to add the BlazorStartup to the Startup.cs class.  Can you share some code on how to do this please?

**Comment by ramilcatalandomingo** [comment]
> also I see 1.7.31 hangfire version which does not match the one the package uses, but I am not certain why
> 
> ```powershell
> Get-NugetPackageDependencies Xpand.xaf.modules.Jobscheduler.Hangfire|sls hang
> 
> Hangfire.AspNetCore [1.7.30, )
> Hangfire.Core [1.7.30, )
> ```

I went ahead and downgraded Hangfire package to 1.7.30.

**Comment by apobekiaris** [comment]
@ramilcatalandomingo I guess you work veru hard you need a break :)

the exception instructs you:

> Install the Xpand.XAF.Modules.Blazor package in the front end project and add: [assembly: HostingStartup(typeof(Xpand.XAF.Modules.Blazor.BlazorStartup))]

what is not clear in this message

**Comment by apobekiaris** [comment]
here a sample registration from the easutests project

https://github.com/eXpandFramework/Reactive.XAF/blob/6ac0a6c27281c9d55c7ac53256fb058a204806fa/src/Tests/EasyTests/TestApplication/TestApplication.Blazor.Server/Startup.cs#L20-L23

**Comment by ramilcatalandomingo** [comment]
Thank you so much @apobekiaris.  I apologize for the newbie questions.  I appreciate your help.  By the way, would you know when is the timeline of the next release of your extension that fixes this issue?

**Comment by apobekiaris** [comment]
yesterday but appearently there are delays working on them, cannot estimate the unknown

**Comment by ramilcatalandomingo** [comment]
Okay understood.  Thank you @apobekiaris

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
