### ISSUE TITLE
HyperLinkPropertyEditor Nullreference

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#959]
Hi Tolis,

I converted the first project to .net6. With the HyperLinkPropertyEditor I get the error

```
iXISXRM.Win Error: 0 : 21.10.22 17:36:01.687	================================================================================
The error occurred:

	Type:       InvalidOperationException
	Message:    Exception occurs while assigning the 'XpandDetailView, ID:XpandPermissionPolicyUser_DetailView' view to XpandWinWindow:
Object reference not set to an instance of an object.
	Data:       0 entries
	Stack trace:

   at DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.CreateWindow(ShowViewParameters parameters, ShowViewSource showViewSource, Boolean isMain)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.CreateInspectorWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewInInspector(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.WinShowViewStrategyBase.ShowViewInNewWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Win.MdiShowViewStrategy.ShowViewInCurrentWindow(ShowViewParameters parameters, ShowViewSource showViewSource)
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	----------------
	InnerException:

			Type:       NullReferenceException
			Message:    Object reference not set to an instance of an object.
			Data:       0 entries
			Stack trace:

   at Xpand.ExpressApp.Win.PropertyEditors.HyperLinkPropertyEditor.CreateControlCore()
   at DevExpress.ExpressApp.Editors.ViewItem.CreateControl()
   at DevExpress.ExpressApp.Win.Layout.WinLayoutManager.controlItem_QueryControl(Object sender, QueryControlEventArgs e)
   at DevExpress.ExpressApp.Win.Layout.XafLayoutControlItem.RaiseQueryControl()
   at DevExpress.ExpressApp.Win.Layout.XafLayoutControlItem.EnsureControl()
   at DevExpress.XtraLayout.BaseLayoutItem.SetVisible(Boolean lVisible)
   at DevExpress.XtraLayout.LayoutGroup.UpdateChild(BaseLayoutItem item, Boolean visible)
   at DevExpress.XtraLayout.LayoutGroup.UpdateChildren(Boolean visible)
   at DevExpress.XtraLayout.LayoutGroup.UpdateChild(BaseLayoutItem item, Boolean visible)
   at DevExpress.XtraLayout.LayoutGroup.UpdateChildren(Boolean visible)
   at DevExpress.XtraLayout.LayoutGroup.UpdateChild(BaseLayoutItem item, Boolean visible)
   at DevExpress.XtraLayout.LayoutGroup.UpdateChildren(Boolean visible)
   at DevExpress.XtraLayout.LayoutGroup.UpdateChild(BaseLayoutItem item, Boolean visible)
   at DevExpress.XtraLayout.LayoutGroup.UpdateChildren(Boolean visible)
   at DevExpress.XtraLayout.LayoutControlImplementor.UpdateRoot()
   at DevExpress.XtraLayout.LayoutControlImplementor.InvalidateRootOffsetControlsAndScrolls()
   at DevExpress.XtraLayout.LayoutControlImplementor.Invalidate()
   at DevExpress.XtraLayout.LayoutDesignerMethodsProvider.DevExpress.XtraLayout.ILayoutDesignerMethods.EndChangeUpdate()
   at DevExpress.XtraLayout.LayoutControlImplementor.ProcessLookAndFeelStyleChanged()
   at DevExpress.XtraLayout.LayoutControlImplementor.OnLookAndFeelStyleChanged(Object sender, EventArgs e)
   at DevExpress.XtraLayout.LayoutControlImplementor.EndInitCore()
   at DevExpress.ExpressApp.Win.Layout.WinLayoutManager.LayoutControls(IModelNode layoutNode, ViewItemsCollection viewItems)
   at DevExpress.ExpressApp.View.CreateControls()
   at DevExpress.ExpressApp.Win.Templates.ViewSiteManager.EnsureViewControl()
   at DevExpress.ExpressApp.Win.Templates.ViewSiteManager.FillViewSite()
   at DevExpress.ExpressApp.Win.Templates.Ribbon.DetailRibbonFormV2.DevExpress.ExpressApp.Templates.IFrameTemplate.SetView(View view)
   at DevExpress.ExpressApp.Frame.SetTemplateView(View view)
   at DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
			InnerException is null
```

I can not repro it in a new blank project. Do you have an idea?

**Comment by apobekiaris** [comment]
not anyrthing that will makse sense given the exception site

**Comment by CWolffIF** [comment]
hi, once you give an instruction how to debug with the expand code. But I can´t find it anymore. Can you help me?

**Comment by apobekiaris** [comment]
I am not sure what u looking for the symbols are distributed with nuget so once in your bin this applies

https://github.com/eXpandFramework/Reactive.XAF/wiki/How-to-boost-your-DevExpress-Debugging-Experience

**Comment by apobekiaris** [comment]
however u could also copy the source code of the editor add it in your source code, change the namespqace and use it instead. It will break in your code.
