### ISSUE TITLE
InvalidOperationException WarmUpApplication Backend Web API Service

### ISSUE THREAD

**Issue by TheGermanNiko** [eXpandFramework/eXpand#967]
Hi we recently startet upgrading our Application to net6, as a part of it i tried to include the Web API from DevExpress to it.
Everytime i try to start the Web API it throws an Exception.

System.InvalidOperationException: Exception occurs while initializing the 'Xpand.XAF.Modules.ModelMapper.ModelMapperModule' module: DevExpress.ExpressApp.AspNetCore.WebApi.Core.Internal.WarmUpApplication.

I created a simple Demo Project containing all refrences as they are used in our Application.
Any ideas what causes that exception?

𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲

Create the Application and attempt to start the Web API.

---------------------------------------------------------------
System.InvalidOperationException: Exception occurs while initializing the 'Xpand.XAF.Modules.ModelMapper.ModelMapperModule' module: DevExpress.ExpressApp.AspNetCore.WebApi.Core.Internal.WarmUpApplication
 ---> System.NotImplementedException: DevExpress.ExpressApp.AspNetCore.WebApi.Core.Internal.WarmUpApplication
   at Xpand.Extensions.XAF.XafApplicationExtensions.XafApplicationExtensions.GetPlatform(XafApplication application)
   at Xpand.Extensions.XAF.XafApplicationExtensions.XafApplicationExtensions.GetPlatform(IEnumerable`1 moduleBases)
   at Xpand.XAF.Modules.ModelMapper.Services.ModelExtendingService.ConnectExtendingService(ApplicationModulesManager applicationModulesManager)
   at Xpand.XAF.Modules.ModelMapper.ModelMapperModule.Setup(ApplicationModulesManager moduleManager)
   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager applicationModulesManager)
   --- End of inner exception stack trace ---

------------------------------------------------------------------

Attached the Demo Project
[DXApplication2.zip](https://github.com/eXpandFramework/eXpand/files/10236165/DXApplication2.zip)

**Comment by apobekiaris** [comment]
I did not test your sample the cause I see you use `ModelMapperModule` which does not support the Blazor or WebAPI projects

**Comment by TheGermanNiko** [comment]
I see, thank you for the information.
