### ISSUE TITLE
Unable to load Blazor XAF Model Editor in v22.2.3 when integrating Jobscheduler.Hangfire module

### ISSUE THREAD

**Issue by ss-carlo** [eXpandFramework/eXpand#973]
Hi, 

I am trying to integrate the JobScheduler.Hangfire module to a Blazor server but I am encountering an issue when opening the model editor. Blazor application is running without errors but when I try to open the model editor in the Blazor Server project, it crashes and is giving off the following error:

Could not load file or assembly 'System.Interactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. Reference assemblies cannot be loaded for execution. (0x80131058)

at Xpand.XAF.Modules.Reactive.Services.AttributesExtensions.<>c.<InvisibleInAllViewsAttribute>b__6_1(ValueTuple`2[] attributes)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1332
--- End of stack trace from previous location ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
   at System.Reactive.ExceptionHelpers.Throw(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:line 16
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 62
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Catch`2._.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Catch.cs:line 137
   at System.Reactive.Linq.ObservableImpl.ThrowImmediate`1.Run(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Throw.cs:line 56
   at System.Reactive.BasicProducer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 66
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 374
   at System.Reactive.Linq.ObservableImpl.Catch`2._.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Catch.cs:line 133
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 62
   at System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error) in /_/Rx.NET/Source/src/System.Reactive/Internal/HalfSerializer.cs:line 77
   at System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnError(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeUntil.cs:line 62
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 62
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 62
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 887
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 887
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 887
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 958
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1336
   at System.Reactive.Linq.ObservableImpl.ReturnImmediate`1.Run(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Return.cs:line 62
   at System.Reactive.BasicProducer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 43
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 374
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1315
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 374
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.IgnoreElements`1.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/IgnoreElements.cs:line 18
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 374
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 22
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 374
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Where.cs:line 27
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 374
   at System.Reactive.TailRecursiveSink`1.Drain() in /_/Rx.NET/Source/src/System.Reactive/Internal/TailRecursiveSink.cs:line 128
   at System.Reactive.TailRecursiveSink`1.Run(IEnumerable`1 sources) in /_/Rx.NET/Source/src/System.Reactive/Internal/TailRecursiveSink.cs:line 34
   at System.Reactive.Linq.ObservableImpl.Concat`1.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Concat.cs:line 20
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 374
   at System.Reactive.Linq.ObservableImpl.Finally`1._.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Finally.cs:line 38
   at System.Reactive.Linq.ObservableImpl.Finally`1.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Finally.cs:line 23
   at System.Reactive.Producer`2.<>c.<SubscribeRaw>b__1_0(ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 121
   at System.Reactive.Concurrency.Scheduler.<>c__75`1.<ScheduleAction>b__75_0(IScheduler _, ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 65
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/CurrentThreadScheduler.cs:line 101
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/LocalScheduler.cs:line 32
   at System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 61
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 374
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.SubscribeInner(IObservable`1 inner) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 934
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 880
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.<GetHandler>b__1(Object sender, TEventArgs eventArgs) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEventPattern.cs:line 39
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at DevExpress.ExpressApp.ApplicationModulesManager.OnCustomizeTypesInfo(ITypesInfo typesInfo)
   at DevExpress.ExpressApp.ApplicationModulesManager.DoCustomizeTypesInfo(ITypesInfo typesInfo)
   at DevExpress.ExpressApp.ApplicationModulesManager.LoadTypesInfo(ITypesInfo typesInfo)
   at DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   at DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(XafApplication application, String configFileName, String assembliesPath, Action initializeTypeInfoSources)
   at DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, String targetDiffFileName, IDisposable& obj, ILogger logger)
   at DevExpress.ExpressApp.Design.ModelEditor.ModelEditorFormController.CreateModelEditorController()
   at DevExpress.ExpressApp.Design.ModelEditor.ModelEditorFormController.Init()
   at DevExpress.ExpressApp.Design.ModelEditorServer.ServerHost.CreateNewModelEditor(String fileName, ModelEditorInfo meInfo, String projectUniqueName, Dictionary`2 settings, String frameworkVersion)
   at DevExpress.ExpressApp.Design.ModelEditorServer.ServerHost.<>c__DisplayClass66_0.<OpenModelEditor>b__1()
   at DevExpress.ExpressApp.Design.ModelEditorServer.UiRunner.<>c__DisplayClass3_0.<RunOnUIThreadCore>b__0(Object _)
--- End of stack trace from previous location ---
   at DevExpress.ExpressApp.Design.ModelEditorServer.ServerHost.OpenModelEditor(String fileName, String projectUniqueName, Dictionary`2 settings, String frameworkVersion)
   at DevExpress.ExpressApp.Design.ModelEditorServer.ServerProtocol.OpenModelEditor(String xafmlFileName, String projectUniqueName, Dictionary`2 settings, String frameworkVersion)
   at InvokeStub_IServerReceiveProtocol.OpenModelEditor(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
   at DevExpress.ExpressApp.Design.ModelEditorServer.LoggedServerProtocol`1.Invoke(MethodInfo targetMethod, Object[] args)
   at generatedProxy_1.OpenModelEditor(String, String, Dictionary`2, String)
   at InvokeStub_generatedProxy_1.OpenModelEditor(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
----------InnerException----------
Cannot load a reference assembly for execution.

----------InnerException----------
Could not load file or assembly 'System.Interactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. Reference assemblies cannot be loaded for execution. (0x80131058)
----------StackTrace----------
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DevExpress.ExpressApp.Design.ClientHost.<OpenModelEditorAsync>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DevExpress.ExpressApp.Design.ClientHost.<>c__DisplayClass134_0.<<OpenModelEditor>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DevExpress.ExpressApp.Design.ClientHost.<>c__DisplayClass120_0.<<RunAsync>b__0>d.MoveNext()

**Comment by ss-carlo** [comment]
Thanks, it is working now!
