### ISSUE TITLE
eXpand Modeleditor did not open

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#986]
After moving to 22.2.403 and 4.222.5 the eXpand Modeleditor did not open anymore.

Loading Editor 4.222.5.0 is displaying and after that I get the message:

![image](https://user-images.githubusercontent.com/43132306/226176688-cf7cb076-d904-44ff-b7f6-9d3f2100b19f.png)

**Comment by apobekiaris** [comment]
sample me so I can verify it, you know the drill at least in my apps I see no issue.

**Comment by CWolffIF** [comment]
I can´t repro it with a simple sample. But in my project the problem is there.
Any Idea how to find out?

Here is the logtext

20.03.23 15:32:32.900    ================================================================================
The error occurred:

    Type:       BadImageFormatException
    Message:    Could not load file or assembly 'System.Interactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. Reference assemblies cannot be loaded for execution. (0x80131058)
    Data:       0 entries
    Stack trace:

   at Xpand.XAF.Modules.Reactive.Services.AttributesExtensions.<>c.<InvisibleInAllViewsAttribute>b__6_1(ValueTuple`2[] attributes)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1332
--- End of stack trace from previous location ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
   at System.Reactive.ExceptionHelpers.Throw(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:line 16
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 62
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error) in /_/Rx.NET/Source/src/System.Reactive/Internal/HalfSerializer.cs:line 77
   at System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnError(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeUntil.cs:line 62
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 246
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 887
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 887
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 887
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 887
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 958
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1336
   at System.Reactive.Linq.ObservableImpl.ReturnImmediate`1.Run(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Return.cs:line 62
   at System.Reactive.BasicProducer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 66
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1315
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.IgnoreElements`1.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/IgnoreElements.cs:line 18
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 22
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Where.cs:line 27
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.TailRecursiveSink`1.Drain() in /_/Rx.NET/Source/src/System.Reactive/Internal/TailRecursiveSink.cs:line 128
   at System.Reactive.TailRecursiveSink`1.Run(IEnumerable`1 sources) in /_/Rx.NET/Source/src/System.Reactive/Internal/TailRecursiveSink.cs:line 34
   at System.Reactive.Linq.ObservableImpl.Concat`1.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Concat.cs:line 20
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Linq.ObservableImpl.Finally`1._.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Finally.cs:line 38
   at System.Reactive.Linq.ObservableImpl.Finally`1.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Finally.cs:line 23
   at System.Reactive.Producer`2.<>c.<SubscribeRaw>b__1_0(ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 121
   at System.Reactive.Concurrency.Scheduler.<>c__75`1.<ScheduleAction>b__75_0(IScheduler _, ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 65
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/CurrentThreadScheduler.cs:line 101
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/LocalScheduler.cs:line 32
   at System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 61
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.SubscribeInner(IObservable`1 inner) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 934
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 880
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 136
   at System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.<GetHandler>b__1(Object sender, TEventArgs eventArgs) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEventPattern.cs:line 39
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at DevExpress.ExpressApp.ApplicationModulesManager.OnCustomizeTypesInfo(ITypesInfo typesInfo)
   at DevExpress.ExpressApp.ApplicationModulesManager.DoCustomizeTypesInfo(ITypesInfo typesInfo)
   at DevExpress.ExpressApp.ApplicationModulesManager.LoadTypesInfo(ITypesInfo typesInfo)
   at DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   at DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(ModuleBase module, String assembliesPath, List`1 additionalModules, ISecurityStrategyBase securityInstance, Action initializeTypeInfoSources)
   at DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(ModuleBase module, String assembliesPath, Action initializeTypeInfoSources)
   at DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, String targetDiffFileName, IDisposable& obj, ILogger logger)
   at DevExpress.ExpressApp.Design.ModelEditor.ModelEditorFormController.CreateModelEditorController()
   at DevExpress.ExpressApp.Design.ModelEditor.ModelEditorFormController.Init()
   at DevExpress.ExpressApp.Design.ModelEditorServer.ServerHost.CreateNewModelEditor(String fileName, ModelEditorInfo meInfo, String projectUniqueName, Dictionary`2 settings, String frameworkVersion)
   at DevExpress.ExpressApp.Design.ModelEditorServer.ServerHost.<>c__DisplayClass66_0.<OpenModelEditor>b__1()
   at DevExpress.ExpressApp.Design.ModelEditorServer.UiRunner.<>c__DisplayClass3_0.<RunOnUIThreadCore>b__0(Object _)
    ----------------
    InnerException:

            Type:       BadImageFormatException
            Message:    Cannot load a reference assembly for execution.
            Data:       0 entries
            Stack trace:


            InnerException is null

**Comment by apobekiaris** [comment]
whats the plugin version? did you clean the C:\Users\Tolis\AppData\Roaming\Xpand.XAF.ModelEditor.Win\ and your bin and nugetcache?

**Comment by CWolffIF** [comment]
Hi,
I cleaned everything.
It is downloading 4.222.5.0 and here is a screenshot from the roaming directory
![image](https://user-images.githubusercontent.com/43132306/226550974-875b91c7-c0d0-408c-9c14-1552cfa70909.png)

**Comment by CWolffIF** [comment]
Seams it is using the 4.222.2.1 Xpand.XAF.ModelEditor.Win.exe and not the Xpand.XAF.ModelEditor.WinDesktop.exe from inside VS2022

**Comment by TheGermanNiko** [comment]
[Test.zip](https://github.com/eXpandFramework/eXpand/files/11026766/Test.zip)
Here is an example of the exeption for the plattform agnostic module.

**Comment by apobekiaris** [comment]
the stack points towards the scheduler may I assume that in your sample you installed JobScheduler at least ?

**Comment by apobekiaris** [comment]
nevermid i just saw the sample let me have a look first

**Comment by apobekiaris** [comment]
thnks I repro it I ll update u once I have a solution

**Comment by apobekiaris** [comment]
I managed to start ME with the latest VS plugin 22.4.2 and Rider 2022.2.4.3. Make sure u allow prerelease to test it

![image](https://user-images.githubusercontent.com/159464/227236314-207416e5-0caf-44c8-ac7f-8c185f61e5a3.png)
![image](https://user-images.githubusercontent.com/159464/227236659-51dc2618-b267-4057-9ccb-58fe2b0224c9.png)

**Comment by TheGermanNiko** [comment]
Editor opens up again this way, thank you for your help.

**Comment by expand** [comment]
The pre-release [4.222.11.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.222.11.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Fix ME conflict #986](https://github.com/eXpandFramework/Reactive.XAF/commit/d324efacbf59b850549fe876b222cb25d67cda07)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
<a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions'>Xpand.Extensions v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Blazor'>Xpand.Extensions.Blazor v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil'>Xpand.Extensions.Mono.Cecil v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud'>Xpand.Extensions.Office.Cloud v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor'>Xpand.Extensions.Office.Cloud.Google.Blazor v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive'>Xpand.Extensions.Reactive v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF'>Xpand.Extensions.XAF v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo'>Xpand.Extensions.XAF.Xpo v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Blazor v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Common v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.EasyTest v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/tools/Xpand.VersionConverter'>Xpand.VersionConverter v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Core.All v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/AutoCommit'>Xpand.XAF.Modules.AutoCommit v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Blazor'>Xpand.XAF.Modules.Blazor v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/BulkObjectUpdate'>Xpand.XAF.Modules.BulkObjectUpdate v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneMemberValue'>Xpand.XAF.Modules.CloneMemberValue v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneModelView'>Xpand.XAF.Modules.CloneModelView v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Email'>Xpand.XAF.Modules.Email v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/GridListEditor'>Xpand.XAF.Modules.GridListEditor v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/HideToolBar'>Xpand.XAF.Modules.HideToolBar v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire'>Xpand.XAF.Modules.JobScheduler.Hangfire v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Notification'>Xpand.XAF.Modules.JobScheduler.Notification v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/MasterDetail'>Xpand.XAF.Modules.MasterDetail v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelMapper'>Xpand.XAF.Modules.ModelMapper v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelViewInheritance'>Xpand.XAF.Modules.ModelViewInheritance v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google'>Xpand.XAF.Modules.Office.Cloud.Google v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar'>Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks'>Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.DocumentStyleManager'>Xpand.XAF.Modules.Office.DocumentStyleManager v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/OneView'>Xpand.XAF.Modules.OneView v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/PositionInListView'>Xpand.XAF.Modules.PositionInListView v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ProgressBarViewItem'>Xpand.XAF.Modules.ProgressBarViewItem v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RazorView'>Xpand.XAF.Modules.RazorView v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive'>Xpand.XAF.Modules.Reactive v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger'>Xpand.XAF.Modules.Reactive.Logger v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win'>Xpand.XAF.Modules.Reactive.Logger.Client.Win v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Hub'>Xpand.XAF.Modules.Reactive.Logger.Hub v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Rest'>Xpand.XAF.Modules.Reactive.Rest v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RefreshView'>Xpand.XAF.Modules.RefreshView v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SequenceGenerator'>Xpand.XAF.Modules.SequenceGenerator v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Speech'>Xpand.XAF.Modules.Speech v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SpellChecker'>Xpand.XAF.Modules.SpellChecker v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/StoreToDisk'>Xpand.XAF.Modules.StoreToDisk v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SuppressConfirmation'>Xpand.XAF.Modules.SuppressConfirmation v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/TenantManager'>Xpand.XAF.Modules.TenantManager v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewEditMode'>Xpand.XAF.Modules.ViewEditMode v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewItemValue'>Xpand.XAF.Modules.ViewItemValue v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewWizard'>Xpand.XAF.Modules.ViewWizard v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Windows'>Xpand.XAF.Modules.Windows v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Web.All v.4.222.13</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Win.All v.4.222.13</a></br>
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.
